Repository IQSS/dataverse, pull requests merged in 2021-08, with the labels that each got.

#8034 IQSS/8032 Add optional flag to trigger update of PID at provider during migrate
  doc/sphinx-guides/source/admin/dataverses-datasets.rst
  doc/sphinx-guides/source/developers/dataset-migration-api.rst
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JSONLDUtil.java
Labels: DANS

#7958 SPO/7388 lang attributes in ddi export
  doc/sphinx-guides/source/installation/config.rst
  src/main/java/edu/harvard/iq/dataverse/ControlledVocabularyValue.java
  src/main/java/edu/harvard/iq/dataverse/DatasetField.java
  src/main/java/edu/harvard/iq/dataverse/DatasetPage.java
  src/main/java/edu/harvard/iq/dataverse/DataversePage.java
  src/main/java/edu/harvard/iq/dataverse/DvObjectContainer.java
  src/main/java/edu/harvard/iq/dataverse/SettingsWrapper.java
  src/main/java/edu/harvard/iq/dataverse/api/dto/DatasetDTO.java
  src/main/java/edu/harvard/iq/dataverse/api/dto/MetadataBlockDTO.java
  src/main/java/edu/harvard/iq/dataverse/export/ddi/DdiExportUtil.java
  src/main/java/edu/harvard/iq/dataverse/settings/SettingsServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/util/BundleUtil.java
  src/main/java/edu/harvard/iq/dataverse/util/SystemConfig.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java
  src/main/java/propertyFiles/Bundle.properties
  src/main/resources/db/migration/V5.5.0.6__7388_i18n_metadata.sql
  src/main/webapp/dataset.xhtml
  src/main/webapp/dataverse.xhtml
  src/main/webapp/metadataFragment.xhtml
  src/test/java/edu/harvard/iq/dataverse/export/SchemaDotOrgExporterTest.java
  src/test/java/edu/harvard/iq/dataverse/export/ddi/dataset-finch1.json
  src/test/java/edu/harvard/iq/dataverse/export/ddi/dataset-finch1.xml
  src/test/java/edu/harvard/iq/dataverse/mocks/MockDatasetFieldSvc.java
Labels: SciencesPO

#7695 6953 mpconfig context param
  doc/release-notes/6953-dev-jsf-settings.md
  doc/sphinx-guides/source/developers/debugging.rst
  doc/sphinx-guides/source/developers/dev-environment.rst
  scripts/dev/dev-rebuild.sh
  src/main/resources/META-INF/microprofile-config.properties
  src/main/webapp/WEB-INF/web.xml
Labels: Type: Feature, Feature: Developer Guide, User Role: Sysadmin

#7959 SPO/6751 cvv i18n
  doc/sphinx-guides/source/installation/config.rst
  src/main/java/edu/harvard/iq/dataverse/DatasetFieldType.java
  src/main/java/edu/harvard/iq/dataverse/api/dto/MetadataBlockDTO.java
  src/main/java/edu/harvard/iq/dataverse/export/ddi/DdiExportUtil.java
  src/test/java/edu/harvard/iq/dataverse/export/DDIExporterTest.java
  src/test/java/edu/harvard/iq/dataverse/export/ddi/dataset-finch1.json
  src/test/java/edu/harvard/iq/dataverse/export/ddi/dataset-finch1.xml
  src/test/java/edu/harvard/iq/dataverse/export/ddi/exportfull.xml
  src/test/java/edu/harvard/iq/dataverse/feedback/FeedbackUtilTest.java
  src/test/java/edu/harvard/iq/dataverse/util/json/JsonParserTest.java
  src/test/java/edu/harvard/iq/dataverse/util/json/JsonPrinterTest.java
  src/test/resources/json/dataset-finch1.json
  src/test/resources/json/dataset-finch2.json
Labels: SciencesPO
