Repository IQSS/dataverse, pull requests merged in 2022-04, with the labels that each got.

#8534 8531 refactor validators
  pom.xml
  src/main/java/ValidationMessages.properties
  src/main/java/edu/harvard/iq/dataverse/DatasetFieldValueValidator.java
  src/main/java/edu/harvard/iq/dataverse/DatasetPage.java
  src/main/java/edu/harvard/iq/dataverse/DataverseContact.java
  src/main/java/edu/harvard/iq/dataverse/EMailValidator.java
  src/main/java/edu/harvard/iq/dataverse/MailServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/Shib.java
  src/main/java/edu/harvard/iq/dataverse/URLValidator.java
  src/main/java/edu/harvard/iq/dataverse/UserNameValidator.java
  src/main/java/edu/harvard/iq/dataverse/ValidateEmail.java
  src/main/java/edu/harvard/iq/dataverse/api/Admin.java
  src/main/java/edu/harvard/iq/dataverse/authorization/groups/impl/builtin/BuiltInGroupsProvider.java
  src/main/java/edu/harvard/iq/dataverse/authorization/providers/builtin/BuiltinUser.java
  src/main/java/edu/harvard/iq/dataverse/authorization/providers/builtin/DataverseUserPage.java
  src/main/java/edu/harvard/iq/dataverse/authorization/providers/oauth2/OAuth2FirstLoginPage.java
  src/main/java/edu/harvard/iq/dataverse/authorization/providers/shib/ShibUtil.java
  src/main/java/edu/harvard/iq/dataverse/authorization/users/AuthenticatedUser.java
  src/main/java/edu/harvard/iq/dataverse/passwordreset/PasswordResetPage.java
  src/main/java/edu/harvard/iq/dataverse/validation/EMailValidator.java
  src/main/java/edu/harvard/iq/dataverse/validation/URLValidator.java
  src/main/java/edu/harvard/iq/dataverse/validation/UserNameValidator.java
  src/main/java/edu/harvard/iq/dataverse/validation/ValidateEmail.java
  src/main/java/edu/harvard/iq/dataverse/validation/ValidateURL.java
  src/main/java/edu/harvard/iq/dataverse/validation/ValidateUserName.java
  src/main/java/propertyFiles/Bundle.properties
  src/test/java/edu/harvard/iq/dataverse/DatasetFieldValueValidatorTest.java
  src/test/java/edu/harvard/iq/dataverse/EMailValidatorTest.java
  src/test/java/edu/harvard/iq/dataverse/URLValidatorTest.java
  src/test/java/edu/harvard/iq/dataverse/UserNameValidatorTest.java
  src/test/java/edu/harvard/iq/dataverse/validation/EMailValidatorTest.java
  src/test/java/edu/harvard/iq/dataverse/validation/URLValidatorTest.java
  src/test/java/edu/harvard/iq/dataverse/validation/UserNameValidatorTest.java
Labels: Feature: Code Infrastructure

#8606 TDL/7493 Make BagGenerator threads configurable
  doc/sphinx-guides/source/admin/integrations.rst
  doc/sphinx-guides/source/developers/workflows.rst
  doc/sphinx-guides/source/installation/config.rst
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/AbstractSubmitToArchiveCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/DuraCloudSubmitToArchiveCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/GoogleCloudSubmitToArchiveCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/LocalSubmitToArchiveCommand.java
  src/main/java/edu/harvard/iq/dataverse/util/bagit/BagGenerator.java
Labels: TDL

#8308 8191 require toa or req access
  doc/release-notes/8191-require-toa-or-request-access.md
  scripts/issues/8191/datasets_without_toa_or_request_access
  scripts/search/tests/data/dataset-finch1.jsonld
  src/main/java/edu/harvard/iq/dataverse/Dataset.java
  src/main/java/edu/harvard/iq/dataverse/DatasetPage.java
  src/main/java/edu/harvard/iq/dataverse/DatasetVersion.java
  src/main/java/edu/harvard/iq/dataverse/EditDatafilesPage.java
  src/main/java/edu/harvard/iq/dataverse/FilePage.java
  src/main/java/edu/harvard/iq/dataverse/Template.java
  src/main/java/edu/harvard/iq/dataverse/TermsOfUseAndAccess.java
  src/main/java/edu/harvard/iq/dataverse/TermsOfUseAndAccessValidator.java
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/main/java/edu/harvard/iq/dataverse/api/Dataverses.java
  src/main/java/edu/harvard/iq/dataverse/api/datadeposit/StatementManagerImpl.java
  src/main/java/edu/harvard/iq/dataverse/api/datadeposit/SwordServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/AbstractDatasetCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/CuratePublishedDatasetVersionCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/FinalizeDatasetPublicationCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/PublishDatasetCommand.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonParser.java
  src/main/java/propertyFiles/.LCKBundle.properties~
  src/main/java/propertyFiles/Bundle.properties
  src/main/webapp/dataset-license-terms.xhtml
  src/main/webapp/dataset.xhtml
  src/main/webapp/editFilesFragment.xhtml
  src/main/webapp/editdatafiles.xhtml
  src/main/webapp/file-edit-button-fragment.xhtml
  src/main/webapp/file-edit-popup-fragment.xhtml
  src/main/webapp/file.xhtml
  src/main/webapp/filesFragment.xhtml
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
Labels: sz.Small
