Repository IQSS/dataverse, pull requests merged in 2022-02, with the labels that each got.

#8373 sec35 duracloud update
  pom.xml
Labels: Feature: Code Infrastructure, User Role: Sysadmin, dependencies

#8362 8094 Experimental CI Java 17 Maven Unittest build
  .github/workflows/maven_unit_test.yml
  pom.xml
  src/main/java/edu/harvard/iq/dataverse/harvest/server/xoai/XlistRecordsHandler.java
Labels: Type: Suggestion, Feature: Code Infrastructure

#8419 8094 disable 17 ci
  .github/workflows/maven_unit_test.yml
  src/main/java/edu/harvard/iq/dataverse/authorization/groups/impl/maildomain/MailDomainGroupServiceBean.java
Labels: Feature: Code Infrastructure

#8399 IQSS/8398 - move bag when complete
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/LocalSubmitToArchiveCommand.java
Labels: DANS
