Repository IQSS/dataverse, pull requests merged in 2022-12, with the labels that each got.

#9174 8290 harvest client api
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/api/HarvestingClients.java
  src/main/java/edu/harvard/iq/dataverse/harvest/client/HarvestingClient.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonParser.java
  src/test/java/edu/harvard/iq/dataverse/api/HarvestingClientsIT.java
  tests/integration-tests.txt
Labels: Size: 3

#8983 feat(upload): make upload file storage path configurable #6656
  doc/release-notes/6656-file-uploads.md
  doc/sphinx-guides/source/installation/config.rst
  src/main/webapp/WEB-INF/glassfish-web.xml
Labels: bk2211, Size: 33

#9125 8346 License internationalizataion
  doc/sphinx-guides/source/installation/config.rst
  src/main/java/edu/harvard/iq/dataverse/dataset/DatasetUtil.java
  src/main/java/propertyFiles/License.properties
  src/main/webapp/dataset-license-terms.xhtml
  src/main/webapp/datasetLicenseInfoFragment.xhtml
Labels: Size: 10

#9107 fix for cvv and editMetadata replace=true, and test
  doc/sphinx-guides/source/_static/api/dataset-add-subject-metadata.json
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
Labels: DANS, Size: 3

#9213 #8944 - Extend 'metadatablocks/{block_id}' endpoint JSON output
  doc/release-notes/8944-metadatablocks.md
  doc/sphinx-guides/source/admin/metadatacustomization.rst
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java
  src/test/java/edu/harvard/iq/dataverse/api/MetadataBlocksIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
  tests/integration-tests.txt
Labels: bk2211, Size: 33

#9187 7940 stop harvest in progress
  doc/release-notes/7940-stop-harvest-in-progress
  doc/sphinx-guides/source/admin/harvestclients.rst
  src/main/java/edu/harvard/iq/dataverse/DashboardPage.java
  src/main/java/edu/harvard/iq/dataverse/harvest/client/ClientHarvestRun.java
  src/main/java/edu/harvard/iq/dataverse/harvest/client/HarvesterServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/harvest/client/HarvestingClientServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/harvest/client/StopHarvestException.java
  src/main/java/propertyFiles/Bundle.properties
  src/main/webapp/dashboard.xhtml
Labels: Size: 10

#9227 8843 more harvest tests
  modules/dataverse-parent/pom.xml
  src/main/java/edu/harvard/iq/dataverse/api/HarvestingClients.java
  src/main/java/edu/harvard/iq/dataverse/harvest/client/FastGetRecord.java
  src/main/java/edu/harvard/iq/dataverse/harvest/client/HarvesterServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/harvest/server/xoai/DataverseXoaiItemRepository.java
  src/test/java/edu/harvard/iq/dataverse/api/HarvestingClientsIT.java
  src/test/java/edu/harvard/iq/dataverse/api/HarvestingServerIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: Size: 10

#9173 QDR/9172-fix messages
  src/main/java/edu/harvard/iq/dataverse/util/MailUtil.java
Labels: Size: 3

#9226 import function DatasetUtil
  src/main/webapp/dataset-license-terms.xhtml
Labels: Size: 3

#8962 IQSS/8730 - fix direct upload progress
  src/main/webapp/resources/js/fileupload.js
Labels: DataverseNO, bk2211, Size: 3

#8933 8932 container base image
  .github/workflows/container_base_push.yml
  .github/workflows/shellcheck.yml
  .github/workflows/shellspec.yml
  doc/sphinx-guides/source/container/base-image.rst
  doc/sphinx-guides/source/container/index.rst
  doc/sphinx-guides/source/developers/containers.rst
  doc/sphinx-guides/source/index.rst
  modules/container-base/.gitignore
  modules/container-base/README.md
  modules/container-base/pom.xml
  modules/container-base/src/main/docker/Dockerfile
  modules/container-base/src/main/docker/assembly.xml
  modules/container-base/src/main/docker/scripts/entrypoint.sh
  modules/container-base/src/main/docker/scripts/init_1_generate_deploy_commands.sh
  modules/container-base/src/main/docker/scripts/init_1_generate_devmode_commands.sh
  modules/container-base/src/main/docker/scripts/removeExpiredCaCerts.sh
  modules/container-base/src/main/docker/scripts/startInForeground.sh
  modules/dataverse-parent/pom.xml
Labels: Containers & Cloud, Working Group: SWC, Size: 3

#8824 7000 mpconfig version
  doc/sphinx-guides/source/developers/making-releases.rst
  doc/sphinx-guides/source/developers/tips.rst
  src/main/java/edu/harvard/iq/dataverse/util/SystemConfig.java
  src/test/java/edu/harvard/iq/dataverse/util/SystemConfigTest.java
Labels: Feature: Code Infrastructure, Feature: Developer Guide, Containers & Cloud, bk2211, Size: 3

#9076 #9074 - Added support for building sphinx docs using python 3.10+
  doc/sphinx-guides/requirements.txt
Labels: bk2211, Size: 3

#9236 8932 - fix pushing to Docker Hub
  .github/workflows/container_base_push.yml
Labels: Containers & Cloud, Size: 3

#8826 7000 mpconfig fqdn & siteUrl
  doc/sphinx-guides/source/installation/config.rst
  src/main/java/edu/harvard/iq/dataverse/HandlenetServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/api/Info.java
  src/main/java/edu/harvard/iq/dataverse/export/ddi/DdiExportUtil.java
  src/main/java/edu/harvard/iq/dataverse/harvest/server/web/servlet/OAIServlet.java
  src/main/java/edu/harvard/iq/dataverse/settings/JvmSettings.java
  src/main/java/edu/harvard/iq/dataverse/util/SystemConfig.java
  src/main/resources/META-INF/microprofile-config.properties
  src/test/java/edu/harvard/iq/dataverse/export/SchemaDotOrgExporterTest.java
  src/test/java/edu/harvard/iq/dataverse/externaltools/ExternalToolHandlerTest.java
  src/test/java/edu/harvard/iq/dataverse/util/UrlTokenUtilTest.java
Labels: Feature: Code Infrastructure, Feature: Installation Guide, User Role: Sysadmin, bk2211, Size: 3

#8830 7000 mpconfig rserve
  doc/sphinx-guides/source/installation/config.rst
  src/main/java/edu/harvard/iq/dataverse/ingest/tabulardata/impl/plugins/rdata/RDATAFileReader.java
  src/main/java/edu/harvard/iq/dataverse/rserve/RemoteDataFrameService.java
  src/main/java/edu/harvard/iq/dataverse/settings/JvmSettings.java
  src/main/resources/META-INF/microprofile-config.properties
Labels: Type: Feature, Feature: Code Infrastructure, Feature: Installation Guide, User Role: Sysadmin, Containers & Cloud, bk2211, Size: 3

#7877 7844 codemeta schema
  doc/release-notes/7844-codemeta.md
  doc/sphinx-guides/source/user/appendix.rst
  scripts/api/data/metadatablocks/codemeta.tsv
  scripts/api/setup-datasetfields.sh
  src/main/java/propertyFiles/codeMeta20.properties
Labels: Feature: Metadata, Working Group: SWC, HERMES, NIH OTA: 1.3.1, bk2211, Size: 10

#8972 Trigger auto-analyze more frequently for guestbook estimates
  doc/release-notes/8840-improved-download-estimate.md
  src/main/resources/db/migration/V5.13.0.3__8840-improve-guestbook-estimates.sql
Labels: bk2211, Size: 3

#8825 7000 mpconfig solr
  doc/sphinx-guides/source/installation/config.rst
  src/main/java/edu/harvard/iq/dataverse/search/IndexServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/search/SolrClientService.java
  src/main/java/edu/harvard/iq/dataverse/search/SolrIndexServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/settings/JvmSettings.java
  src/main/java/edu/harvard/iq/dataverse/settings/SettingsServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/util/SystemConfig.java
  src/main/resources/META-INF/microprofile-config.properties
  src/test/java/edu/harvard/iq/dataverse/search/IndexServiceBeanTest.java
  src/test/java/edu/harvard/iq/dataverse/search/SolrClientServiceTest.java
  src/test/java/edu/harvard/iq/dataverse/util/SystemConfigTest.java
Labels: Feature: Code Infrastructure, Feature: Installation Guide, User Role: Sysadmin, Containers & Cloud, Feature: Indexing, bk2211, Size: 3
