Repository IQSS/dataverse, pull requests merged in 2022-09, with the labels that each got.

#8925 GDCC/8924 - Check archival status
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/main/java/edu/harvard/iq/dataverse/util/MarkupChecker.java
Labels: hdc, 3a

#8961 Change setting name
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/DRSSubmitToArchiveCommand.java
Labels: hdc, 3a

#8923 GDCC/Update storageIO processing to match RemoteOverlay
  src/main/java/edu/harvard/iq/dataverse/dataaccess/DataAccess.java
  src/main/java/edu/harvard/iq/dataverse/dataaccess/FileAccessIO.java
  src/main/java/edu/harvard/iq/dataverse/dataaccess/RemoteOverlayAccessIO.java
  src/main/java/edu/harvard/iq/dataverse/dataaccess/S3AccessIO.java
  src/main/java/edu/harvard/iq/dataverse/dataaccess/StorageIO.java
  src/main/resources/db/migration/V5.11.1.6__storageconstraint.sql
  src/test/java/edu/harvard/iq/dataverse/dataaccess/FileAccessIOTest.java
  src/test/java/edu/harvard/iq/dataverse/dataaccess/S3AccessIOTest.java
Labels: Type: Bug

#8823 7000 mpconfig basic infra
  doc/release-notes/7000-mpconfig-support.md
  doc/sphinx-guides/source/developers/configuration.rst
  doc/sphinx-guides/source/developers/testing.rst
  modules/dataverse-parent/pom.xml
  pom.xml
  src/main/java/edu/harvard/iq/dataverse/settings/JvmSettings.java
  src/main/java/edu/harvard/iq/dataverse/settings/source/AliasConfigSource.java
  src/main/java/edu/harvard/iq/dataverse/settings/source/DbSettingConfigHelper.java
  src/main/java/edu/harvard/iq/dataverse/settings/source/DbSettingConfigSource.java
  src/main/java/edu/harvard/iq/dataverse/settings/spi/DbSettingConfigSourceProvider.java
  src/main/resources/META-INF/microprofile-config.properties
  src/main/resources/META-INF/services/org.eclipse.microprofile.config.spi.ConfigSourceProvider
  src/test/java/edu/harvard/iq/dataverse/settings/JvmSettingsTest.java
  src/test/java/edu/harvard/iq/dataverse/settings/source/AliasConfigSourceTest.java
  src/test/java/edu/harvard/iq/dataverse/settings/source/DbSettingConfigSourceTest.java
  src/test/java/edu/harvard/iq/dataverse/util/testing/JvmSetting.java
  src/test/java/edu/harvard/iq/dataverse/util/testing/JvmSettingExtension.java
  src/test/java/edu/harvard/iq/dataverse/util/testing/SystemProperty.java
  src/test/java/edu/harvard/iq/dataverse/util/testing/SystemPropertyExtension.java
Labels: Type: Feature, Feature: Code Infrastructure, Feature: Developer Guide, Feature: Admin Guide, User Role: Sysadmin, Containers & Cloud

#8891 GDCC/Globus and Big Data Support
  doc/sphinx-guides/source/developers/big-data-support.rst
  doc/sphinx-guides/source/installation/config.rst
  src/main/java/edu/harvard/iq/dataverse/DatasetLock.java
  src/main/java/edu/harvard/iq/dataverse/DatasetPage.java
  src/main/java/edu/harvard/iq/dataverse/DatasetServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/EditDatafilesPage.java
  src/main/java/edu/harvard/iq/dataverse/FilePage.java
  src/main/java/edu/harvard/iq/dataverse/MailServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/PermissionServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/SettingsWrapper.java
  src/main/java/edu/harvard/iq/dataverse/UserNotification.java
  src/main/java/edu/harvard/iq/dataverse/api/Access.java
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/main/java/edu/harvard/iq/dataverse/api/DownloadInstance.java
  src/main/java/edu/harvard/iq/dataverse/api/DownloadInstanceWriter.java
  src/main/java/edu/harvard/iq/dataverse/authorization/providers/builtin/DataverseUserPage.java
  src/main/java/edu/harvard/iq/dataverse/dataaccess/StorageIO.java
  src/main/java/edu/harvard/iq/dataverse/dataaccess/SwiftAccessIO.java
  src/main/java/edu/harvard/iq/dataverse/dataset/DatasetUtil.java
  src/main/java/edu/harvard/iq/dataverse/datasetutility/AddReplaceFileHelper.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/FinalizeDatasetPublicationCommand.java
  src/main/java/edu/harvard/iq/dataverse/externaltools/ExternalToolHandler.java
  src/main/java/edu/harvard/iq/dataverse/globus/AccessList.java
  src/main/java/edu/harvard/iq/dataverse/globus/AccessToken.java
  src/main/java/edu/harvard/iq/dataverse/globus/FileDetailsHolder.java
  src/main/java/edu/harvard/iq/dataverse/globus/GlobusServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/globus/GlobusTask.java
  src/main/java/edu/harvard/iq/dataverse/globus/Permissions.java
  src/main/java/edu/harvard/iq/dataverse/settings/SettingsServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/util/FileUtil.java
  src/main/java/edu/harvard/iq/dataverse/util/MailUtil.java
  src/main/java/edu/harvard/iq/dataverse/util/SystemConfig.java
  src/main/java/edu/harvard/iq/dataverse/util/URLTokenUtil.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java
  src/main/java/propertyFiles/Bundle.properties
  src/main/webapp/dataset-license-terms.xhtml
  src/main/webapp/dataset.xhtml
  src/main/webapp/dataverseuser.xhtml
  src/main/webapp/editFilesFragment.xhtml
  src/main/webapp/editdatafiles.xhtml
  src/main/webapp/file-download-button-fragment.xhtml
  src/main/webapp/file-edit-button-fragment.xhtml
  src/main/webapp/globus.xhtml
  src/main/webapp/manage-templates.xhtml
  src/main/webapp/resources/css/structure.css
  src/main/webapp/template.xhtml
  src/test/java/edu/harvard/iq/dataverse/util/FileUtilTest.java
Labels: hdc, 1

#8894 Release Notes related to HDC 1 and 3A/3B
  doc/release-notes/8611-DataCommons-related-notes.md
  doc/release-notes/8639-computational-workflow.md
  doc/release-notes/8759-add-computational-worflow-file-types.md
Labels: hdc, 3a, 3b, 1

#8949 8947 Update to Payara 5.2022.3
  conf/docker-aio/0prep_deps.sh
  conf/docker-aio/c8.dockerfile
  doc/release-notes/8947-payara-update.md
  doc/sphinx-guides/source/admin/troubleshooting.rst
  doc/sphinx-guides/source/developers/dev-environment.rst
  doc/sphinx-guides/source/installation/installation-main.rst
  doc/sphinx-guides/source/installation/prerequisites.rst
  downloads/download.sh
  modules/dataverse-parent/pom.xml
  scripts/vagrant/setup.sh
Labels: Feature: Code Infrastructure, Feature: Installer, Feature: Installation Guide, dependencies
