Repository IQSS/dataverse, pull requests merged in 2023-02, with the labels that each got.

#9089 IQSS/7349-4 creator updates in schema.org
  doc/release-notes/7349-4-schema.org-updates.md
  doc/sphinx-guides/source/admin/metadataexport.rst
  doc/sphinx-guides/source/installation/config.rst
  src/main/java/edu/harvard/iq/dataverse/DatasetVersion.java
  src/main/java/edu/harvard/iq/dataverse/export/openaire/OpenAireExportUtil.java
  src/main/java/edu/harvard/iq/dataverse/util/PersonOrOrgUtil.java
  src/test/java/edu/harvard/iq/dataverse/export/SchemaDotOrgExporterTest.java
  src/test/java/edu/harvard/iq/dataverse/util/PersonOrOrgUtilTest.java
Labels: DANS, QDR, Size: 10

#8958 IQSS/8957 JWT creation test for DRS Archiver
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/DRSSubmitToArchiveCommand.java
  src/test/java/edu/harvard/iq/dataverse/engine/command/impl/DRSSubmitToArchiveCommandTest.java
Labels: hdc, 3a, Size: 3

#9061 IQSS/9020- Fix for Update current version issue when a file is the dataset thumb
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/CuratePublishedDatasetVersionCommand.java
Labels: Size: 3

#9225 9224 - revert workflow metadata block in Solr schema
  conf/solr/8.11.1/schema.xml
  doc/release-notes/9224-remove-workflow-fields-from-index.md
  doc/sphinx-guides/source/user/appendix.rst
Labels: HERMES, hdc, 2, Size: 3

#9367 Text corrections #9365
  src/main/java/propertyFiles/Bundle.properties
  src/main/java/propertyFiles/astrophysics.properties
Labels: Feature: Metadata, Size: 3

#9254 Make productionPlace multiple, facetable, and enabled for Advanced Search #9253
  conf/solr/8.11.1/schema.xml
  doc/release-notes/9253-productionPlace.md
  doc/sphinx-guides/source/_static/api/ddi_dataset.xml
  scripts/api/data/metadatablocks/citation.tsv
  src/main/java/edu/harvard/iq/dataverse/api/imports/ImportDDIServiceBean.java
Labels: Feature: Metadata, Size: 3

#9366 Add initial support for .eln file format
  doc/release-notes/9363-eln.md
  src/main/java/propertyFiles/MimeTypeDetectionByFileExtension.properties
  src/main/java/propertyFiles/MimeTypeDisplay.properties
  src/main/java/propertyFiles/MimeTypeFacets.properties
Labels: Feature: File Upload & Handling, Size: 3

#9222 Update dataverse.xhtml to add "read more/read less" buttons for dataverse descriptions
  doc/release-notes/1249-collapse_dataverse_description.md
  src/main/java/propertyFiles/Bundle.properties
  src/main/webapp/dataset.xhtml
  src/main/webapp/dataverse.xhtml
  src/main/webapp/resources/js/dv_rebind_bootstrap_ui.js
Labels: Feature: Search/Browse, Size: 3

#8970 class field can be replaced by local variable
  src/main/java/edu/harvard/iq/dataverse/api/datadeposit/SWORDv2ContainerServlet.java
Labels: Type: Suggestion, Feature: Code Infrastructure, User Role: Hackathon Participant, Size: 3

#9303 9293 - New filter-based design for the API authentication mechanisms (1/2)
  src/main/java/edu/harvard/iq/dataverse/api/AbstractApiBean.java
  src/main/java/edu/harvard/iq/dataverse/api/ApiConfiguration.java
  src/main/java/edu/harvard/iq/dataverse/api/ApiConstants.java
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/main/java/edu/harvard/iq/dataverse/api/Files.java
  src/main/java/edu/harvard/iq/dataverse/api/auth/ApiKeyAuthMechanism.java
  src/main/java/edu/harvard/iq/dataverse/api/auth/AuthFilter.java
  src/main/java/edu/harvard/iq/dataverse/api/auth/AuthMechanism.java
  src/main/java/edu/harvard/iq/dataverse/api/auth/AuthRequired.java
  src/main/java/edu/harvard/iq/dataverse/api/auth/CompoundAuthMechanism.java
  src/main/java/edu/harvard/iq/dataverse/api/auth/SignedUrlAuthMechanism.java
  src/main/java/edu/harvard/iq/dataverse/api/auth/WorkflowKeyAuthMechanism.java
  src/main/java/edu/harvard/iq/dataverse/api/auth/WrappedAuthErrorResponse.java
  src/main/java/edu/harvard/iq/dataverse/datasetutility/AddReplaceFileHelper.java
  src/test/java/edu/harvard/iq/dataverse/api/FilesIT.java
  src/test/java/edu/harvard/iq/dataverse/api/HarvestingClientsIT.java
  src/test/java/edu/harvard/iq/dataverse/api/HarvestingServerIT.java
  src/test/java/edu/harvard/iq/dataverse/api/auth/ApiKeyAuthMechanismTest.java
  src/test/java/edu/harvard/iq/dataverse/api/auth/CompoundAuthMechanismTest.java
  src/test/java/edu/harvard/iq/dataverse/api/auth/SignedUrlAuthMechanismTest.java
  src/test/java/edu/harvard/iq/dataverse/api/auth/WorkflowKeyAuthMechanismTest.java
  src/test/java/edu/harvard/iq/dataverse/api/auth/doubles/ApiKeyContainerRequestTestFake.java
  src/test/java/edu/harvard/iq/dataverse/api/auth/doubles/ApiKeyUriInfoTestFake.java
  src/test/java/edu/harvard/iq/dataverse/api/auth/doubles/ContainerRequestTestFake.java
  src/test/java/edu/harvard/iq/dataverse/api/auth/doubles/SignedUrlContainerRequestTestFake.java
  src/test/java/edu/harvard/iq/dataverse/api/auth/doubles/SignedUrlUriInfoTestFake.java
  src/test/java/edu/harvard/iq/dataverse/api/auth/doubles/UriInfoTestFake.java
  src/test/java/edu/harvard/iq/dataverse/api/auth/doubles/WorkflowKeyContainerRequestTestFake.java
  src/test/java/edu/harvard/iq/dataverse/api/auth/doubles/WorkflowKeyUriInfoTestFake.java
Labels: Feature: API, User Role: API User, NIH OTA: 1.7.1 (reArchitecture), Size: 33

#9360 9293 - Apply filter-based auth for all API endpoints (2/2)
  src/main/java/edu/harvard/iq/dataverse/api/AbstractApiBean.java
  src/main/java/edu/harvard/iq/dataverse/api/Access.java
  src/main/java/edu/harvard/iq/dataverse/api/Admin.java
  src/main/java/edu/harvard/iq/dataverse/api/BatchImport.java
  src/main/java/edu/harvard/iq/dataverse/api/BuiltinUsers.java
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/main/java/edu/harvard/iq/dataverse/api/Dataverses.java
  src/main/java/edu/harvard/iq/dataverse/api/EditDDI.java
  src/main/java/edu/harvard/iq/dataverse/api/Files.java
  src/main/java/edu/harvard/iq/dataverse/api/HarvestingClients.java
  src/main/java/edu/harvard/iq/dataverse/api/HarvestingServer.java
  src/main/java/edu/harvard/iq/dataverse/api/Index.java
  src/main/java/edu/harvard/iq/dataverse/api/Info.java
  src/main/java/edu/harvard/iq/dataverse/api/Licenses.java
  src/main/java/edu/harvard/iq/dataverse/api/Notifications.java
  src/main/java/edu/harvard/iq/dataverse/api/Pids.java
  src/main/java/edu/harvard/iq/dataverse/api/Prov.java
  src/main/java/edu/harvard/iq/dataverse/api/Roles.java
  src/main/java/edu/harvard/iq/dataverse/api/Search.java
  src/main/java/edu/harvard/iq/dataverse/api/Users.java
  src/main/java/edu/harvard/iq/dataverse/api/batchjob/FileRecordJobResource.java
  src/main/java/edu/harvard/iq/dataverse/mydata/DataRetrieverAPI.java
  src/test/java/edu/harvard/iq/dataverse/api/AdminIT.java
  src/test/java/edu/harvard/iq/dataverse/api/BuiltinUsersIT.java
  src/test/java/edu/harvard/iq/dataverse/api/DataRetrieverApiIT.java
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
  src/test/java/edu/harvard/iq/dataverse/api/DataversesTest.java
  src/test/java/edu/harvard/iq/dataverse/api/DeactivateUsersIT.java
  src/test/java/edu/harvard/iq/dataverse/api/SearchIT.java
  src/test/java/edu/harvard/iq/dataverse/api/SignedUrlAuthMechanismIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: Feature: API, User Role: API User, NIH OTA: 1.7.1 (reArchitecture), Size: 10
