Repository IQSS/dataverse, pull requests merged in 2023-12, with the labels that each got.

#10159 Fix Datasets API getVersionFiles endpoint content type filtering (JPA Criteria)
  src/main/java/edu/harvard/iq/dataverse/DatasetVersionFilesServiceBean.java
Labels: Size: 3

#10004 fix S3 provider priorities
  src/main/java/edu/harvard/iq/dataverse/dataaccess/S3AccessIO.java
Labels: Size: 3

#10122 make BagIT source organization info (name, address, email) configurable
  doc/release-notes/8760-bagit.md
  doc/release-notes/8760-download-tmp-file.md
  doc/sphinx-guides/source/api/changelog.rst
  doc/sphinx-guides/source/api/native-api.rst
  doc/sphinx-guides/source/installation/config.rst
  src/main/java/edu/harvard/iq/dataverse/api/AbstractApiBean.java
  src/main/java/edu/harvard/iq/dataverse/api/Admin.java
  src/main/java/edu/harvard/iq/dataverse/settings/JvmSettings.java
  src/main/java/edu/harvard/iq/dataverse/util/bagit/BagGenerator.java
  src/main/java/propertyFiles/Bundle.properties
  src/test/java/edu/harvard/iq/dataverse/api/AdminIT.java
  src/test/java/edu/harvard/iq/dataverse/api/BagIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: Size: 3

#9669 IQSS/9506 thumbnail failure tracking and other performance improvements
  doc/sphinx-guides/source/api/changelog.rst
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/DataFileServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/DatasetPage.java
  src/main/java/edu/harvard/iq/dataverse/DatasetVersionServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/DataverseServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/DvObject.java
  src/main/java/edu/harvard/iq/dataverse/ThumbnailServiceWrapper.java
  src/main/java/edu/harvard/iq/dataverse/api/Admin.java
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/main/java/edu/harvard/iq/dataverse/dataaccess/ImageThumbConverter.java
  src/main/java/edu/harvard/iq/dataverse/dataset/DatasetUtil.java
  src/main/java/edu/harvard/iq/dataverse/search/SearchIncludeFragment.java
  src/main/resources/db/migration/V6.0.0.6__9506-track-thumb-failures.sql
  src/main/webapp/editFilesFragment.xhtml
  src/main/webapp/file-info-fragment.xhtml
  src/test/java/edu/harvard/iq/dataverse/api/AdminIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: Feature: Performance & Stability, GDCC: QDR, Size: 33, GDCC: Borealis

#10109 JSON Schema creator and validator
  doc/release-notes/9464-json-validation.md
  doc/sphinx-guides/source/_static/api/dataset-schema.json
  doc/sphinx-guides/source/api/changelog.rst
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/DataverseFieldTypeInputLevel.java
  src/main/java/edu/harvard/iq/dataverse/DataverseFieldTypeInputLevelServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/DataverseServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/api/Dataverses.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/GetDatasetSchemaCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/ValidateDatasetJsonCommand.java
  src/main/java/edu/harvard/iq/dataverse/metrics/MetricsServiceBean.java
  src/main/java/propertyFiles/Bundle.properties
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: Size: 10

#10044 add S3 tests, LocalStack, MinIO
  conf/localstack/buckets.sh
  doc/release-notes/6783-s3-tests.md
  doc/sphinx-guides/source/admin/dataverses-datasets.rst
  doc/sphinx-guides/source/developers/s3-direct-upload-api.rst
  doc/sphinx-guides/source/developers/testing.rst
  docker-compose-dev.yml
  pom.xml
  src/test/java/edu/harvard/iq/dataverse/api/S3AccessDirectIT.java
  src/test/java/edu/harvard/iq/dataverse/api/S3AccessIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
  src/test/java/edu/harvard/iq/dataverse/dataaccess/S3AccessIOLocalstackIT.java
  tests/integration-tests.txt
Labels: Component: Containers, Size: 3

#10174 8549 collection quotas
  src/main/java/edu/harvard/iq/dataverse/AuxiliaryFileServiceBean.java
Labels: Size: 0.5

#10132 add performance section to dev guide
  doc/sphinx-guides/source/admin/monitoring.rst
  doc/sphinx-guides/source/developers/index.rst
  doc/sphinx-guides/source/developers/performance.rst
  doc/sphinx-guides/source/developers/testing.rst
  doc/sphinx-guides/source/developers/tips.rst
  doc/sphinx-guides/source/installation/advanced.rst
Labels: Size: 3

#10166 adding 6.1 release notes and removing .md files
  doc/release-notes/10001-datasets-files-api-user-permissions.md
  doc/release-notes/10060-api-changelog.md
  doc/release-notes/10093-signedUrl_improvements.md
  doc/release-notes/10104-dataset-citation-deaccessioned.md
  doc/release-notes/10162-globus-support.md
  doc/release-notes/6.1-release-notes.md
  doc/release-notes/6783-s3-tests.md
  doc/release-notes/8549-collection-quotas.md
  doc/release-notes/8760-bagit.md
  doc/release-notes/8760-download-tmp-file.md
  doc/release-notes/9002_allow_direct_upload_setting.md
  doc/release-notes/9268-8349-oidc-improvements.md
  doc/release-notes/9412-markdown-previewer.md
  doc/release-notes/9428-alternative-title.md
  doc/release-notes/9464-json-validation.md
  doc/release-notes/9547-validation-for-geospatial-metadata.md
  doc/release-notes/9589-ds-configure-tool.md
  doc/release-notes/9590-intellij-redeploy.md
  doc/release-notes/9599-guestbook-at-request.md
  doc/release-notes/9635-solr-improvements.md
  doc/release-notes/9692-files-api-extension.md
  doc/release-notes/9714-files-api-extension-filters.md
  doc/release-notes/9763-versions-api-improvements.md
  doc/release-notes/9785-files-api-extension-search-text.md
  doc/release-notes/9834-files-api-extension-counts.md
  doc/release-notes/9851-datafile-payload-extension-new-file-access-endpoints.md
  doc/release-notes/9852-files-api-extension-deaccession.md
  doc/release-notes/9859-ORE and Bag updates.md
  doc/release-notes/9880-info-api-zip-limit-embargo.md
  doc/release-notes/9907-files-api-counts-with-criteria.md
  doc/release-notes/9955-Signposting-updates.md
  doc/release-notes/9958-dataset-api-downloadsize-ignore-tabular-size.md
  doc/release-notes/9972-files-api-filter-by-tabular-tags.md
  doc/release-notes/9995-files-api-downloadsize-with-criteria-and-deaccessioned-support.md
  doc/sphinx-guides/source/api/changelog.rst
Labels: Size: 10

#10165 Bump version to 6.1
  doc/sphinx-guides/source/conf.py
  doc/sphinx-guides/source/versions.rst
  modules/dataverse-parent/pom.xml
Labels: Size: 0.5

#10185 10168 fix api error response for getDatasetVersionArchivalStatus
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
Labels: Size: 3

#10180 update "making releases" after 6.1
  doc/sphinx-guides/source/developers/making-releases.rst
Labels: Size: 0.5

#10167 Add API endpoint to know if a user can download at least one file in a Dataset version
  doc/release-notes/10155-datasets-can-download-at-least-one-file.md
  doc/sphinx-guides/source/api/native-api.rst
  doc/sphinx-guides/source/installation/shibboleth.rst
  docker-compose-dev.yml
  src/main/java/edu/harvard/iq/dataverse/PermissionServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: Size: 10, SPA
