Repository IQSS/dataverse, pull requests merged in 2023-01, with the labels that each got.

#9096 IQSS/9095-dvwebloader integration
  doc/release-notes/9096-folder-upload.md
  doc/sphinx-guides/source/developers/big-data-support.rst
  doc/sphinx-guides/source/installation/config.rst
  doc/sphinx-guides/source/user/dataset-management.rst
  src/main/java/edu/harvard/iq/dataverse/DatasetPage.java
  src/main/java/edu/harvard/iq/dataverse/EditDatafilesPage.java
  src/main/java/edu/harvard/iq/dataverse/SettingsWrapper.java
  src/main/java/edu/harvard/iq/dataverse/authorization/AuthenticationServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/settings/SettingsServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/util/SystemConfig.java
  src/main/java/edu/harvard/iq/dataverse/util/WebloaderUtil.java
  src/main/java/propertyFiles/Bundle.properties
  src/main/webapp/dataset.xhtml
  src/main/webapp/editFilesFragment.xhtml
  src/main/webapp/editdatafiles.xhtml
  src/main/webapp/resources/css/structure.css
Labels: DataverseNO, Size: 10

#9234 9228 - add OIDC development setup for OIDC login feature testing
  conf/keycloak/docker-compose.yml
  conf/keycloak/oidc-keycloak-auth-provider.json
  conf/keycloak/oidc-realm.json
  conf/keycloak/rm-keycloak.sh
  conf/keycloak/run-keycloak.sh
  doc/sphinx-guides/source/developers/remote-users.rst
Labels: Feature: Account & User Info, NIH OTA: 1.7.1 (reArchitecture), Size: 3

#9018 GDCC/9005 replace files api call
  doc/release-notes/9005-replaceFiles-api-call
  doc/sphinx-guides/source/api/native-api.rst
  doc/sphinx-guides/source/developers/s3-direct-upload-api.rst
  src/main/java/edu/harvard/iq/dataverse/DataFileServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/EditDatafilesPage.java
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/main/java/edu/harvard/iq/dataverse/api/Files.java
  src/main/java/edu/harvard/iq/dataverse/datasetutility/AddReplaceFileHelper.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonUtil.java
  src/main/webapp/editFilesFragment.xhtml
Labels: DANS, bk2211, Size: 33

#9129 IQSS/9126- Fix workflow token access
  src/main/java/edu/harvard/iq/dataverse/api/Access.java
Labels: DANS, Size: 10

#8827 7000 mpconfig files basic
  doc/sphinx-guides/source/api/native-api.rst
  doc/sphinx-guides/source/installation/config.rst
  src/main/java/edu/harvard/iq/dataverse/Dataset.java
  src/main/java/edu/harvard/iq/dataverse/EditDatafilesPage.java
  src/main/java/edu/harvard/iq/dataverse/api/datadeposit/SwordConfigurationImpl.java
  src/main/java/edu/harvard/iq/dataverse/batch/jobs/importer/filesystem/FileRecordJobListener.java
  src/main/java/edu/harvard/iq/dataverse/batch/jobs/importer/filesystem/FileRecordReader.java
  src/main/java/edu/harvard/iq/dataverse/batch/util/LoggingUtil.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/GoogleCloudSubmitToArchiveCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/ImportFromFileSystemCommand.java
  src/main/java/edu/harvard/iq/dataverse/settings/JvmSettings.java
  src/main/java/edu/harvard/iq/dataverse/util/FileUtil.java
  src/main/java/edu/harvard/iq/dataverse/util/SystemConfig.java
  src/main/resources/META-INF/microprofile-config.properties
Labels: Feature: File Upload & Handling, Feature: Code Infrastructure, Feature: Installation Guide, User Role: Sysadmin, Containers & Cloud, Size: 3

#9239 extract metadata (NcML XML) from NetCDF/HDF5 files, new "requirements" option for external tools
  doc/release-notes/9153-extract-metadata.md
  doc/sphinx-guides/source/_static/admin/dataverse-external-tools.tsv
  doc/sphinx-guides/source/_static/installation/files/root/external-tools/auxFileTool.json
  doc/sphinx-guides/source/api/external-tools.rst
  doc/sphinx-guides/source/api/native-api.rst
  doc/sphinx-guides/source/user/dataset-management.rst
  src/main/java/edu/harvard/iq/dataverse/AuxiliaryFile.java
  src/main/java/edu/harvard/iq/dataverse/AuxiliaryFileServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/DatasetPage.java
  src/main/java/edu/harvard/iq/dataverse/FilePage.java
  src/main/java/edu/harvard/iq/dataverse/api/Files.java
  src/main/java/edu/harvard/iq/dataverse/api/TestApi.java
  src/main/java/edu/harvard/iq/dataverse/externaltools/ExternalTool.java
  src/main/java/edu/harvard/iq/dataverse/externaltools/ExternalToolServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/ingest/IngestServiceBean.java
  src/main/java/propertyFiles/Bundle.properties
  src/main/resources/db/migration/V5.12.1.1__8671-sorting_licenses.sql
  src/main/resources/db/migration/V5.12.1.2__7715-signed-urls-for-tools.sql
  src/main/resources/db/migration/V5.12.1.3__8840-improve-guestbook-estimates.sql
  src/main/resources/db/migration/V5.12.1.4__9153-extract-metadata.sql
  src/test/java/edu/harvard/iq/dataverse/api/ExternalToolsIT.java
  src/test/java/edu/harvard/iq/dataverse/api/NetcdfIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
  src/test/java/edu/harvard/iq/dataverse/externaltools/ExternalToolServiceBeanTest.java
  tests/integration-tests.txt
Labels: Size: 10

#9105 Add quotes around CVoc term URIs on advanced search page
  src/main/java/edu/harvard/iq/dataverse/search/AdvancedSearchPage.java
  src/main/java/edu/harvard/iq/dataverse/search/SearchUtil.java
Labels: DANS, Size: 10

#9122 IQSS/9121 Fix for search display with ext. CVoc
  src/main/webapp/search-include-fragment.xhtml
Labels: DANS, Size: 10

#8915 7980 enhanced dsd
  doc/release-notes/7980-enhanced-dsd.md
  doc/sphinx-guides/source/installation/config.rst
  src/main/java/edu/harvard/iq/dataverse/util/DataSourceProducer.java
Labels: User Role: Sysadmin, Size: 3

#9269 8339 file data api
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/DataFile.java
  src/main/java/edu/harvard/iq/dataverse/api/AbstractApiBean.java
  src/main/java/edu/harvard/iq/dataverse/api/Files.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java
  src/main/java/propertyFiles/Bundle.properties
  src/test/java/edu/harvard/iq/dataverse/api/FilesIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: Size: 10

#9132 Dataset files cleanup
  doc/release-notes/9130-cleanup-storage.md
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/main/java/edu/harvard/iq/dataverse/dataaccess/FileAccessIO.java
  src/main/java/edu/harvard/iq/dataverse/dataaccess/InputStreamIO.java
  src/main/java/edu/harvard/iq/dataverse/dataaccess/RemoteOverlayAccessIO.java
  src/main/java/edu/harvard/iq/dataverse/dataaccess/S3AccessIO.java
  src/main/java/edu/harvard/iq/dataverse/dataaccess/StorageIO.java
  src/main/java/edu/harvard/iq/dataverse/dataaccess/SwiftAccessIO.java
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsTest.java
Labels: Size: SprintTail

#9101 IQSS/7349-5 - Use brand name for catalog
  src/main/java/edu/harvard/iq/dataverse/DatasetVersion.java
Labels: QDR, Size: 3

#9193 IQSS/9189-fix non-Globus properties
  src/main/java/propertyFiles/Bundle.properties
Labels: Size: 3

#6183 Fix at 'Show the dataset whose id is passed' section #6083
  doc/sphinx-guides/source/api/native-api.rst
Labels: Type: Suggestion, Feature: API Guide, User Role: API User, Size: 3

#9249 DOCS: add link to development documentation build
  doc/sphinx-guides/source/developers/documentation.rst
  doc/sphinx-guides/source/index.rst
  doc/sphinx-guides/source/versions.rst
Labels: Feature: User Guide, Size: 3

#9086 Iqss/7349 2 improve related pub citation entry
  doc/release-notes/7349-2-schema.org-updates.md
  src/main/java/edu/harvard/iq/dataverse/DatasetVersion.java
  src/test/java/edu/harvard/iq/dataverse/export/SchemaDotOrgExporterTest.java
Labels: QDR, Size: 3

#9087 IQSS/7349-3 file updates for schema.org
  doc/release-notes/7349-3-schema.org-updates.md
  src/main/java/edu/harvard/iq/dataverse/DatasetVersion.java
  src/test/java/edu/harvard/iq/dataverse/export/SchemaDotOrgExporterTest.java
Labels: QDR, Size: 3

#9085 Iqss/7349 1 truncate description
  doc/release-notes/7349-1-schema.org-updates.md
  src/main/java/edu/harvard/iq/dataverse/DatasetVersion.java
  src/test/java/edu/harvard/iq/dataverse/export/SchemaDotOrgExporterTest.java
  src/test/resources/json/dataset-long-description.json
Labels: QDR, Size: 3

#9316 Fix for the broken "earliest date" (#9309)
  src/main/java/edu/harvard/iq/dataverse/harvest/server/OAIRecordServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/harvest/server/web/servlet/OAIServlet.java
Labels: Size: 10

#9212 #9211 fix render logic display with TOA OR restricted files
  src/main/webapp/dataset-license-terms.xhtml
Labels: Size: 3

#9017 GDCC/9016-handle no file PID case in metrics
  doc/sphinx-guides/source/api/metrics.rst
  src/main/java/edu/harvard/iq/dataverse/metrics/MetricsServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/metrics/MetricsUtil.java
  src/main/java/edu/harvard/iq/dataverse/util/FileUtil.java
Labels: JHU, Size: 10
