Repository IQSS/dataverse, pull requests merged in 2023-07, with the labels that each got.

#9695 Update for #9677
  src/main/java/edu/harvard/iq/dataverse/export/InternalExportDataProvider.java
  src/main/java/edu/harvard/iq/dataverse/export/ddi/DdiExportUtil.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java
Labels: Size: 3

#9596 add MyData API to dataverse documentaion
  doc/release-notes/5042-add-mydata-doc-api.md
  doc/sphinx-guides/source/api/native-api.rst
Labels: Feature: API Guide, Size: 3, Waiting

#9545 IQSS/9544 - Migrate API fixes
  src/main/java/edu/harvard/iq/dataverse/AbstractGlobalIdServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/DOIDataCiteServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/DOIEZIdServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/DOIServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/DataFileServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/DvObjectServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/GlobalIdServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/HandlenetServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/AbstractDatasetCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/DeleteDataFileCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/DestroyDatasetCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/ImportDatasetCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/RegisterDvObjectCommand.java
  src/main/java/edu/harvard/iq/dataverse/pidproviders/FakePidProviderServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/pidproviders/PermaLinkPidProviderServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/pidproviders/UnmanagedDOIServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/pidproviders/UnmanagedHandlenetServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JSONLDUtil.java
Labels: DANS, Size: 10

#9668 9667 - displayFormat added to DatasetFieldType API payload
  doc/release-notes/9667-metadatablocks-api-extension.md
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java
Labels: Size: 3

#9611 fix S3 direct upload NPE and NetCDF/HDF5 and keep geospatial metadata extraction
  doc/release-notes/9331-extract-bounding-box.md
  doc/sphinx-guides/source/developers/big-data-support.rst
  doc/sphinx-guides/source/installation/config.rst
  doc/sphinx-guides/source/user/dataset-management.rst
  src/main/java/edu/harvard/iq/dataverse/ingest/IngestServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/ingest/metadataextraction/impl/plugins/netcdf/NetcdfFileMetadataExtractor.java
  src/main/java/edu/harvard/iq/dataverse/settings/JvmSettings.java
  src/main/java/edu/harvard/iq/dataverse/util/FileUtil.java
Labels: Size: 3

#9388 IQSS/9387 - Support protected system metadata
  doc/release-notes/9387-system_metadata_blocks.md
  doc/sphinx-guides/source/admin/metadatacustomization.rst
  doc/sphinx-guides/source/developers/dataset-semantic-metadata-api.rst
  src/main/java/edu/harvard/iq/dataverse/DatasetPage.java
  src/main/java/edu/harvard/iq/dataverse/DatasetVersionDifference.java
  src/main/java/edu/harvard/iq/dataverse/DatasetVersionUI.java
  src/main/java/edu/harvard/iq/dataverse/ManageTemplatesPage.java
  src/main/java/edu/harvard/iq/dataverse/MetadataBlockServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/SettingsWrapper.java
  src/main/java/edu/harvard/iq/dataverse/Template.java
  src/main/java/edu/harvard/iq/dataverse/TemplatePage.java
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/main/java/edu/harvard/iq/dataverse/api/Dataverses.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/DataverseRequest.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/AbstractCreateDatasetCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/AbstractDatasetCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/CreateDatasetVersionCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/CreateHarvestedDatasetCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/CreateNewDatasetCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/UpdateDatasetVersionCommand.java
  src/main/java/edu/harvard/iq/dataverse/settings/JvmSettings.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JSONLDUtil.java
  src/test/java/edu/harvard/iq/dataverse/mocks/MocksFactory.java
Labels: DANS, Size: 33

#9652 better message when picking a new password #9326
  src/main/java/propertyFiles/Bundle.properties
Labels: Size: 3

#9569 Fix #9346 clear single metrics api
  src/main/java/edu/harvard/iq/dataverse/api/Admin.java
  src/test/java/edu/harvard/iq/dataverse/api/MetricsIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: QDR, Size: 3

#9644 More QDR a11y fixes
  src/main/java/propertyFiles/Bundle.properties
  src/main/webapp/dataset-license-terms.xhtml
  src/main/webapp/file-edit-popup-fragment.xhtml
  src/main/webapp/filesFragment.xhtml
  src/main/webapp/resources/css/structure.css
  src/main/webapp/search-include-fragment.xhtml
Labels: QDR, Size: 3

#9643 IQSS/9185-improve parsing for given/family name
  src/main/java/edu/harvard/iq/dataverse/util/PersonOrOrgUtil.java
  src/test/java/edu/harvard/iq/dataverse/export/OpenAireExportUtilTest.java
  src/test/java/edu/harvard/iq/dataverse/util/PersonOrOrgUtilTest.java
Labels: QDR, Size: 3

#9698 DANS - Add embargo info to ORE map (and therefore bag export)
  doc/release-notes/9698-embargo-info-in-ORE.md
  src/main/java/edu/harvard/iq/dataverse/util/bagit/OREMap.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonLDTerm.java
Labels: DANS, Size: 3

#9556 IQSS/9555 update list curation states api call
  doc/sphinx-guides/source/api/curation-labels.rst
  src/main/java/edu/harvard/iq/dataverse/DatasetServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
Labels: QDR, DataverseNO, Size: 3

#9641 IQSS/9640-citationDate bug
  src/main/webapp/metadataFragment.xhtml
Labels: Size: 3

#9699 update configbaker to included recent version of ed
  modules/container-configbaker/Dockerfile
Labels: Containers & Cloud, Size: 3

#9645 QDR - fix for full-text indexing when one file fails
  src/main/java/edu/harvard/iq/dataverse/search/IndexServiceBean.java
Labels: QDR, Size: 3

#9706 DANS - 9707/Second fix for #9677
  src/main/java/edu/harvard/iq/dataverse/export/ddi/DdiExportUtil.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
Labels: Size: 3

#9712 MDC Legacy counts: Remove duplicate elements from bad merge
  src/main/webapp/file.xhtml
Labels: Size: 3

#9710 api-session-auth: stop linking to closed issue
  doc/sphinx-guides/source/installation/config.rst
Labels: Size: 3

#9715 5.14 performance improvements
  src/main/java/edu/harvard/iq/dataverse/DatasetPage.java
  src/main/webapp/dataset.xhtml
Labels: Size: 3

#9734 Document MDCStartDate
  doc/sphinx-guides/source/admin/make-data-count.rst
  doc/sphinx-guides/source/installation/config.rst
Labels: Size: 3

#9721 IQSS/8889 - second try to limit file pids management
  doc/release-notes/8889-2-filepids-in-collections-changes.md
  doc/sphinx-guides/source/admin/dataverses-datasets.rst
  doc/sphinx-guides/source/api/native-api.rst
  doc/sphinx-guides/source/installation/config.rst
  src/main/java/edu/harvard/iq/dataverse/api/Admin.java
  src/main/java/edu/harvard/iq/dataverse/api/Dataverses.java
  src/main/java/edu/harvard/iq/dataverse/batch/jobs/importer/filesystem/FileRecordWriter.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/CreateDataverseCommand.java
  src/main/java/edu/harvard/iq/dataverse/settings/SettingsServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/util/SystemConfig.java
  src/test/java/edu/harvard/iq/dataverse/api/FilesIT.java
Labels: Size: 10
