Repository IQSS/dataverse, pull requests merged in 2023-11, with the labels that each got.

#9068 Update HTTP URL to HTTPS URL
  README.md
  doc/sphinx-guides/source/_static/navbarscroll.js
  doc/sphinx-guides/source/_templates/navbar.html
  doc/sphinx-guides/source/admin/monitoring.rst
  doc/sphinx-guides/source/api/client-libraries.rst
  doc/sphinx-guides/source/api/external-tools.rst
  doc/sphinx-guides/source/api/getting-started.rst
  doc/sphinx-guides/source/api/intro.rst
  doc/sphinx-guides/source/api/native-api.rst
  doc/sphinx-guides/source/api/sword.rst
  doc/sphinx-guides/source/conf.py
  doc/sphinx-guides/source/developers/classic-dev-env.rst
  doc/sphinx-guides/source/developers/documentation.rst
  doc/sphinx-guides/source/developers/intro.rst
  doc/sphinx-guides/source/developers/testing.rst
  doc/sphinx-guides/source/developers/tools.rst
  doc/sphinx-guides/source/developers/unf/index.rst
  doc/sphinx-guides/source/developers/unf/unf-v3.rst
  doc/sphinx-guides/source/developers/unf/unf-v6.rst
  doc/sphinx-guides/source/developers/version-control.rst
  doc/sphinx-guides/source/index.rst
  doc/sphinx-guides/source/installation/config.rst
  doc/sphinx-guides/source/installation/installation-main.rst
  doc/sphinx-guides/source/installation/intro.rst
  doc/sphinx-guides/source/installation/oauth2.rst
  doc/sphinx-guides/source/installation/oidc.rst
  doc/sphinx-guides/source/installation/prerequisites.rst
  doc/sphinx-guides/source/installation/shibboleth.rst
  doc/sphinx-guides/source/style/foundations.rst
  doc/sphinx-guides/source/style/patterns.rst
  doc/sphinx-guides/source/user/account.rst
  doc/sphinx-guides/source/user/appendix.rst
  doc/sphinx-guides/source/user/dataset-management.rst
  doc/sphinx-guides/source/user/tabulardataingest/ingestprocess.rst
Labels: Size: 0.5

#10026 Replace "identifer" with "identifier" in docs and code
  doc/sphinx-guides/source/developers/s3-direct-upload-api.rst
  doc/sphinx-guides/source/user/dataset-management.rst
  doc/sphinx-guides/source/user/find-use-data.rst
  src/main/java/edu/harvard/iq/dataverse/DatasetVersionServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/Shib.java
  src/main/java/edu/harvard/iq/dataverse/api/datadeposit/CollectionListManagerImpl.java
  src/main/java/edu/harvard/iq/dataverse/api/datadeposit/MediaResourceManagerImpl.java
  src/main/java/edu/harvard/iq/dataverse/authorization/AuthenticationServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/authorization/UserIdentifier.java
  src/main/java/edu/harvard/iq/dataverse/authorization/providers/shib/ShibUtil.java
  src/main/java/edu/harvard/iq/dataverse/batch/jobs/importer/filesystem/FileRecordJobListener.java
  src/main/java/edu/harvard/iq/dataverse/batch/jobs/importer/filesystem/FileRecordReader.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/ImportFromFileSystemCommand.java
  src/test/java/edu/harvard/iq/dataverse/api/AdminIT.java
  src/test/java/edu/harvard/iq/dataverse/authorization/providers/shib/ShibUtilTest.java
Labels: Size: 3

#10058 IQSS/10057 ddi export bugs
  src/main/java/edu/harvard/iq/dataverse/export/ddi/DdiExportUtil.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java
Labels: GDCC: QDR, Size: 3, GDCC:UNC

#10102 Docs for fast redeploy with IntelliJ IDEA Ultimate and Payara Platform Tools
  doc/release-notes/9590-intellij-redeploy.md
  doc/sphinx-guides/source/container/dev-usage.rst
  modules/nginx/img.png
Labels: Component: Containers

#10039 document preserving access logging in 6.0 upgrade steps
  doc/release-notes/6.0-release-notes.md
Labels: Size: 0.5

#10113 10112-ProvIT-enable-fix
  src/test/java/edu/harvard/iq/dataverse/api/ProvIT.java
  tests/integration-tests.txt
Labels: Type: Bug, Size: 0.5

#10096 IQSS/10095-download estimate bug fix
  src/main/resources/db/migration/V6.0.0.3__10095-guestbook-at-request2.sql
Labels: Size: 3

#10115 Single retry when datafile checksum validation fails
  src/main/java/edu/harvard/iq/dataverse/util/FileUtil.java
Labels: Size: 3, KULeuven

#10127 Add condition for 401 on invalid key and changelog on API Guide
  doc/release-notes/10060-api-changelog.md
  doc/sphinx-guides/source/api/changelog.rst
  doc/sphinx-guides/source/api/index.rst
  src/test/java/edu/harvard/iq/dataverse/api/AccessIT.java
Labels: Type: Feature, Type: Bug, Size: 3

#10121 Support get dataset citation for deaccessioned datasets via API
  doc/release-notes/10104-dataset-citation-deaccessioned.md
  doc/sphinx-guides/source/api/changelog.rst
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: Size: 10, SPA

#10098 signed URLs with private url users, autogenerate API token
  doc/release-notes/10093-signedUrl_improvements.md
  doc/sphinx-guides/source/api/auth.rst
  doc/sphinx-guides/source/api/external-tools.rst
  src/main/java/edu/harvard/iq/dataverse/DatasetPage.java
  src/main/java/edu/harvard/iq/dataverse/FileDownloadServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/FilePage.java
  src/main/java/edu/harvard/iq/dataverse/RoleAssigneeServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/main/java/edu/harvard/iq/dataverse/api/Files.java
  src/main/java/edu/harvard/iq/dataverse/api/auth/SignedUrlAuthMechanism.java
  src/main/java/edu/harvard/iq/dataverse/authorization/AuthenticationServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/authorization/users/PrivateUrlUser.java
  src/main/java/edu/harvard/iq/dataverse/externaltools/ExternalToolHandler.java
  src/main/resources/db/migration/V6.0.0.4__10093-privateurluser_id_update.sql
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
  src/test/java/edu/harvard/iq/dataverse/privateurl/PrivateUrlUtilTest.java
  src/test/java/edu/harvard/iq/dataverse/util/json/JsonPrinterTest.java
Labels: Size: 10

#10050 9635 solr improvements
  conf/solr/9.3.0/solrconfig.xml
  doc/release-notes/9635-solr-improvements.md
  doc/sphinx-guides/source/installation/config.rst
  doc/sphinx-guides/source/installation/prerequisites.rst
  src/main/java/edu/harvard/iq/dataverse/DatasetPage.java
  src/main/java/edu/harvard/iq/dataverse/GuestbookPage.java
  src/main/java/edu/harvard/iq/dataverse/api/Search.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/UpdateDataverseCommand.java
  src/main/java/edu/harvard/iq/dataverse/mydata/DataRetrieverAPI.java
  src/main/java/edu/harvard/iq/dataverse/search/IndexServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/search/SearchIncludeFragment.java
  src/main/java/edu/harvard/iq/dataverse/search/SearchServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/search/SolrQueryResponse.java
  src/main/java/edu/harvard/iq/dataverse/settings/SettingsServiceBean.java
  src/main/java/propertyFiles/Bundle.properties
  src/main/webapp/search-include-fragment.xhtml
  src/main/webapp/search-include-pager.xhtml
Labels: Size: 33

#10142 Add validation for entered coordinate values in Geospatial metadata
  doc/release-notes/9547-validation-for-geospatial-metadata.md
  scripts/api/data/metadatablocks/geospatial.tsv
  src/main/java/edu/harvard/iq/dataverse/DatasetFieldValueValidator.java
  src/main/java/edu/harvard/iq/dataverse/search/IndexServiceBean.java
  src/main/java/propertyFiles/Bundle.properties
  src/main/java/propertyFiles/geospatial.properties
  src/test/java/edu/harvard/iq/dataverse/DatasetFieldValueValidatorTest.java
  src/test/java/edu/harvard/iq/dataverse/search/IndexServiceBeanTest.java
Labels: Size: 33
