Repository IQSS/dataverse, pull requests merged in 2023-04, with the labels that each got.

#8828 7000 mpconfig pid doi hdl
  doc/release-notes/7000-pidproviders.md
  doc/sphinx-guides/source/admin/make-data-count.rst
  doc/sphinx-guides/source/api/native-api.rst
  doc/sphinx-guides/source/container/app-image.rst
  doc/sphinx-guides/source/installation/config.rst
  scripts/installer/as-setup.sh
  scripts/installer/install.py
  src/main/docker/scripts/init_2_configure.sh
  src/main/java/edu/harvard/iq/dataverse/DOIDataCiteRegisterService.java
  src/main/java/edu/harvard/iq/dataverse/DOIDataCiteServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/DOIEZIdServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/HandlenetServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/api/MakeDataCountApi.java
  src/main/java/edu/harvard/iq/dataverse/api/Pids.java
  src/main/java/edu/harvard/iq/dataverse/pidproviders/FakePidProviderServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/pidproviders/PermaLinkPidProviderServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/pidproviders/UnmanagedDOIServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/pidproviders/UnmanagedHandlenetServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/settings/JvmSettings.java
  src/main/java/edu/harvard/iq/dataverse/settings/source/AliasConfigSource.java
  src/main/java/edu/harvard/iq/dataverse/util/SystemConfig.java
  src/main/resources/META-INF/microprofile-config.properties
  src/test/java/edu/harvard/iq/dataverse/settings/JvmSettingsTest.java
  src/test/resources/META-INF/microprofile-config.properties
Labels: Feature: Code Infrastructure, Feature: Installer, Feature: DOI & Handle, Feature: Installation Guide, User Role: Sysadmin, Containers & Cloud, Size: 10, bklog: NeedsDiscussion, D: DataverseInDocker

#9206 IQSS/9205-Add role-based provider for S3
  doc/sphinx-guides/source/developers/deployment.rst
  doc/sphinx-guides/source/installation/config.rst
  src/main/java/edu/harvard/iq/dataverse/dataaccess/S3AccessIO.java
Labels: Size: 3

#9184 Iqss/9183 terms of access validation fix
  src/main/webapp/dataset.xhtml
Labels: Type: Suggestion, Feature: Code Infrastructure, Size: 3

#9012 rename role.editor to role.contributor
  src/main/java/propertyFiles/BuiltInRoles.properties
Labels: Size: 3

#9195 IQSS/9194-fix curate command validation
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/CuratePublishedDatasetVersionCommand.java
Labels: QDR, Size: 10

#9402 Iqss/9150 handle fundreg reqs for ext cvv
  doc/release-notes/9150-improved-external-vocab-supprt.md
  src/main/java/edu/harvard/iq/dataverse/DatasetFieldServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/DatasetPage.java
  src/main/java/edu/harvard/iq/dataverse/SettingsWrapper.java
  src/main/java/edu/harvard/iq/dataverse/pidproviders/PermaLinkPidProviderServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/search/IndexServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/util/bagit/OREMap.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java
  src/main/webapp/dataverse_template.xhtml
  src/main/webapp/metadataFragment.xhtml
  src/main/webapp/resources/css/structure.css
  src/main/webapp/search-include-fragment.xhtml
Labels: NIH OTA: 1.2.1, Size: 10, D: 5 Core PIDs, pm.GREI-d-1.2.1

#9538 Bugfix for /api/metrics/downloads/toMonth/{yyyymm} endpoint: add parenthesis to condition SQL Query
  src/main/java/edu/harvard/iq/dataverse/metrics/MetricsServiceBean.java
Labels: Size: 3

#9503 6723 unzip optimizations
  src/main/java/edu/harvard/iq/dataverse/ingest/IngestableDataChecker.java
  src/main/java/edu/harvard/iq/dataverse/util/FileUtil.java
Labels: Size: 3

#9257 8092 timestamp of data access request
  doc/release-notes/8092-timestamp-of-data-access-request.md
  src/main/java/edu/harvard/iq/dataverse/DataFile.java
  src/main/java/edu/harvard/iq/dataverse/DataFileServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/DatasetPage.java
  src/main/java/edu/harvard/iq/dataverse/FileAccessRequest.java
  src/main/java/edu/harvard/iq/dataverse/FileDownloadHelper.java
  src/main/java/edu/harvard/iq/dataverse/FileDownloadServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/ManageFilePermissionsPage.java
  src/main/java/edu/harvard/iq/dataverse/api/Access.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/RequestAccessCommand.java
  src/main/java/propertyFiles/Bundle.properties
  src/main/resources/db/migration/V5.13.0.4__8092-timestamp-of-data-access-request.sql
  src/main/webapp/file-download-button-fragment.xhtml
  src/main/webapp/filesFragment.xhtml
  src/main/webapp/permissions-manage-files.xhtml
Labels: Feature: Request Access Workflow, DANS, Size: 3
