Repository IQSS/dataverse, pull requests merged in 2023-06, with the labels that each got.

#9574 configbaker container
  .github/workflows/container_app_pr.yml
  .github/workflows/container_app_push.yml
  .github/workflows/shellcheck.yml
  conf/solr/8.11.1/update-fields.sh
  doc/release-notes/9573-configbaker.md
  doc/sphinx-guides/source/admin/metadatacustomization.rst
  doc/sphinx-guides/source/container/configbaker-image.rst
  doc/sphinx-guides/source/container/dev-usage.rst
  doc/sphinx-guides/source/container/index.rst
  docker-compose-dev.yml
  modules/container-configbaker/Dockerfile
  modules/container-configbaker/README.md
  modules/container-configbaker/assembly.xml
  modules/container-configbaker/scripts/bootstrap.sh
  modules/container-configbaker/scripts/bootstrap/base/init.sh
  modules/container-configbaker/scripts/bootstrap/dev/init.sh
  modules/container-configbaker/scripts/fix-fs-perms.sh
  modules/container-configbaker/scripts/help.sh
  modules/dataverse-parent/pom.xml
  pom.xml
  scripts/api/setup-all.sh
  scripts/api/setup-builtin-roles.sh
  scripts/api/setup-datasetfields.sh
  scripts/api/setup-identity-providers.sh
Labels: Containers & Cloud, Size: 3

#9399 #9398 - fixing issues with metadata language inherited option label
  src/main/java/edu/harvard/iq/dataverse/SettingsWrapper.java
Labels: Feature: Metadata, Size: 3

#9632 External Exporters bug fix
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java
Labels: Size: 3

#9493 9488 internationalization issues
  src/main/java/edu/harvard/iq/dataverse/DataFile.java
  src/main/java/edu/harvard/iq/dataverse/DatasetFieldValueValidator.java
  src/main/java/edu/harvard/iq/dataverse/MailServiceBean.java
  src/main/java/propertyFiles/Bundle.properties
  src/main/webapp/dataverseuser.xhtml
  src/main/webapp/file-download-button-fragment.xhtml
Labels: Feature: Internationalization, Size: 3

#6543 MDC handle legacy counts
  doc/release-notes/6542-mdc-legacy-counts.md
  src/main/java/edu/harvard/iq/dataverse/GuestbookResponseServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/SettingsWrapper.java
  src/main/java/edu/harvard/iq/dataverse/settings/SettingsServiceBean.java
  src/main/java/propertyFiles/Bundle.properties
  src/main/webapp/dataset.xhtml
  src/main/webapp/file.xhtml
  src/main/webapp/resources/css/structure.css
Labels: QDR, Size: 10

#9636 Fix n test series multiple
  scripts/api/data/dataset-create-new-all-default-fields.json
  src/test/java/edu/harvard/iq/dataverse/api/MetadataBlocksIT.java
Labels: Type: Bug, Feature: Performance & Stability, Testing: API, Size: 3

#9639 Payara downloads moved to Nexus
  doc/sphinx-guides/source/installation/prerequisites.rst
Labels: Feature: Installation Guide, Size: 3

#9558 async indexing after update command
  doc/release-notes/9558-async-indexing.md
  pom.xml
  src/main/java/edu/harvard/iq/dataverse/DataFileServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/Dataset.java
  src/main/java/edu/harvard/iq/dataverse/DatasetPage.java
  src/main/java/edu/harvard/iq/dataverse/DatasetServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/DatasetVersionServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/DvObject.java
  src/main/java/edu/harvard/iq/dataverse/DvObjectServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/PermissionServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/main/java/edu/harvard/iq/dataverse/api/EditDDI.java
  src/main/java/edu/harvard/iq/dataverse/api/Files.java
  src/main/java/edu/harvard/iq/dataverse/api/Index.java
  src/main/java/edu/harvard/iq/dataverse/datasetutility/AddReplaceFileHelper.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/AbstractCreateDatasetCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/CreateDatasetVersionCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/DeaccessionDatasetVersionCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/DeleteDatasetLinkingDataverseCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/DeleteDatasetVersionCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/FinalizeDatasetPublicationCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/LinkDatasetCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/MoveDatasetCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/MoveDataverseCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/RedetectFileTypeCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/RegisterDvObjectCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/ReturnDatasetToAuthorCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/SetCurationStatusCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/SetDatasetCitationDateCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/SubmitDatasetForReviewCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/UpdateDatasetVersionCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/UpdateDataverseCommand.java
  src/main/java/edu/harvard/iq/dataverse/ingest/IngestMessage.java
  src/main/java/edu/harvard/iq/dataverse/ingest/IngestMessageBean.java
  src/main/java/edu/harvard/iq/dataverse/ingest/IngestServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/search/IndexBatchServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/search/IndexServiceBean.java
  src/test/java/edu/harvard/iq/dataverse/api/MoveIT.java
  src/test/java/edu/harvard/iq/dataverse/api/SearchIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
  src/test/java/edu/harvard/iq/dataverse/engine/command/impl/MoveDatasetCommandTest.java
  src/test/java/edu/harvard/iq/dataverse/engine/command/impl/MoveDataverseCommandTest.java
  src/test/java/edu/harvard/iq/dataverse/engine/command/impl/ReturnDatasetToAuthorCommandTest.java
  src/test/java/edu/harvard/iq/dataverse/engine/command/impl/SubmitDatasetForReviewCommandTest.java
Labels: Size: 10

#9454 External tools fix
  doc/sphinx-guides/source/_static/installation/files/root/external-tools/dynamicDatasetTool.json
  doc/sphinx-guides/source/_static/installation/files/root/external-tools/fabulousFileTool.json
  src/main/java/edu/harvard/iq/dataverse/externaltools/ExternalToolHandler.java
Labels: Size: 3, Community

#9482 IQSS/9431-support checksum alg in direct uploads
  doc/release-notes/9431-checksum-alg-in-direct-uploads.md
  doc/sphinx-guides/source/api/native-api.rst
  doc/sphinx-guides/source/installation/config.rst
  src/main/java/edu/harvard/iq/dataverse/api/Files.java
  src/main/webapp/editFilesFragment.xhtml
  src/main/webapp/provenance-popups-fragment.xhtml
  src/main/webapp/resources/css/fontcustom.css-e
  src/main/webapp/resources/js/crypto-js/4.0.0/core.js
  src/main/webapp/resources/js/crypto-js/4.0.0/md5.js
  src/main/webapp/resources/js/crypto-js/4.0.0/sha1.js
  src/main/webapp/resources/js/crypto-js/4.0.0/sha256.js
  src/main/webapp/resources/js/crypto-js/4.0.0/sha512.js
  src/main/webapp/resources/js/crypto-js/4.0.0/x64-core.js
  src/main/webapp/resources/js/fileupload.js
Labels: QDR, Size: 3

#9653 VarMetadata fixes for #9175
  src/main/java/edu/harvard/iq/dataverse/export/ddi/DdiExportUtil.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java
Labels: DANS

#9600 add H5Web to guides
  doc/release-notes/9480-h5web.md
  doc/sphinx-guides/source/_static/admin/dataverse-external-tools.tsv
  doc/sphinx-guides/source/user/dataset-management.rst
  doc/sphinx-guides/source/user/img/h5web.png
Labels: pm.netcdf-hdf5.d

#9584 9540 - more docs for container usage
  doc/sphinx-guides/source/container/dev-usage.rst
  doc/sphinx-guides/source/developers/dev-environment.rst
  doc/sphinx-guides/source/developers/windows.rst
  docker-compose-dev.yml
Labels: Containers & Cloud, Size: 3, Feature: Container Guide
