Repository IQSS/dataverse, pull requests merged in 2023-05, with the labels that each got.

#9564 constrain description display
  src/main/webapp/mydata_templates/cards_minimum.html
Labels: Size: 3

#9256 Make Series multiple #9255
  conf/solr/8.11.1/schema.xml
  doc/release-notes/9256-series.md
  doc/sphinx-guides/source/_static/api/ddi_dataset.xml
  scripts/api/data/metadatablocks/citation.tsv
  src/main/java/edu/harvard/iq/dataverse/DataCitation.java
  src/main/java/edu/harvard/iq/dataverse/DatasetVersion.java
  src/main/java/edu/harvard/iq/dataverse/api/imports/ImportDDIServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/export/ddi/DdiExportUtil.java
  src/main/java/edu/harvard/iq/dataverse/export/openaire/OpenAireExportUtil.java
  src/test/java/edu/harvard/iq/dataverse/api/DataversesIT.java
  src/test/java/edu/harvard/iq/dataverse/export/dataset-all-defaults.txt
  src/test/java/edu/harvard/iq/dataverse/export/ddi/dataset-create-new-all-ddi-fields.json
  src/test/java/edu/harvard/iq/dataverse/export/ddi/exportfull.xml
Labels: Feature: Metadata, Size: 3

#9204 IQSS/4959-Support-By-Category-and-Folder-Grouping
  doc/release-notes/9204-group-by-file-ordering.md
  doc/sphinx-guides/source/installation/config.rst
  src/main/java/edu/harvard/iq/dataverse/DatasetPage.java
  src/main/java/edu/harvard/iq/dataverse/DatasetVersion.java
  src/main/java/edu/harvard/iq/dataverse/FileMetadata.java
  src/main/java/edu/harvard/iq/dataverse/settings/SettingsServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/util/DataFileComparator.java
  src/main/java/propertyFiles/Bundle.properties
  src/main/webapp/dataset.xhtml
  src/main/webapp/filesFragment.xhtml
  src/main/webapp/resources/css/structure.css
Labels: QDR, JHU, Size: 33, ASU

#9186 IQSS/9185 contact email updates
  doc/release-notes/9185-contact-email-updates.md
  doc/sphinx-guides/source/api/native-api.rst
  doc/sphinx-guides/source/installation/config.rst
  src/main/java/edu/harvard/iq/dataverse/MailServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/SendFeedbackDialog.java
  src/main/java/edu/harvard/iq/dataverse/api/FeedbackApi.java
  src/main/java/edu/harvard/iq/dataverse/feedback/Feedback.java
  src/main/java/edu/harvard/iq/dataverse/feedback/FeedbackUtil.java
  src/main/java/edu/harvard/iq/dataverse/settings/JvmSettings.java
  src/main/java/propertyFiles/Bundle.properties
  src/main/webapp/contactFormFragment.xhtml
  src/test/java/edu/harvard/iq/dataverse/feedback/FeedbackUtilTest.java
  src/test/java/edu/harvard/iq/dataverse/util/PersonOrOrgUtilTest.java
  tests/data/datasetContacts1.json
Labels: QDR, Size: 3

#9579 9578 - fix RTFD build by adding a config file for it
  .readthedocs.yml
Labels: Feature: Developer Guide, Feature: API Guide, Feature: Installation Guide, Feature: Admin Guide, Feature: User Guide, Feature: Style Guide, Containers & Cloud, Feature: Container Guide

#9576 9575 fix CI for app images pushing
  .github/workflows/container_app_pr.yml
  .github/workflows/container_app_push.yml
  .github/workflows/pr_comment_commands.yml
Labels: Feature: Developer Guide, Containers & Cloud, Size: 3, Feature: Container Guide

#9533 9531 - Add a Log Out endpoint available when the session API auth feature flag is enabled
  src/main/java/edu/harvard/iq/dataverse/api/Logout.java
  src/main/java/edu/harvard/iq/dataverse/settings/JvmSettings.java
  src/test/java/edu/harvard/iq/dataverse/api/LogoutIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: Size: 3

#9582 9469 accented letters and other utf8 characters in Stata ingest
  src/main/java/edu/harvard/iq/dataverse/ingest/tabulardata/impl/plugins/dta/DataReader.java
  src/main/java/edu/harvard/iq/dataverse/ingest/tabulardata/impl/plugins/dta/NewDTAFileReader.java
Labels: Size: 3

#9586 #9565 Fix metrics API "file/byType/monthly" by using specific key cache
  src/main/java/edu/harvard/iq/dataverse/api/Metrics.java
Labels: Size: 3

#9591 9229 - Add bearer token auth mechanism for OIDC user with feature flag
  conf/keycloak/oidc-keycloak-auth-provider.json
  doc/release-notes/9229-bearer-api-auth.md
  doc/sphinx-guides/source/api/auth.rst
  doc/sphinx-guides/source/developers/remote-users.rst
  doc/sphinx-guides/source/installation/config.rst
  docker-compose-dev.yml
  src/main/java/edu/harvard/iq/dataverse/api/auth/BearerTokenAuthMechanism.java
  src/main/java/edu/harvard/iq/dataverse/api/auth/CompoundAuthMechanism.java
  src/main/java/edu/harvard/iq/dataverse/authorization/providers/oauth2/oidc/OIDCAuthProvider.java
  src/main/java/edu/harvard/iq/dataverse/settings/FeatureFlags.java
  src/test/java/edu/harvard/iq/dataverse/api/auth/BearerTokenAuthMechanismTest.java
  src/test/java/edu/harvard/iq/dataverse/api/auth/doubles/BearerTokenKeyContainerRequestTestFake.java
Labels: Feature: Account & User Info, Size: 3

#8940 8822 incomplete datasets via api
  conf/solr/8.11.1/schema.xml
  doc/release-notes/8822-incomplete-datasets-via-api.md
  doc/sphinx-guides/source/api/native-api.rst
  doc/sphinx-guides/source/installation/config.rst
  doc/sphinx-guides/source/user/account.rst
  src/main/java/edu/harvard/iq/dataverse/Dataset.java
  src/main/java/edu/harvard/iq/dataverse/DatasetPage.java
  src/main/java/edu/harvard/iq/dataverse/DatasetServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/DatasetVersion.java
  src/main/java/edu/harvard/iq/dataverse/FilePage.java
  src/main/java/edu/harvard/iq/dataverse/SettingsWrapper.java
  src/main/java/edu/harvard/iq/dataverse/api/Dataverses.java
  src/main/java/edu/harvard/iq/dataverse/api/Info.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/AbstractCreateDatasetCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/CreateDatasetVersionCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/CreateNewDatasetCommand.java
  src/main/java/edu/harvard/iq/dataverse/mydata/DataRetrieverAPI.java
  src/main/java/edu/harvard/iq/dataverse/mydata/MyDataFilterParams.java
  src/main/java/edu/harvard/iq/dataverse/mydata/MyDataFinder.java
  src/main/java/edu/harvard/iq/dataverse/mydata/MyDataPage.java
  src/main/java/edu/harvard/iq/dataverse/search/IndexServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/search/SearchFields.java
  src/main/java/edu/harvard/iq/dataverse/search/SearchIncludeFragment.java
  src/main/java/edu/harvard/iq/dataverse/search/SearchServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/search/SolrSearchResult.java
  src/main/java/edu/harvard/iq/dataverse/settings/JvmSettings.java
  src/main/java/edu/harvard/iq/dataverse/settings/SettingsServiceBean.java
  src/main/java/propertyFiles/Bundle.properties
  src/main/webapp/dataset.xhtml
  src/main/webapp/file.xhtml
  src/main/webapp/mydata_fragment.xhtml
  src/main/webapp/mydata_templates/cards_minimum.html
  src/main/webapp/resources/js/mydata.js
  src/main/webapp/search-include-fragment.xhtml
Labels: Feature: Metadata, Feature: API, Size: 3, UI/UX: Design

#9602 Fix Flyway script name
  src/main/resources/db/migration/V5.13.0.1__8092-timestamp-of-data-access-request.sql
Labels: Size: 3

#9618 Make DDIExportTest XML validation non-flaky
  src/test/java/edu/harvard/iq/dataverse/export/DDIExporterTest.java
  src/test/resources/xml/xsd/ddi-codebook-2.5/XHTML/xhtml-attribs-1.xsd
  src/test/resources/xml/xsd/ddi-codebook-2.5/XHTML/xhtml-bdo-1.xsd
  src/test/resources/xml/xsd/ddi-codebook-2.5/XHTML/xhtml-blkphras-1.xsd
  src/test/resources/xml/xsd/ddi-codebook-2.5/XHTML/xhtml-blkpres-1.xsd
  src/test/resources/xml/xsd/ddi-codebook-2.5/XHTML/xhtml-blkstruct-1.xsd
  src/test/resources/xml/xsd/ddi-codebook-2.5/XHTML/xhtml-charent-1.xsd
  src/test/resources/xml/xsd/ddi-codebook-2.5/XHTML/xhtml-datatypes-1.xsd
  src/test/resources/xml/xsd/ddi-codebook-2.5/XHTML/xhtml-framework-1.xsd
  src/test/resources/xml/xsd/ddi-codebook-2.5/XHTML/xhtml-hypertext-1.xsd
  src/test/resources/xml/xsd/ddi-codebook-2.5/XHTML/xhtml-inlphras-1.xsd
  src/test/resources/xml/xsd/ddi-codebook-2.5/XHTML/xhtml-inlpres-1.xsd
  src/test/resources/xml/xsd/ddi-codebook-2.5/XHTML/xhtml-inlstruct-1.xsd
  src/test/resources/xml/xsd/ddi-codebook-2.5/XHTML/xhtml-inlstyle-1.xsd
  src/test/resources/xml/xsd/ddi-codebook-2.5/XHTML/xhtml-list-1.xsd
  src/test/resources/xml/xsd/ddi-codebook-2.5/XHTML/xhtml-notations-1.xsd
  src/test/resources/xml/xsd/ddi-codebook-2.5/XHTML/xhtml-pres-1.xsd
  src/test/resources/xml/xsd/ddi-codebook-2.5/XHTML/xhtml-table-1.xsd
  src/test/resources/xml/xsd/ddi-codebook-2.5/XHTML/xhtml-text-1.xsd
  src/test/resources/xml/xsd/ddi-codebook-2.5/dc.xsd
  src/test/resources/xml/xsd/ddi-codebook-2.5/dcmitype.xsd
  src/test/resources/xml/xsd/ddi-codebook-2.5/dcterms.xsd
  src/test/resources/xml/xsd/ddi-codebook-2.5/ddi-xhtml11-model-1.xsd
  src/test/resources/xml/xsd/ddi-codebook-2.5/ddi-xhtml11-modules-1.xsd
  src/test/resources/xml/xsd/ddi-codebook-2.5/ddi-xhtml11.xsd
  src/test/resources/xml/xsd/ddi-codebook-2.5/ddi_codebook_2_5.xsd
  src/test/resources/xml/xsd/ddi-codebook-2.5/xml.xsd
Labels: Testing: API, Size: 3

#9543 Remove duplicate entry api/info/metrics/filedownloads/monthly
  doc/sphinx-guides/source/api/metrics.rst
Labels: Size: 3

#9451 Replaced hard coded strings in File Access button by new Bundle properties
  src/main/java/propertyFiles/Bundle.properties
  src/main/webapp/file-download-button-fragment.xhtml
Labels: Feature: Internationalization, Size: 3

#9571 Internationalization of ingest messages
  src/main/java/edu/harvard/iq/dataverse/ingest/IngestMessageBean.java
  src/main/java/propertyFiles/Bundle.properties
Labels: Feature: Internationalization, Size: 3

#9175 DANS - Exporters in external jars
  .github/workflows/container_app_pr.yml
  .github/workflows/container_app_push.yml
  .github/workflows/maven_unit_test.yml
  .github/workflows/spi_release.yml
  doc/release-notes/9175-external-exporters.md
  doc/sphinx-guides/source/developers/index.rst
  doc/sphinx-guides/source/developers/metadataexport.rst
  doc/sphinx-guides/source/installation/advanced.rst
  doc/sphinx-guides/source/installation/config.rst
  modules/dataverse-parent/pom.xml
  modules/dataverse-spi/.gitignore
  modules/dataverse-spi/pom.xml
  modules/dataverse-spi/src/main/java/io/gdcc/spi/export/ExportDataProvider.java
  modules/dataverse-spi/src/main/java/io/gdcc/spi/export/ExportException.java
  modules/dataverse-spi/src/main/java/io/gdcc/spi/export/Exporter.java
  modules/dataverse-spi/src/main/java/io/gdcc/spi/export/XMLExporter.java
  pom.xml
  src/main/java/edu/harvard/iq/dataverse/DatasetPage.java
  src/main/java/edu/harvard/iq/dataverse/DatasetServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/FilePage.java
  src/main/java/edu/harvard/iq/dataverse/api/Files.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/CuratePublishedDatasetVersionCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/DeaccessionDatasetVersionCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/FinalizeDatasetPublicationCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/RedetectFileTypeCommand.java
  src/main/java/edu/harvard/iq/dataverse/export/DCTermsExporter.java
  src/main/java/edu/harvard/iq/dataverse/export/DDIExporter.java
  src/main/java/edu/harvard/iq/dataverse/export/DataCiteExporter.java
  src/main/java/edu/harvard/iq/dataverse/export/DublinCoreExporter.java
  src/main/java/edu/harvard/iq/dataverse/export/ExportException.java
  src/main/java/edu/harvard/iq/dataverse/export/ExportService.java
  src/main/java/edu/harvard/iq/dataverse/export/HtmlCodeBookExporter.java
  src/main/java/edu/harvard/iq/dataverse/export/InternalExportDataProvider.java
  src/main/java/edu/harvard/iq/dataverse/export/JSONExporter.java
  src/main/java/edu/harvard/iq/dataverse/export/OAI_DDIExporter.java
  src/main/java/edu/harvard/iq/dataverse/export/OAI_OREExporter.java
  src/main/java/edu/harvard/iq/dataverse/export/OpenAireExporter.java
  src/main/java/edu/harvard/iq/dataverse/export/SchemaDotOrgExporter.java
  src/main/java/edu/harvard/iq/dataverse/export/ddi/DdiExportUtil.java
  src/main/java/edu/harvard/iq/dataverse/export/spi/Exporter.java
  src/main/java/edu/harvard/iq/dataverse/harvest/server/OAIRecordServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/harvest/server/web/servlet/OAIServlet.java
  src/main/java/edu/harvard/iq/dataverse/harvest/server/xoai/DataverseXoaiItemRepository.java
  src/main/java/edu/harvard/iq/dataverse/ingest/IngestServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/settings/JvmSettings.java
  src/main/java/edu/harvard/iq/dataverse/util/BundleUtil.java
  src/main/java/edu/harvard/iq/dataverse/util/bagit/OREMap.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java
  src/main/resources/META-INF/microprofile-config.properties
  src/test/java/edu/harvard/iq/dataverse/export/DDIExporterTest.java
  src/test/java/edu/harvard/iq/dataverse/export/OpenAireExporterTest.java
  src/test/java/edu/harvard/iq/dataverse/export/SchemaDotOrgExporterTest.java
  src/test/java/edu/harvard/iq/dataverse/util/BundleUtilTest.java
Labels: DANS, HERMES, Size: 10

#9406 #9404 Added Harvesting key to customize facet label
  src/main/java/propertyFiles/Bundle.properties
Labels: Feature: Search/Browse, Feature: Internationalization, Size: 3
