Repository IQSS/dataverse, pull requests merged in 2023-09, with the labels that each got.

#9844 switch to UNF 6.0 on Maven Central
  doc/sphinx-guides/source/developers/dependencies.rst
  local_lib/org/dataverse/unf/6.0/unf-6.0.jar
  local_lib/org/dataverse/unf/6.0/unf-6.0.jar.md5
  local_lib/org/dataverse/unf/6.0/unf-6.0.jar.sha1
  local_lib/org/dataverse/unf/6.0/unf-6.0.pom
  local_lib/org/dataverse/unf/6.0/unf-6.0.pom.md5
  local_lib/org/dataverse/unf/6.0/unf-6.0.pom.sha1
  modules/dataverse-parent/pom.xml
Labels: Size: 0.5

#9833 Added additional line in Permalinks config
  doc/sphinx-guides/source/installation/config.rst
Labels: Size: 0.5

#9903 fix installer, CREATE instead of ALL for public schema (Postgres 15)
  scripts/installer/install.py
Labels: Size: 10

#9881 Add getZipDownloadLimit and getMaxEmbargoDurationInMonths API info endpoints
  doc/release-notes/9880-info-api-zip-limit-embargo.md
  doc/sphinx-guides/source/api/native-api.rst
  doc/sphinx-guides/source/developers/api-design.rst
  doc/sphinx-guides/source/developers/index.rst
  doc/sphinx-guides/source/installation/config.rst
  src/main/java/edu/harvard/iq/dataverse/api/AbstractApiBean.java
  src/main/java/edu/harvard/iq/dataverse/api/Info.java
  src/test/java/edu/harvard/iq/dataverse/api/InfoIT.java
Labels: Size: 3

#9009 Remove unused GPL-licensed code
  src/main/java/edu/harvard/iq/dataverse/ingest/metadataextraction/spi/FileMetadataExtractorSpi.java
  src/main/java/edu/harvard/iq/dataverse/ingest/plugin/spi/DigraphNode.java
  src/main/java/edu/harvard/iq/dataverse/ingest/plugin/spi/IngestServiceProvider.java
  src/main/java/edu/harvard/iq/dataverse/ingest/plugin/spi/PartiallyOrderedSet.java
  src/main/java/edu/harvard/iq/dataverse/ingest/plugin/spi/RegisterableService.java
  src/main/java/edu/harvard/iq/dataverse/ingest/plugin/spi/ServiceRegistry.java
Labels: Size: 0.5

#9768 exclusion of ingested files during mimetype redetection
  src/main/java/edu/harvard/iq/dataverse/api/Files.java
Labels: Size: 3

#9690 Clarify note about Basic File Access in API Guide
  doc/sphinx-guides/source/api/dataaccess.rst
Labels: Feature: API Guide, Size: 0.5

#9929 add UBC Dataverse_Utils to client libraries page
  doc/sphinx-guides/source/api/client-libraries.rst
Labels: Feature: API Guide, Size: 0.5

#9936 document harvesting server IT config
  doc/sphinx-guides/source/developers/testing.rst
Labels: Feature: Developer Guide, Size: 0.5

#9886 increase configbaker timeout
  modules/container-configbaker/scripts/bootstrap.sh
Labels: Containers, Size: 0.5

#9885 fix command for only building configbaker image
  doc/sphinx-guides/source/container/configbaker-image.rst
Labels: Containers, Feature: Container Guide, Size: 0.5

#9930 feat(ct): add labels with service dependency versions to images #9928
  src/main/docker/Dockerfile
Labels: Containers, Size: 0.5

#9935 9933 configbaker expose bootstrap
  modules/container-configbaker/scripts/bootstrap.sh
  modules/container-configbaker/scripts/bootstrap/dev/init.sh
Labels: Containers, Size: 0.5

#9693 Dataset files API extension for file display data with pagination and sorting
  doc/release-notes/9692-files-api-extension.md
  doc/sphinx-guides/source/api/dataaccess.rst
  doc/sphinx-guides/source/api/metrics.rst
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/DatasetVersionServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/FileDownloadServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/api/Access.java
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/main/java/edu/harvard/iq/dataverse/api/Files.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java
  src/test/java/edu/harvard/iq/dataverse/api/AccessIT.java
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
  src/test/java/edu/harvard/iq/dataverse/api/FilesIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
  src/test/resources/tab/test.tab
Labels: Size: 10

#9859 DANS Archiving, Bag, and OREMap updates
  doc/release-notes/9859-ORE and Bag updates.md
  doc/sphinx-guides/source/admin/integrations.rst
  doc/sphinx-guides/source/api/native-api.rst
  doc/sphinx-guides/source/installation/config.rst
  src/main/java/edu/harvard/iq/dataverse/util/bagit/OREMap.java
  src/main/java/edu/harvard/iq/dataverse/util/bagit/OREMapHelper.java
Labels: DANS, QDR, Size: 10

#9440 make Alternative Title repeatable
  conf/solr/9.3.0/schema.xml
  doc/release-notes/9428-alternative-title.md
  scripts/api/data/dataset-create-new-all-default-fields.json
  scripts/api/data/metadatablocks/citation.tsv
  src/main/java/edu/harvard/iq/dataverse/api/imports/ImportDDIServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/export/ddi/DdiExportUtil.java
  src/main/java/edu/harvard/iq/dataverse/export/openaire/OpenAireExportUtil.java
  src/test/java/edu/harvard/iq/dataverse/export/dataset-all-defaults.txt
  src/test/java/edu/harvard/iq/dataverse/export/ddi/dataset-create-new-all-ddi-fields.json
  src/test/java/edu/harvard/iq/dataverse/export/ddi/dataset-finch1.json
  src/test/java/edu/harvard/iq/dataverse/export/ddi/dataset-finch1.xml
  src/test/java/edu/harvard/iq/dataverse/export/ddi/exportfull.xml
Labels: Feature: Metadata, Size: 10

#9779 Update to Maven Docker Plugin 0.43.4
  modules/dataverse-parent/pom.xml
Labels: Containers, Size: 0.5

#9900 Extend DataFile API payload and new endpoints for Files (getHasBeenDeleted) and Access (userFileAccessRequested)
  doc/release-notes/9851-datafile-payload-extension-new-file-access-endpoints.md
  doc/sphinx-guides/source/api/dataaccess.rst
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/api/Access.java
  src/main/java/edu/harvard/iq/dataverse/api/Files.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java
  src/test/java/edu/harvard/iq/dataverse/api/AccessIT.java
  src/test/java/edu/harvard/iq/dataverse/api/FilesIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: Size: 3

#9820 Dataset files API extension for search text filtering
  doc/release-notes/9785-files-api-extension-search-text.md
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/DatasetVersionFilesServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: Size: 3

#9003 9002 allow direct upload setting
  doc/release-notes/9002_allow_direct_upload_setting.md
  doc/sphinx-guides/source/developers/s3-direct-upload-api.rst
  doc/sphinx-guides/source/installation/config.rst
  src/main/java/edu/harvard/iq/dataverse/dataaccess/StorageIO.java
Labels: Feature: File Upload & Handling, Size: 3

#9409 9361 storage quotas
  src/main/java/edu/harvard/iq/dataverse/DataFileServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/DatasetServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/EditDatafilesPage.java
  src/main/java/edu/harvard/iq/dataverse/api/datadeposit/MediaResourceManagerImpl.java
  src/main/java/edu/harvard/iq/dataverse/datasetutility/AddReplaceFileHelper.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/CreateNewDataFilesCommand.java
  src/main/java/edu/harvard/iq/dataverse/settings/SettingsServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/util/FileUtil.java
  src/main/java/edu/harvard/iq/dataverse/util/SystemConfig.java
  src/main/java/edu/harvard/iq/dataverse/util/bagit/data/FileUtilWrapper.java
  src/main/java/edu/harvard/iq/dataverse/util/file/FileExceedsStorageQuotaException.java
  src/main/java/propertyFiles/Bundle.properties
  src/main/webapp/editFilesFragment.xhtml
Labels: Size: 10, D: FixRateLimitingBehaviors
