Repository IQSS/dataverse, pull requests merged in 2023-08, with the labels that each got.

#9722 add double quotes in curl urls
  doc/sphinx-guides/source/api/native-api.rst
Labels: Feature: API Guide, Size: 0.5

#9688 5.14 release notes
  doc/release-notes/1249-collapse_dataverse_description.md
  doc/release-notes/215-handles-upgrade-reminder.md
  doc/release-notes/3913-delete-file-endpoint
  doc/release-notes/5.14-release-notes.md
  doc/release-notes/5042-add-mydata-doc-api.md
  doc/release-notes/6542-mdc-legacy-counts.md
  doc/release-notes/7000-pidproviders.md
  doc/release-notes/8092-timestamp-of-data-access-request.md
  doc/release-notes/8424-signposting.md
  doc/release-notes/8674-permalinks.md
  doc/release-notes/8822-incomplete-datasets-via-api.md
  doc/release-notes/8889-2-filepids-in-collections-changes.md
  doc/release-notes/8889-filepids-in-collections.md
  doc/release-notes/9063-session-api-auth.md
  doc/release-notes/9100-schema.org-updates.md
  doc/release-notes/9148-license-via-api.md
  doc/release-notes/9150-improved-external-vocab-supprt.md
  doc/release-notes/9175-external-exporters.md
  doc/release-notes/9185-contact-email-updates.md
  doc/release-notes/9204-group-by-file-ordering.md
  doc/release-notes/9229-bearer-api-auth.md
  doc/release-notes/9256-series.md
  doc/release-notes/9277-nonstopmode-pdf-guides.md
  doc/release-notes/9331-extract-bounding-box.md
  doc/release-notes/9374-binder-orig.md
  doc/release-notes/9387-system_metadata_blocks.md
  doc/release-notes/9414-containerized_dev_dependencies.md
  doc/release-notes/9431-checksum-alg-in-direct-uploads.md
  doc/release-notes/9434-app-container.md
  doc/release-notes/9480-h5web.md
  doc/release-notes/9558-async-indexing.md
  doc/release-notes/9573-configbaker.md
  doc/release-notes/9588-datasets-api-extension.md
  doc/release-notes/9656-api-optional-dataset-params.md
  doc/release-notes/9663-Ask-Dataverse-tool.md
  doc/release-notes/9667-metadatablocks-api-extension.md
  doc/release-notes/9691-go-client-library.md
  doc/release-notes/9698-embargo-info-in-ORE.md
  doc/release-notes/9704-GeotifShp.md
Labels: Size: 3

#9759 IQSS/9758 Fix Tabular Tag entry from file table kebab menu
  src/main/webapp/editFilesFragment.xhtml
Labels: Size: 3

#9789 Upload war file after unit test build as actions artifact
  .github/workflows/maven_unit_test.yml
  src/main/java/edu/harvard/iq/dataverse/DatasetVersion.java
Labels: Feature: Code Infrastructure

#9795 Update to Payara 6.2023.8
  doc/sphinx-guides/source/developers/classic-dev-env.rst
  doc/sphinx-guides/source/installation/prerequisites.rst
  downloads/download.sh
  modules/container-base/src/main/docker/Dockerfile
  modules/dataverse-parent/pom.xml
  scripts/vagrant/setup.sh
Labels: Feature: Code Infrastructure, Feature: Installer, Feature: Installation Guide, Containers & Cloud

#9845 release note for archivers
  doc/release-notes/9812-archiver-warnings.md
Labels: Size: 3

#9855 get tests passing in Jenkins
  src/test/java/edu/harvard/iq/dataverse/api/DataversesIT.java
  src/test/java/edu/harvard/iq/dataverse/api/FilesIT.java
Labels: Size: 0.5
