Repository IQSS/dataverse, pull requests merged in 2023-10, with the labels that each got.

#9925 make configure tools available at the dataset level
  doc/release-notes/9589-ds-configure-tool.md
  doc/sphinx-guides/source/admin/external-tools.rst
  doc/sphinx-guides/source/api/external-tools.rst
  src/main/java/edu/harvard/iq/dataverse/DatasetPage.java
  src/main/java/edu/harvard/iq/dataverse/externaltools/ExternalToolHandler.java
  src/main/java/propertyFiles/Bundle.properties
  src/main/webapp/dataset.xhtml
  src/test/java/edu/harvard/iq/dataverse/api/ExternalToolsIT.java
  src/test/java/edu/harvard/iq/dataverse/externaltools/ExternalToolHandlerTest.java
Labels: Size: 3

#9853 Dataset files API extension for file counts
  doc/release-notes/9834-files-api-extension-counts.md
  doc/release-notes/9851-datafile-payload-extension-new-file-access-endpoints.md
  doc/sphinx-guides/source/api/dataaccess.rst
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/DatasetVersionFilesServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/api/Access.java
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/main/java/edu/harvard/iq/dataverse/api/Files.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java
  src/test/java/edu/harvard/iq/dataverse/api/AccessIT.java
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
  src/test/java/edu/harvard/iq/dataverse/api/FilesIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: Size: 3, SPA

#9273 OIDC auth: MPCONFIG provisioning, PKCE support and integration tests
  .github/workflows/maven_unit_test.yml
  conf/keycloak/docker-compose.yml
  conf/keycloak/oidc-keycloak-auth-provider.json
  conf/keycloak/oidc-realm.json
  conf/keycloak/run-keycloak.sh
  conf/keycloak/test-realm.json
  doc/release-notes/9268-8349-oidc-improvements.md
  doc/sphinx-guides/source/_static/installation/files/root/auth-providers/oidc.json
  doc/sphinx-guides/source/api/auth.rst
  doc/sphinx-guides/source/developers/remote-users.rst
  doc/sphinx-guides/source/developers/testing.rst
  doc/sphinx-guides/source/developers/tools.rst
  doc/sphinx-guides/source/installation/config.rst
  doc/sphinx-guides/source/installation/oidc.rst
  docker-compose-dev.yml
  modules/dataverse-parent/pom.xml
  pom.xml
  src/main/java/edu/harvard/iq/dataverse/api/auth/BearerTokenAuthMechanism.java
  src/main/java/edu/harvard/iq/dataverse/authorization/AuthenticationProvidersRegistrationServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/authorization/UserRecordIdentifier.java
  src/main/java/edu/harvard/iq/dataverse/authorization/providers/oauth2/AbstractOAuth2AuthenticationProvider.java
  src/main/java/edu/harvard/iq/dataverse/authorization/providers/oauth2/OAuth2LoginBackingBean.java
  src/main/java/edu/harvard/iq/dataverse/authorization/providers/oauth2/oidc/OIDCAuthProvider.java
  src/main/java/edu/harvard/iq/dataverse/authorization/providers/oauth2/oidc/OIDCAuthenticationProviderFactory.java
  src/main/java/edu/harvard/iq/dataverse/settings/JvmSettings.java
  src/main/resources/META-INF/microprofile-config.properties
  src/test/java/edu/harvard/iq/dataverse/api/auth/BearerTokenAuthMechanismTest.java
  src/test/java/edu/harvard/iq/dataverse/api/auth/SessionCookieAuthMechanismTest.java
  src/test/java/edu/harvard/iq/dataverse/authorization/providers/oauth2/OAuth2LoginBackingBeanTest.java
  src/test/java/edu/harvard/iq/dataverse/authorization/providers/oauth2/oidc/OIDCAuthenticationProviderFactoryIT.java
  src/test/java/edu/harvard/iq/dataverse/export/SchemaDotOrgExporterTest.java
  src/test/java/edu/harvard/iq/dataverse/externaltools/ExternalToolHandlerTest.java
  src/test/java/edu/harvard/iq/dataverse/search/IndexServiceBeanTest.java
  src/test/java/edu/harvard/iq/dataverse/search/SolrClientServiceTest.java
  src/test/java/edu/harvard/iq/dataverse/settings/FeatureFlagsTest.java
  src/test/java/edu/harvard/iq/dataverse/settings/JvmSettingsTest.java
  src/test/java/edu/harvard/iq/dataverse/util/SystemConfigTest.java
  src/test/java/edu/harvard/iq/dataverse/util/UrlTokenUtilTest.java
  src/test/java/edu/harvard/iq/dataverse/util/testing/JvmSetting.java
  src/test/java/edu/harvard/iq/dataverse/util/testing/JvmSettingBroker.java
  src/test/java/edu/harvard/iq/dataverse/util/testing/JvmSettingExtension.java
  src/test/java/edu/harvard/iq/dataverse/util/testing/LocalJvmSettings.java
  src/test/java/edu/harvard/iq/dataverse/util/testing/Tags.java
Labels: Feature: Performance & Stability, Containers, NIH OTA: 1.7.1 (reArchitecture), Size: 10, pm.GREI-d-1.7.1

#9972 Reverts revert of 9714-files-api-extension-filters and adds tabular file tag filtering to getVersionFiles endpoint and new endpoint for tagging tab files
  doc/release-notes/9714-files-api-extension-filters.md
  doc/release-notes/9785-files-api-extension-search-text.md
  doc/release-notes/9834-files-api-extension-counts.md
  doc/release-notes/9851-datafile-payload-extension-new-file-access-endpoints.md
  doc/release-notes/9972-files-api-filter-by-tabular-tags.md
  doc/sphinx-guides/source/api/dataaccess.rst
  doc/sphinx-guides/source/api/native-api.rst
  modules/dataverse-parent/pom.xml
  pom.xml
  src/main/java/edu/harvard/iq/dataverse/DataFile.java
  src/main/java/edu/harvard/iq/dataverse/DataFileTag.java
  src/main/java/edu/harvard/iq/dataverse/DatasetVersionFilesServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/DatasetVersionServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/api/Access.java
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/main/java/edu/harvard/iq/dataverse/api/Files.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java
  src/main/java/propertyFiles/Bundle.properties
  src/test/java/edu/harvard/iq/dataverse/api/AccessIT.java
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
  src/test/java/edu/harvard/iq/dataverse/api/FilesIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: SPA

#9989 Disable TC when no Docker around
  doc/sphinx-guides/source/developers/testing.rst
  src/test/java/edu/harvard/iq/dataverse/authorization/providers/oauth2/oidc/OIDCAuthenticationProviderFactoryIT.java
Labels: Feature: Developer Guide, Component: Containers, Size: 0.5

#9986 Add Markdown previewer in Guide
  doc/release-notes/9412-markdown-previewer.md
  doc/sphinx-guides/source/_static/admin/dataverse-external-tools.tsv
  doc/sphinx-guides/source/user/dataset-management.rst
Labels: hacktoberfest-accepted

#9906 Fix the issues with the permissions of the Docker scripts on Windows
  modules/container-configbaker/Dockerfile
Labels: Component: Containers, Size: 0.5

#9975 Use stable Rewrite releases for Jakarta EE 10
  modules/dataverse-parent/pom.xml
  pom.xml
Labels: Component: Code Infrastructure, Component: JSF, Size: 0.5

#9977 Equals method fix
  src/main/java/edu/harvard/iq/dataverse/DatasetFieldDefaultValue.java
  src/main/java/edu/harvard/iq/dataverse/DataverseContact.java
  src/main/java/edu/harvard/iq/dataverse/DataverseFacet.java
  src/main/java/edu/harvard/iq/dataverse/DataverseFeaturedDataverse.java
  src/main/java/edu/harvard/iq/dataverse/DataverseTheme.java
  src/test/java/edu/harvard/iq/dataverse/DatasetFieldDefaultValueTest.java
  src/test/java/edu/harvard/iq/dataverse/DataverseContactTest.java
  src/test/java/edu/harvard/iq/dataverse/DataverseFacetTest.java
  src/test/java/edu/harvard/iq/dataverse/DataverseFeaturedDataverseTest.java
  src/test/java/edu/harvard/iq/dataverse/DataverseThemeTest.java
Labels: Component: Code Infrastructure, Size: 0.5, hacktoberfest-accepted

#9961 allow fast xhtml edits in Docker
  docker-compose-dev.yml
Labels: Component: Containers, Size: 0.5

#9985 getVersionFileCounts API endpoints extended to support filtering by criteria
  doc/release-notes/9907-files-api-counts-with-criteria.md
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/DatasetVersionFilesServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/FileSearchCriteria.java
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java
  src/main/java/propertyFiles/Bundle.properties
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: SPA

#9937 Extend Datasets API to support dataset deaccession and recovery of files and file counts of deaccessioned datasets
  doc/release-notes/9852-files-api-extension-deaccession.md
  doc/release-notes/9958-dataset-api-downloadsize-ignore-tabular-size.md
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/DatasetServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/DatasetVersionFilesServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/api/ApiConstants.java
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/main/java/edu/harvard/iq/dataverse/dataset/DatasetUtil.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/GetDatasetStorageSizeCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/GetLatestAccessibleDatasetVersionCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/GetLatestPublishedDatasetVersionCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/GetSpecificPublishedDatasetVersionCommand.java
  src/main/java/edu/harvard/iq/dataverse/externaltools/ExternalToolHandler.java
  src/main/java/edu/harvard/iq/dataverse/util/FileUtil.java
  src/main/java/edu/harvard/iq/dataverse/util/URLTokenUtil.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java
  src/main/java/propertyFiles/Bundle.properties
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
  src/test/java/edu/harvard/iq/dataverse/api/DownloadFilesIT.java
  src/test/java/edu/harvard/iq/dataverse/api/FilesIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: Size: 10, SPA

#9819 Configurable docroot via MicroProfile Config
  doc/sphinx-guides/source/installation/config.rst
  docker-compose-dev.yml
  src/main/docker/Dockerfile
  src/main/java/edu/harvard/iq/dataverse/DataverseServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/ThemeWidgetFragment.java
  src/main/java/edu/harvard/iq/dataverse/api/Access.java
  src/main/java/edu/harvard/iq/dataverse/api/Dataverses.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/UpdateDataverseThemeCommand.java
  src/main/java/edu/harvard/iq/dataverse/settings/ConfigCheckService.java
  src/main/java/edu/harvard/iq/dataverse/settings/JvmSettings.java
  src/main/java/edu/harvard/iq/dataverse/sitemap/SiteMapUtil.java
  src/main/java/edu/harvard/iq/dataverse/util/FileUtil.java
  src/main/resources/META-INF/microprofile-config.properties
  src/main/webapp/WEB-INF/glassfish-web.xml
  src/test/java/edu/harvard/iq/dataverse/settings/ConfigCheckServiceTest.java
  src/test/java/edu/harvard/iq/dataverse/sitemap/SiteMapUtilTest.java
  src/test/resources/META-INF/microprofile-config.properties
Labels: Feature: Installation Guide, Component: Containers, Size: 3, Feature: Container Guide

#9955 995x - Signposting fixes
  doc/release-notes/9955-Signposting-updates.md
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/DatasetFieldServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/DatasetPage.java
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/main/java/edu/harvard/iq/dataverse/util/SignpostingResources.java
  src/test/java/edu/harvard/iq/dataverse/api/SignpostingIT.java
Labels: Size: 3, Feature: Signposting

#9883 Versions API improvements (9763)
  doc/release-notes/9763-versions-api-improvements.md
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/Dataset.java
  src/main/java/edu/harvard/iq/dataverse/DatasetServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/DatasetVersion.java
  src/main/java/edu/harvard/iq/dataverse/DatasetVersionServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/main/java/edu/harvard/iq/dataverse/dataset/DatasetUtil.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/FinalizeDatasetPublicationCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/ListVersionsCommand.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java
  src/main/resources/db/migration/V6.0.0.2__9763-embargocitationdate.sql
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: Feature: Performance & Stability, Feature: Publishing & Versions, Size: 10

#10010 guestbook problems post-merge, refix 9825
  src/main/webapp/file-download-popup-fragment.xhtml
  src/main/webapp/guestbook-terms-popup-fragment.xhtml
Labels: Size: 3

#10019 IQSS/10018-Check driver type not id
  src/main/java/edu/harvard/iq/dataverse/dataaccess/StorageIO.java
Labels: Size: 3

#10020 Lookup dataverse by alias or ID when downloading guestbook responses via API
  src/main/java/edu/harvard/iq/dataverse/api/Dataverses.java
  src/test/java/edu/harvard/iq/dataverse/api/DataversesIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: Feature: Guestbook, hacktoberfest-accepted

#10014 Extend Datasets getDownloadSize API endpoint to support file search criteria and deaccessioned datasets
  doc/release-notes/9995-files-api-downloadsize-with-criteria-and-deaccessioned-support.md
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/DatasetVersionFilesServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: SPA

#10023 Extend the API to get Dataset user permissions, new File user permissions, and deaccessioned support for getDatasetVersion endpoint
  doc/release-notes/10001-datasets-files-api-user-permissions.md
  doc/sphinx-guides/source/api/dataaccess.rst
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/FileDownloadServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/api/Access.java
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/test/java/edu/harvard/iq/dataverse/api/AccessIT.java
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: SPA

#10027 Added tabulartags in files metadata for files metadata
  doc/sphinx-guides/source/api/native-api.rst
Labels: Size: 0.5

#10041 Rewrite DatasetVersionFilesServiceBean QueryDSL queries using JPA Criteria and remove the QueryDSL library from the application dependencies
  modules/dataverse-parent/pom.xml
  pom.xml
  src/main/java/edu/harvard/iq/dataverse/DatasetVersionFilesServiceBean.java
Labels: Size: 3, SPA

#10072 Update appendix.rst
  doc/sphinx-guides/source/user/appendix.rst
Labels: Size: 0.5
