Repository IQSS/dataverse, pull requests merged in 2024-08, with the labels that each got.

#10729 Remove InReview lock when dataset is moved to a collection where the author can publish
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/MoveDatasetCommand.java
  src/test/java/edu/harvard/iq/dataverse/engine/command/impl/MoveDatasetCommandTest.java
  src/test/java/edu/harvard/iq/dataverse/mocks/MocksFactory.java
Labels: Type: Bug, FY25 Sprint 2

#10691 tweaks to dev guide when setting up new laptop
  doc/sphinx-guides/source/container/dev-usage.rst
  doc/sphinx-guides/source/contributor/documentation.md
  doc/sphinx-guides/source/developers/dev-environment.rst
  doc/sphinx-guides/source/developers/tips.rst
Labels: Type: Bug, Feature: Developer Guide, Size: 0.5

#9176 check for duplicate keys in Java properties files, fix CodeMeta displayName
  .github/workflows/check_property_files.yml
  .github/workflows/shellspec.yml
  src/main/java/propertyFiles/codeMeta20.properties
  tests/check_duplicate_properties.sh
  tests/verify_mdb_properties.sh
Labels: Feature: Metadata, Feature: Performance & Stability, NIH OTA: 1.3.1, Size: 0.5, GREI 6

#10479 new script for make data count log processing as well as updated docu…
  doc/release-notes/make-data-count-.md
  doc/sphinx-guides/source/_static/util/counter_daily.sh
  doc/sphinx-guides/source/admin/make-data-count.rst
  doc/sphinx-guides/source/developers/make-data-count.rst
  doc/sphinx-guides/source/installation/prerequisites.rst
  src/main/java/edu/harvard/iq/dataverse/makedatacount/DatasetMetrics.java
  src/main/java/edu/harvard/iq/dataverse/makedatacount/MakeDataCountUtil.java
Labels: Size: 10, GREI 4

#10682 update shellspec for Debian 12, Rocky 9
  .github/workflows/shellspec.yml
  tests/shell/spec/spec_helper.sh
Labels: Type: Bug, Component: Code Infrastructure, Size: 0.5

#10738 adding publication statuses to search api response
  doc/release-notes/10733-add-publication-status-to-search-api-results.md
  doc/sphinx-guides/source/api/search.rst
  src/main/java/edu/harvard/iq/dataverse/search/SolrSearchResult.java
  src/test/java/edu/harvard/iq/dataverse/api/SearchIT.java
  src/test/java/edu/harvard/iq/dataverse/search/SolrSearchResultTest.java
Labels: Size: 3, SPA, FY25 Sprint 3

#10758 Add Rust-Dataverse to client libraries documentation
  doc/release-notes/10758-rust-client.md
  doc/sphinx-guides/source/api/client-libraries.rst
  doc/sphinx-guides/source/contributor/code.md
  doc/sphinx-guides/source/contributor/index.md
Labels: Type: Feature, Feature: API Guide

#7044 fix mimetype of error pages
  src/main/webapp/WEB-INF/web.xml
Labels: Size: 3

#10751 Extends the /dataverses API to get user permissions on a collection
  doc/release-notes/10749-dataverse-user-permissions-api-extension.md
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/api/Dataverses.java
  src/test/java/edu/harvard/iq/dataverse/api/DataversesIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: Size: 3, SPA, GREI Re-arch

#10760 Add mimetype for 3D Data readable by the Smithsonian's Voyager app
  src/main/java/edu/harvard/iq/dataverse/api/Access.java
  src/main/java/propertyFiles/MimeTypeDetectionByFileExtension.properties
  src/main/java/propertyFiles/MimeTypeDisplay.properties
  src/main/java/propertyFiles/MimeTypeFacets.properties
Labels: Consider For Next Release

#10077 Use StandardCharsets instead of charset names
  src/main/java/edu/harvard/iq/dataverse/DataCitation.java
  src/main/java/edu/harvard/iq/dataverse/Shib.java
  src/main/java/edu/harvard/iq/dataverse/api/Admin.java
  src/main/java/edu/harvard/iq/dataverse/authorization/providers/builtin/PasswordEncryption.java
  src/main/java/edu/harvard/iq/dataverse/dataaccess/TabularSubsetGenerator.java
  src/main/java/edu/harvard/iq/dataverse/dataset/DatasetUtil.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/DuraCloudSubmitToArchiveCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/GoogleCloudSubmitToArchiveCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/S3SubmitToArchiveCommand.java
  src/main/java/edu/harvard/iq/dataverse/export/JSONExporter.java
  src/main/java/edu/harvard/iq/dataverse/export/OAI_OREExporter.java
  src/main/java/edu/harvard/iq/dataverse/export/SchemaDotOrgExporter.java
  src/main/java/edu/harvard/iq/dataverse/ingest/IngestableDataChecker.java
  src/main/java/edu/harvard/iq/dataverse/ingest/tabulardata/impl/plugins/dta/DTAFileReader.java
  src/main/java/edu/harvard/iq/dataverse/ingest/tabulardata/impl/plugins/dta/DataReader.java
  src/main/java/edu/harvard/iq/dataverse/ingest/tabulardata/impl/plugins/dta/NewDTAFileReader.java
  src/main/java/edu/harvard/iq/dataverse/ingest/tabulardata/impl/plugins/por/PORFileReader.java
  src/main/java/edu/harvard/iq/dataverse/ingest/tabulardata/impl/plugins/rdata/RDATAFileReader.java
  src/main/java/edu/harvard/iq/dataverse/ingest/tabulardata/impl/plugins/sav/SAVFileReader.java
  src/main/java/edu/harvard/iq/dataverse/pidproviders/handle/HandlePidProvider.java
  src/main/java/edu/harvard/iq/dataverse/provenance/ProvPopupFragmentBean.java
  src/main/java/edu/harvard/iq/dataverse/rserve/RemoteDataFrameService.java
  src/main/java/edu/harvard/iq/dataverse/util/StringUtil.java
  src/main/java/edu/harvard/iq/dataverse/util/UrlSignerUtil.java
  src/main/java/edu/harvard/iq/dataverse/util/bagit/BagGenerator.java
  src/main/java/edu/harvard/iq/dataverse/util/bagit/OREMap.java
  src/test/java/edu/harvard/iq/dataverse/api/SearchIT.java
Labels: Component: Code Infrastructure, Size: 10

#7334 IQSS/7068 Reserve File Pids
  doc/release-notes/7068-reserve-file-pids.md
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/DataFileServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/AbstractDatasetCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/FinalizeDatasetPublicationCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/PublishDatasetCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/ReservePidCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/UpdateDatasetVersionCommand.java
  src/main/java/edu/harvard/iq/dataverse/util/SystemConfig.java
  src/main/java/propertyFiles/Bundle.properties
Labels: Size: 3

#10767 Fix dataverses/{identifier}/metadatablocks endpoint to not return fields marked as displayOnCreate=true if there is an input level with include=false
  doc/release-notes/10741-list-metadatablocks-display-on-create-fix.md
  src/main/java/edu/harvard/iq/dataverse/DatasetFieldServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java
  src/test/java/edu/harvard/iq/dataverse/api/DataversesIT.java
  src/test/java/edu/harvard/iq/dataverse/api/MetadataBlocksIT.java
Labels: Size: 3, SPA, GREI Re-arch

#10755 #10754 update bundle for Edit Dataset Permissions (Create Role Popup)
  src/main/java/propertyFiles/Bundle.properties
Labels: Size: 3, FY25 Sprint 3

#10198 Support deletion of saved searches
  doc/release-notes/9317-delete-saved-search.md
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/api/SavedSearches.java
  src/main/java/edu/harvard/iq/dataverse/search/savedsearch/SavedSearchServiceBean.java
  src/test/java/edu/harvard/iq/dataverse/api/SavedSearchIT.java
  tests/integration-tests.txt
Labels: Size: 3

#10689 adding unlink to ui and matching link permissions
  doc/release-notes/10583-dataset-unlink-functionality-same-permission-as-link.md
  doc/sphinx-guides/source/admin/dataverses-datasets.rst
  src/main/java/edu/harvard/iq/dataverse/DatasetPage.java
  src/main/java/edu/harvard/iq/dataverse/DataverseServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/DeleteDatasetLinkingDataverseCommand.java
  src/main/java/propertyFiles/Bundle.properties
  src/main/webapp/dataset.xhtml
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
Labels: Type: Feature, Size: 10, FY25 Sprint 1, FY25 Sprint 2

#10808 #10807 fix GB fragment
  src/main/webapp/guestbook-terms-popup-fragment.xhtml
Labels: Type: Bug, Size: 0.5, FY25 Sprint 4, FY25 Sprint 5

#10792 use DATAVERSE_SITEURL instead of _CT_ version
  doc/sphinx-guides/source/container/running/demo.rst
  docker/compose/demo/compose.yml
Labels: Component: Containers, Size: 0.5, FY25 Sprint 4, FY25 Sprint 5

#10799 update "how to make a PR" doc with current practices
  doc/sphinx-guides/source/developers/version-control.rst
Labels: Feature: Developer Guide, Size: 0.5, FY25 Sprint 4, FY25 Sprint 5

#10796 Add RO-Crate to guides
  doc/release-notes/10744-ro-crate-docs.md
  doc/sphinx-guides/source/installation/advanced.rst
  doc/sphinx-guides/source/user/dataset-management.rst
Labels: Feature: User Guide, Size: 0.5, GREI 6, GREI 3, FY25 Sprint 3, FY25 Sprint 4, FY25 Sprint 5

#10788 add section on links for .rst files
  doc/sphinx-guides/source/contributor/documentation.md
Labels: Size: 0.5, FY25 Sprint 4, Feature: Contributor Guide, FY25 Sprint 5

#10797 Alternate Fix for Curate command failures
  doc/release-notes/10797-update-current-version-bug-fix.md
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/CuratePublishedDatasetVersionCommand.java
  src/main/java/edu/harvard/iq/dataverse/privateurl/PrivateUrlServiceBean.java
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
  src/test/java/edu/harvard/iq/dataverse/dataaccess/RemoteOverlayAccessIOTest.java
Labels: Size: 10, FY25 Sprint 4, FY25 Sprint 5
