Repository IQSS/dataverse, pull requests merged in 2024-02, with the labels that each got.

#10212 10207 bug api datasets versions latest fix
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/GetLatestAccessibleDatasetVersionCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/GetLatestPublishedDatasetVersionCommand.java
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
Labels: Size: 3, SPA

#10284 9634 Dev. Guide checklist for the tasks required when making a field multivalued
  doc/sphinx-guides/source/admin/metadatacustomization.rst
Labels: Size: 3

#10274 #9748 delete tools only added by tests
  src/main/java/edu/harvard/iq/dataverse/api/TestApi.java
  src/test/java/edu/harvard/iq/dataverse/api/ExternalToolsIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: Size: 3

#10303 10297 dataset metadata endpoint fix
  doc/release-notes/10297-metadata-api-fix.md
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
Labels: Type: Bug, Size: 3

#10273 Tutorial for running containers as a demo or for evaluation
  doc/release-notes/10238-container-demo.md
  doc/sphinx-guides/source/container/app-image.rst
  doc/sphinx-guides/source/container/index.rst
  doc/sphinx-guides/source/container/intro.rst
  doc/sphinx-guides/source/container/running/backend-dev.rst
  doc/sphinx-guides/source/container/running/demo.rst
  doc/sphinx-guides/source/container/running/frontend-dev.rst
  doc/sphinx-guides/source/container/running/github-action.rst
  doc/sphinx-guides/source/container/running/index.rst
  doc/sphinx-guides/source/container/running/metadata-blocks.rst
  doc/sphinx-guides/source/container/running/production.rst
  docker/compose/demo/.gitignore
  docker/compose/demo/compose.yml
  modules/container-configbaker/scripts/bootstrap/demo/init.sh
Labels: Size: 10

#10282 8524 adding mechanism for storing tab. files with variable headers
  doc/release-notes/8524-storing-tabular-files-with-varheaders.md
  doc/sphinx-guides/source/installation/config.rst
  src/main/java/edu/harvard/iq/dataverse/DataTable.java
  src/main/java/edu/harvard/iq/dataverse/api/DownloadInstanceWriter.java
  src/main/java/edu/harvard/iq/dataverse/api/TestIngest.java
  src/main/java/edu/harvard/iq/dataverse/dataaccess/FileAccessIO.java
  src/main/java/edu/harvard/iq/dataverse/dataaccess/GlobusOverlayAccessIO.java
  src/main/java/edu/harvard/iq/dataverse/dataaccess/RemoteOverlayAccessIO.java
  src/main/java/edu/harvard/iq/dataverse/dataaccess/S3AccessIO.java
  src/main/java/edu/harvard/iq/dataverse/dataaccess/SwiftAccessIO.java
  src/main/java/edu/harvard/iq/dataverse/dataaccess/TabularSubsetGenerator.java
  src/main/java/edu/harvard/iq/dataverse/dataaccess/TabularSubsetInputStream.java
  src/main/java/edu/harvard/iq/dataverse/export/DDIExportServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/ingest/IngestServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/ingest/tabulardata/TabularDataFileReader.java
  src/main/java/edu/harvard/iq/dataverse/ingest/tabulardata/impl/plugins/csv/CSVFileReader.java
  src/main/java/edu/harvard/iq/dataverse/ingest/tabulardata/impl/plugins/dta/DTAFileReader.java
  src/main/java/edu/harvard/iq/dataverse/ingest/tabulardata/impl/plugins/dta/NewDTAFileReader.java
  src/main/java/edu/harvard/iq/dataverse/ingest/tabulardata/impl/plugins/por/PORFileReader.java
  src/main/java/edu/harvard/iq/dataverse/ingest/tabulardata/impl/plugins/rdata/RDATAFileReader.java
  src/main/java/edu/harvard/iq/dataverse/ingest/tabulardata/impl/plugins/rdata/RTabFileParser.java
  src/main/java/edu/harvard/iq/dataverse/ingest/tabulardata/impl/plugins/sav/SAVFileReader.java
  src/main/java/edu/harvard/iq/dataverse/ingest/tabulardata/impl/plugins/xlsx/XLSXFileReader.java
  src/main/java/edu/harvard/iq/dataverse/settings/SettingsServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/util/SystemConfig.java
  src/main/resources/db/migration/V6.1.0.2__8524-store-tabular-files-with-varheaders.sql
  src/test/java/edu/harvard/iq/dataverse/api/FilesIT.java
  src/test/java/edu/harvard/iq/dataverse/ingest/IngestFrequencyTest.java
  src/test/java/edu/harvard/iq/dataverse/ingest/tabulardata/impl/plugins/csv/CSVFileReaderTest.java
  src/test/java/edu/harvard/iq/dataverse/ingest/tabulardata/impl/plugins/dta/DTAFileReaderTest.java
  src/test/java/edu/harvard/iq/dataverse/ingest/tabulardata/impl/plugins/dta/NewDTAFileReaderTest.java
Labels: Size: 33

#10103 stub out QA guide
  doc/release-notes/10101-qa-guide.md
  doc/sphinx-guides/requirements.txt
  doc/sphinx-guides/source/conf.py
  doc/sphinx-guides/source/developers/intro.rst
  doc/sphinx-guides/source/developers/making-releases.rst
  doc/sphinx-guides/source/developers/sql-upgrade-scripts.rst
  doc/sphinx-guides/source/developers/testing.rst
  doc/sphinx-guides/source/developers/version-control.rst
  doc/sphinx-guides/source/index.rst
  doc/sphinx-guides/source/qa/index.md
  doc/sphinx-guides/source/qa/overview.md
  doc/sphinx-guides/source/qa/performance-tests.md
  doc/sphinx-guides/source/qa/qa-workflow.md
  doc/sphinx-guides/source/qa/test-automation.md
  doc/sphinx-guides/source/qa/testing-approach.md
  doc/sphinx-guides/source/qa/testing-infrastructure.md
Labels: Size: 10

#10300 10229 fix featured dv selection
  src/main/java/edu/harvard/iq/dataverse/DataversePage.java
  src/main/java/propertyFiles/Bundle.properties
Labels: Size: 3

#10293 Update metadatacustomization.rst
  doc/sphinx-guides/source/admin/metadatacustomization.rst
Labels: Size: 0.5

#10222 3437 OAI records for datasets that still exist, but are temporarily un-indexed should not be marked deleted
  doc/release-notes/3437-new-index-api-added.md
  doc/sphinx-guides/source/admin/solr-search-index.rst
  src/main/java/edu/harvard/iq/dataverse/api/Index.java
  src/main/java/edu/harvard/iq/dataverse/harvest/server/OAIRecordServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/harvest/server/OAISetServiceBean.java
  src/test/java/edu/harvard/iq/dataverse/api/HarvestingServerIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: Feature: Harvesting, Size: 33

#9984 External Controlled Vocab: add missing db constraints, add cvoc transaction and try/catch
  doc/release-notes/9983-unique-constraints.md
  scripts/api/data/metadatablocks/astrophysics.tsv
  scripts/api/data/metadatablocks/biomedical.tsv
  scripts/api/data/metadatablocks/citation.tsv
  src/main/java/edu/harvard/iq/dataverse/DatasetFieldServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/DatasetFieldType.java
  src/main/resources/db/migration/V6.1.0.3__9983-missing-unique-constraints.sql
Labels: GDCC: DANS, Size: 10

#10311 #10271 fix tool tests w/arrays
  src/main/java/edu/harvard/iq/dataverse/api/TestApi.java
  src/test/java/edu/harvard/iq/dataverse/api/ExternalToolsIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: Size: 3

#9637 3818 Delete temporary thumbnail files
  src/main/java/edu/harvard/iq/dataverse/dataaccess/ImageThumbConverter.java
Labels: Feature: File Upload & Handling, Size: 3

#10246 file citation via API
  doc/release-notes/10240-file-citation.md
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/api/AbstractApiBean.java
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/main/java/edu/harvard/iq/dataverse/api/Files.java
  src/main/java/propertyFiles/Bundle.properties
  src/test/java/edu/harvard/iq/dataverse/DataCitationTest.java
  src/test/java/edu/harvard/iq/dataverse/api/FilesIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: Size: 10, SPA, SPA: File Page

#10314 OpenShift prep work
  modules/container-base/src/main/docker/Dockerfile
  modules/container-base/src/main/docker/scripts/entrypoint.sh
  modules/container-base/src/main/docker/scripts/init_1_generate_devmode_commands.sh
Labels: Component: Containers, Size: 10

#10299 Update get file endpoint to add a datasetVersion optional query parameter and extend its payload
  doc/release-notes/10280-get-file-api-extension.md
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/DataFile.java
  src/main/java/edu/harvard/iq/dataverse/api/AbstractApiBean.java
  src/main/java/edu/harvard/iq/dataverse/api/Files.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/AbstractGetPublishedFileMetadataCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/GetDataFileCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/GetDraftFileMetadataIfAvailableCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/GetLatestAccessibleFileMetadataCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/GetLatestPublishedFileMetadataCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/GetSpecificPublishedFileMetadataByDatasetVersionCommand.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java
  src/main/java/propertyFiles/Bundle.properties
  src/test/java/edu/harvard/iq/dataverse/api/FilesIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: Size: 10, pm.GREI-d-2.7.1, pm.GREI-d-2.7.2, SPA, SPA: File Page

#10315 Add content to deaccession info message
  src/main/java/propertyFiles/Bundle.properties
  src/main/webapp/dataset.xhtml
Labels: Size: 3

#10322 10286 add owner info
  doc/release-notes/10286-return-owner-added-to-get-apis.md
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/main/java/edu/harvard/iq/dataverse/api/Dataverses.java
  src/main/java/edu/harvard/iq/dataverse/api/Files.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
  src/test/java/edu/harvard/iq/dataverse/api/DataversesIT.java
  src/test/java/edu/harvard/iq/dataverse/api/FilesIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
  src/test/java/edu/harvard/iq/dataverse/util/json/JsonPrinterTest.java
Labels: pm.GREI-d-2.7.1, pm.GREI-d-2.7.2, SPA

#10204 Make licenses searchable and facetable
  conf/solr/9.3.0/schema.xml
  doc/release-notes/9060-7482-make-licenses-searchable-faceatable.md
  src/main/java/edu/harvard/iq/dataverse/mydata/MyDataFinder.java
  src/main/java/edu/harvard/iq/dataverse/search/IndexServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/search/SearchFields.java
  src/main/java/edu/harvard/iq/dataverse/search/SearchIncludeFragment.java
  src/main/java/edu/harvard/iq/dataverse/search/SearchServiceBean.java
  src/main/java/propertyFiles/License.properties
  src/main/java/propertyFiles/staticSearchFields.properties
Labels: Feature: Terms & Licensing, Size: 3

#10306 Geospatial properties name fix
  conf/solr/9.3.0/schema.xml
  doc/release-notes/5645-geospatial-props-nslong-fix.md
  doc/sphinx-guides/source/api/changelog.rst
  scripts/api/data/dataset-create-new-all-default-fields.json
  scripts/api/data/metadatablocks/geospatial.tsv
  src/main/java/edu/harvard/iq/dataverse/DatasetFieldConstant.java
  src/main/java/edu/harvard/iq/dataverse/api/imports/ImportDDIServiceBean.java
  src/main/java/propertyFiles/geospatial.properties
  src/main/resources/db/migration/V6.1.0.3__5645-geospatial-fieldname-fix.sql
  src/test/java/edu/harvard/iq/dataverse/api/NetcdfIT.java
  src/test/java/edu/harvard/iq/dataverse/api/SearchIT.java
  src/test/java/edu/harvard/iq/dataverse/export/OpenAireExportUtilTest.java
  src/test/java/edu/harvard/iq/dataverse/export/dataset-all-defaults.txt
  src/test/java/edu/harvard/iq/dataverse/export/dataset-organizations-comma.txt
  src/test/java/edu/harvard/iq/dataverse/export/dataset-organizations.txt
  src/test/java/edu/harvard/iq/dataverse/export/dataset-simplified.txt
  src/test/java/edu/harvard/iq/dataverse/export/ddi/dataset-create-new-all-ddi-fields.json
  src/test/java/edu/harvard/iq/dataverse/export/ddi/dataset-finch1.json
  src/test/java/edu/harvard/iq/dataverse/util/json/JsonDatasetVersion.txt
  src/test/java/edu/harvard/iq/dataverse/util/json/jsondata.txt
Labels: Type: Bug, Size: 33

#10319 IQSS/10318 Uningest/Reingest UI
  doc/release-notes/10318-uningest-and-reingest.md
  doc/sphinx-guides/source/api/changelog.rst
  doc/sphinx-guides/source/api/native-api.rst
  doc/sphinx-guides/source/user/tabulardataingest/ingestprocess.rst
  src/main/java/edu/harvard/iq/dataverse/FilePage.java
  src/main/java/edu/harvard/iq/dataverse/api/Files.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/UningestFileCommand.java
  src/main/java/propertyFiles/Bundle.properties
  src/main/webapp/file-edit-button-fragment.xhtml
Labels: Size: 3
