Repository IQSS/dataverse, pull requests merged in 2024-06, with the labels that each got.

#9909 Allow merging of accounts that are members of the same group
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/MergeInAccountCommand.java
  src/test/java/edu/harvard/iq/dataverse/api/UsersIT.java
Labels: Type: Bug, Feature: Account & User Info, Size: 3

#10569 IQSS/10568-Fix File Reingest from UI
  doc/release-notes/10568-Fix File Reingest.md
  src/main/java/edu/harvard/iq/dataverse/FilePage.java
Labels: GDCC: QDR, Size: 3, GDCC: Borealis

#10555 avoid expensive Solr join for public dvObjects in search (experimental)
  doc/release-notes/10554-avoid-solr-join-guest.md
  doc/sphinx-guides/source/developers/performance.rst
  doc/sphinx-guides/source/installation/config.rst
  src/main/java/edu/harvard/iq/dataverse/search/IndexServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/search/SearchFields.java
  src/main/java/edu/harvard/iq/dataverse/search/SearchServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/settings/FeatureFlags.java
Labels: Feature: Search/Browse, Feature: Performance & Stability, Size: 30

#10328 OpenAPI definition endpoint
  .gitignore
  doc/release-notes/10236-openapi-definition-endpoint.md
  doc/sphinx-guides/source/api/changelog.rst
  doc/sphinx-guides/source/api/faq.rst
  doc/sphinx-guides/source/api/getting-started.rst
  doc/sphinx-guides/source/developers/api-design.rst
  pom.xml
  src/main/java/edu/harvard/iq/dataverse/api/Access.java
  src/main/java/edu/harvard/iq/dataverse/api/Admin.java
  src/main/java/edu/harvard/iq/dataverse/api/BuiltinUsers.java
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/main/java/edu/harvard/iq/dataverse/api/Files.java
  src/main/java/edu/harvard/iq/dataverse/api/Groups.java
  src/main/java/edu/harvard/iq/dataverse/api/Info.java
  src/main/java/edu/harvard/iq/dataverse/api/TestApi.java
  src/main/java/edu/harvard/iq/dataverse/api/Users.java
  src/main/java/edu/harvard/iq/dataverse/api/WorkflowsAdmin.java
  src/main/java/edu/harvard/iq/dataverse/openapi/OpenApi.java
  src/main/java/propertyFiles/Bundle.properties
  src/test/java/edu/harvard/iq/dataverse/api/InfoIT.java
  src/test/java/edu/harvard/iq/dataverse/api/OpenApiIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
  tests/integration-tests.txt
Labels: Feature: API, Type: Bug, Size: 30

#10596 mention Docker in main README, add docker/README.md, rm dummy Dockerfile
  Dockerfile
  README.md
  docker/README.md
Labels: Component: Containers

#10562 add 3DViewer by openforestdata.pl to list of external tools
  doc/release-notes/10561-3dviewer.md
  doc/sphinx-guides/source/_static/admin/dataverse-external-tools.tsv
Labels: Feature: Admin Guide, Feature: External Tool, Size: 0.5

#10602 #10466: quick fix for math challenge contact form on 403 error page
  doc/release-notes/10466-math-challenge-403-error-page.md
  src/main/java/edu/harvard/iq/dataverse/SendFeedbackDialog.java
Labels: Size: 0.5

#10474 API: Handling creation of duplicate role for a dataset object
  doc/release-notes/9729-release-notes.md
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/AssignRoleCommand.java
  src/main/java/propertyFiles/Bundle.properties
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
  src/test/java/edu/harvard/iq/dataverse/engine/command/impl/CreatePrivateUrlCommandTest.java
Labels: Feature: Permissions, Size: 3

#10547 Solr: Try Soft Commit on Indexing
  conf/solr/9.3.0/solrconfig.xml
  doc/release-notes/10547-solr-updates.md
  src/main/java/edu/harvard/iq/dataverse/search/IndexServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/search/SolrIndexServiceBean.java
  src/test/java/edu/harvard/iq/dataverse/api/DataversesIT.java
  src/test/java/edu/harvard/iq/dataverse/api/LinkIT.java
  src/test/java/edu/harvard/iq/dataverse/api/SearchIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
  src/test/java/edu/harvard/iq/dataverse/engine/command/impl/CreatePrivateUrlCommandTest.java
  src/test/java/edu/harvard/iq/dataverse/util/cache/CacheFactoryBeanTest.java
Labels: Size: 3

#10505 CVOC : Indexed field accuracy (Ontoportal integration)
  doc/release-notes/9276-doc-cvoc-index-in.md
  doc/sphinx-guides/source/admin/metadatacustomization.rst
  src/main/java/edu/harvard/iq/dataverse/DatasetFieldServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/search/IndexServiceBean.java
  src/test/java/edu/harvard/iq/dataverse/DatasetFieldServiceBeanTest.java
  src/test/resources/json/cvoc-agroportal.json
  src/test/resources/json/cvoc-orcid.json
  src/test/resources/json/cvoc-skosmos.json
Labels: Size: 10

#10371 10288 Add keywordTermURI metadata in keyword block
  conf/solr/9.3.0/schema.xml
  doc/release-notes/10288-add-term_uri-metadata-in-keyword-block.md
  scripts/api/data/dataset-create-new-all-default-fields.json
  scripts/api/data/metadatablocks/citation.tsv
  src/main/java/edu/harvard/iq/dataverse/DatasetFieldConstant.java
  src/main/java/edu/harvard/iq/dataverse/DatasetKeyword.java
  src/main/java/edu/harvard/iq/dataverse/export/openaire/OpenAireExportUtil.java
  src/main/java/propertyFiles/citation.properties
  src/test/java/edu/harvard/iq/dataverse/export/OpenAireExportUtilTest.java
  src/test/java/edu/harvard/iq/dataverse/export/SchemaDotOrgExporterTest.java
  src/test/java/edu/harvard/iq/dataverse/export/dataset-all-defaults.txt
  src/test/java/edu/harvard/iq/dataverse/export/ddi/dataset-create-new-all-ddi-fields.json
  src/test/java/edu/harvard/iq/dataverse/export/ddi/dataset-finch1.json
  src/test/resources/json/dataset-finch2.json
  src/test/resources/json/dataset-long-description.json
Labels: Size: 10

#10620 Deprecate rsync: remove from guides, mark code as deprecated
  doc/release-notes/8985-deprecate-rsync.md
  doc/sphinx-guides/source/_static/installation/files/root/big-data-support/checksumValidationSuccess.json
  doc/sphinx-guides/source/api/native-api.rst
  doc/sphinx-guides/source/developers/big-data-support.rst
  doc/sphinx-guides/source/installation/config.rst
  doc/sphinx-guides/source/user/dataset-management.rst
  doc/sphinx-guides/source/user/find-use-data.rst
  scripts/api/data/storageSites/add-storage-site.json
  src/main/java/edu/harvard/iq/dataverse/SettingsWrapper.java
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/main/java/edu/harvard/iq/dataverse/datacapturemodule/DataCaptureModuleException.java
  src/main/java/edu/harvard/iq/dataverse/datacapturemodule/DataCaptureModuleUtil.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/RequestRsyncScriptCommand.java
  src/main/java/edu/harvard/iq/dataverse/repositorystorageabstractionlayer/RepositoryStorageAbstractionLayerPage.java
  src/main/java/edu/harvard/iq/dataverse/repositorystorageabstractionlayer/RepositoryStorageAbstractionLayerUtil.java
  src/main/java/edu/harvard/iq/dataverse/settings/SettingsServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/util/SystemConfig.java
Labels: Component: Code Infrastructure, Feature: User Guide, Size: 0.5

#10565 Banner IT improvements after resolving issues on rocky.
  doc/release-notes/10565-banner-test-improvements.md
  doc/sphinx-guides/source/api/native-api.rst
  doc/sphinx-guides/source/developers/documentation.rst
  makefile
  src/main/java/edu/harvard/iq/dataverse/BannerMessage.java
  src/main/java/edu/harvard/iq/dataverse/BannerMessageServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/api/Admin.java
  src/test/java/edu/harvard/iq/dataverse/api/AdminIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: Size: 30

#10106 IQSS/10105 - fix guestbook preview on dataset page
  src/main/webapp/dataset-license-terms.xhtml
Labels: GDCC: QDR, Size: 3

#10640 Null banner JSON message fix
  src/main/java/edu/harvard/iq/dataverse/api/Admin.java
Labels: Size: 3

#10636 Upgrade Solr to 9.4.1
  conf/solr/schema.xml
  conf/solr/solrconfig.xml
  conf/solr/update-fields.sh
  doc/release-notes/solr-9.4.1.md
  doc/sphinx-guides/source/_static/installation/files/etc/init.d/solr
  doc/sphinx-guides/source/_static/installation/files/etc/systemd/solr.service
  doc/sphinx-guides/source/admin/metadatacustomization.rst
  doc/sphinx-guides/source/developers/classic-dev-env.rst
  doc/sphinx-guides/source/installation/prerequisites.rst
  docker/compose/demo/compose.yml
  modules/container-configbaker/assembly.xml
  modules/dataverse-parent/pom.xml
  scripts/installer/Makefile
  tests/shell/spec/update_fields_spec.sh
Labels: Size: 10

#10603 CVOC: Fix NPE
  src/main/java/edu/harvard/iq/dataverse/DatasetFieldServiceBean.java
Labels: Size: 3

#10610 Fix DOI/ID message when deaccession a Dataset
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
  src/test/java/edu/harvard/iq/dataverse/api/FilesIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: Feature: API, Type: Bug, User Role: API User, Size: 10

#10503 CVOC : Adding hidden metadata fields (Ontoportal integration)
  doc/release-notes/10503-cvoc-hidden-html-fields.md
  src/main/webapp/metadataFragment.xhtml
Labels: Size: 3

#10653 10581 request access email fix
  src/main/java/edu/harvard/iq/dataverse/GuestbookResponse.java
  src/main/java/edu/harvard/iq/dataverse/MailServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/util/MailUtil.java
  src/main/java/propertyFiles/Bundle.properties
  src/test/java/edu/harvard/iq/dataverse/util/MailUtilTest.java
Labels: Size: 3

#10654 IQSS/10559-2 Drop COMMIT_WITHIN which breaks autoSoftCommit by maxTime in solrconfig
  src/main/java/edu/harvard/iq/dataverse/search/IndexServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/search/SolrIndexServiceBean.java
Labels: Size: 3

#10651 Fixes an issue with search cards for harvested records
  doc/release-notes/10611-harvested-origin-facet.md
  doc/sphinx-guides/source/installation/config.rst
  src/main/java/edu/harvard/iq/dataverse/search/IndexServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/search/SearchServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/settings/FeatureFlags.java
Labels: Feature: Harvesting, Size: 3

#10295 Support additional Exporter MIME Types
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
Labels: Type: Feature, Size: 3

#10495 Upgrade to Payara 6.2024.6
  doc/release-notes/10494-payara-upgrade.md
  doc/sphinx-guides/source/admin/monitoring.rst
  doc/sphinx-guides/source/developers/classic-dev-env.rst
  doc/sphinx-guides/source/installation/prerequisites.rst
  doc/sphinx-guides/source/qa/test-automation.md
  modules/container-base/src/main/docker/Dockerfile
  modules/dataverse-parent/pom.xml
  pom.xml
  scripts/installer/as-setup.sh
Labels: Component: Code Infrastructure, Feature: Installer, Feature: Installation Guide, Component: Containers, Size: 3, Feature: Container Guide, FY24 Sprint 26

#10657 IQSS/10656-fix permission check for request access notifications/emails
  src/main/java/edu/harvard/iq/dataverse/FileDownloadServiceBean.java
Labels: GDCC: DANS, Size: 3

#10563 IQSS/10557-fix-installer-pid-setup
  scripts/installer/as-setup.sh
  src/main/java/edu/harvard/iq/dataverse/settings/ConfigCheckService.java
Labels: Size: 3

#10655 IQSS/10137-2 Add flag to remove Return To Author Reason
  doc/release-notes/10137-2-add-disable-reason-flag.md
  doc/sphinx-guides/source/api/native-api.rst
  doc/sphinx-guides/source/installation/config.rst
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/ReturnDatasetToAuthorCommand.java
  src/main/java/edu/harvard/iq/dataverse/settings/FeatureFlags.java
  src/main/java/propertyFiles/Bundle.properties
  src/main/webapp/dataset.xhtml
  src/test/java/edu/harvard/iq/dataverse/engine/command/impl/ReturnDatasetToAuthorCommandTest.java
Labels: Size: 3

#5506 IQSS-5505 - only update DOI metadata at PIDprovider when it changes
  pom.xml
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/UpdateDvObjectPIDMetadataCommand.java
  src/main/java/edu/harvard/iq/dataverse/pidproviders/AbstractPidProvider.java
  src/main/java/edu/harvard/iq/dataverse/pidproviders/PidProvider.java
  src/main/java/edu/harvard/iq/dataverse/pidproviders/doi/datacite/DOIDataCiteRegisterService.java
  src/main/java/edu/harvard/iq/dataverse/pidproviders/doi/datacite/DataCiteDOIProvider.java
Labels: Size: 10, GREI 2
