Repository IQSS/dataverse, pull requests merged in 2024-04, with the labels that each got.

#10443 #10442 fix null from template
  src/main/java/edu/harvard/iq/dataverse/search/IndexServiceBean.java
Labels: Size: 3

#10432 6.2 release notes
  doc/release-notes/10101-qa-guide.md
  doc/release-notes/10117-api-metrics-add-user-accounts-number.md
  doc/release-notes/10155-datasets-can-download-at-least-one-file.md
  doc/release-notes/10202-extend-getVersionFiles-api-to-include-total-file-count.md
  doc/release-notes/10216-metadatablocks.md
  doc/release-notes/10238-container-demo.md
  doc/release-notes/10240-file-citation.md
  doc/release-notes/10254-fix-harvested-redirects.md
  doc/release-notes/10280-get-file-api-extension.md
  doc/release-notes/10286-return-owner-added-to-get-apis.md
  doc/release-notes/10297-metadata-api-fix.md
  doc/release-notes/10318-uningest-and-reingest.md
  doc/release-notes/10338-expose-and-sort-publish-status-facet.md
  doc/release-notes/10342-assign-roles-without-privilege-escalation.md
  doc/release-notes/10360-binder-redirect.md
  doc/release-notes/10381-index-after-publish.md
  doc/release-notes/10382-optional-croissant-exporter.md
  doc/release-notes/10397-geospatial-tooltip-fix.md
  doc/release-notes/10424-new-api-for-mdc.md
  doc/release-notes/3437-new-index-api-added.md
  doc/release-notes/3623-multipid.md
  doc/release-notes/3702-return-to-author.md
  doc/release-notes/5645-geospatial-props-nslong-fix.md
  doc/release-notes/6.1-release-notes.md
  doc/release-notes/6.2-release-notes.md
  doc/release-notes/7424-mailsession.md
  doc/release-notes/8134-add-qpj-qmd-extensions.md
  doc/release-notes/8524-storing-tabular-files-with-varheaders.md
  doc/release-notes/9060-7482-make-licenses-searchable-faceatable.md
  doc/release-notes/9275-harvest-invalid-query-params.md
  doc/release-notes/9356-rate-limiting.md
  doc/release-notes/9590-faster-redeploy.md
  doc/release-notes/9728-universe-variablemetadata.md
  doc/release-notes/9920-postgres16.md
  doc/release-notes/9926-list-role-assignments-permissions.md
  doc/release-notes/9983-unique-constraints.md
  doc/release-notes/9992-harvest-metadata-values-not-in-cvv-list.md
Labels: Size: 10

#10354 Dataset version API change - Adds latestVersionPublishingStatus
  doc/release-notes/10330-api-change-latest-version-status.md
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/GetLatestAccessibleDatasetVersionCommand.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
Labels: User Role: API User, Size: 10, pm.GREI-d-2.7.1, pm.GREI-d-2.7.2, SPA, SPA: File Page

#10467 Explain that 5.6 introduced a breaking change to the create dataset API
  doc/sphinx-guides/source/api/changelog.rst
Labels: Size: 0.5

#10418 Extend the MetadataBlocks API endpoints for the Create Dataset Feature
  doc/release-notes/10389-metadatablocks-api-extension.md
  doc/sphinx-guides/source/api/native-api.rst
  scripts/api/data/metadatablocks/citation.tsv
  src/main/java/edu/harvard/iq/dataverse/Dataverse.java
  src/main/java/edu/harvard/iq/dataverse/EjbDataverseEngine.java
  src/main/java/edu/harvard/iq/dataverse/MetadataBlockServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/api/Dataverses.java
  src/main/java/edu/harvard/iq/dataverse/api/MetadataBlocks.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/CommandContext.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/ListMetadataBlocksCommand.java
  src/main/java/edu/harvard/iq/dataverse/util/json/BriefJsonPrinter.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java
  src/test/java/edu/harvard/iq/dataverse/api/DataversesIT.java
  src/test/java/edu/harvard/iq/dataverse/api/MetadataBlocksIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
  src/test/java/edu/harvard/iq/dataverse/engine/TestCommandContext.java
  src/test/java/edu/harvard/iq/dataverse/util/json/BriefJsonPrinterTest.java
Labels: User Role: API User, pm.GREI-d-2.7.1, pm.GREI-d-2.7.2, SPA

#10464 Add Harvesting Client name to the Metadata Source facet
  doc/release-notes/10464-add-name-harvesting-client-facet.md
  src/main/java/edu/harvard/iq/dataverse/search/IndexServiceBean.java
  src/test/java/edu/harvard/iq/dataverse/api/HarvestingClientsIT.java
Labels: Type: Feature, Size: 33

#10441 convert workflowCodeRepository field into a clickable link
  doc/release-notes/10339-workflow.md
  scripts/api/data/metadatablocks/computational_workflow.tsv
Labels: Size: 0.5

#9705 Prevent "DRAFT" from appearing in citation file downloaded from a published dataset
  src/main/java/edu/harvard/iq/dataverse/FileDownloadServiceBean.java
  src/main/webapp/dataset-citation.xhtml
  src/main/webapp/file.xhtml
Labels: Type: Bug, Size: 3

#10486 10441 - missed release note addition
  doc/release-notes/10339-workflow.md
Labels: Size: 0.5

#10449 Fix intermittent IT test failures for HarvestingClientsIT
  src/test/java/edu/harvard/iq/dataverse/api/HarvestingClientsIT.java
Labels: Size: 3

#10283 bump solrj per qqmyers to address zookeeper dependency
  pom.xml
Labels: Size: 3

#10310 10052 use try with resources to close fileinputstream gzippedin
  src/main/java/edu/harvard/iq/dataverse/util/FileUtil.java
  src/test/java/edu/harvard/iq/dataverse/util/FileUtilTest.java
  src/test/resources/fits/FOSy19g0309t_c2f.fits.gz
Labels: Feature: File Upload & Handling, Component: Code Infrastructure, Size: 3

#10029 disable s3 tagging JVM option
  doc/release-notes/10022_upload_redirect_without_tagging.md
  doc/sphinx-guides/source/api/native-api.rst
  doc/sphinx-guides/source/developers/big-data-support.rst
  doc/sphinx-guides/source/developers/s3-direct-upload-api.rst
  doc/sphinx-guides/source/installation/config.rst
  src/main/java/edu/harvard/iq/dataverse/dataaccess/S3AccessIO.java
  src/main/java/edu/harvard/iq/dataverse/settings/JvmSettings.java
  src/main/webapp/resources/js/fileupload.js
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: Size: 3

#10331 CVOC : add HTTP request headers (Ontoportal integration)
  doc/release-notes/10316_cvoc_http_headers.md
  doc/sphinx-guides/source/admin/metadatacustomization.rst
  doc/sphinx-guides/source/installation/config.rst
  src/main/java/edu/harvard/iq/dataverse/DatasetFieldServiceBean.java
  src/main/webapp/datasetFieldForEditFragment.xhtml
  src/main/webapp/metadataFragment.xhtml
  src/main/webapp/search-include-fragment.xhtml
  src/main/webapp/search/advanced.xhtml
  src/test/java/edu/harvard/iq/dataverse/api/SearchIT.java
Labels: Size: 3

#10440 API: deprecate toggle of superuser status in favor of new idempotent endpoint, update setup-all.sh
  doc/release-notes/9887-new-superuser-status-endpoint.md
  doc/sphinx-guides/source/api/changelog.rst
  doc/sphinx-guides/source/api/native-api.rst
  scripts/api/setup-all.sh
  src/main/java/edu/harvard/iq/dataverse/api/Admin.java
  src/test/java/edu/harvard/iq/dataverse/api/AdminIT.java
  src/test/java/edu/harvard/iq/dataverse/api/BagIT.java
  src/test/java/edu/harvard/iq/dataverse/api/RolesIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: Type: Feature, Feature: API, User Role: Sysadmin, Size: 0.5

#10451 IQSS/10450 - Fixes for Globus download (transfer out) and related info messages
  src/main/java/edu/harvard/iq/dataverse/DatasetPage.java
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/main/java/edu/harvard/iq/dataverse/globus/GlobusServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/util/URLTokenUtil.java
  src/main/java/propertyFiles/Bundle.properties
  src/main/webapp/dataset.xhtml
  src/main/webapp/filesFragment.xhtml
Labels: Size: 10, GREI 5

#10491 added isReleased to GET Dataverse reponse
  doc/release-notes/10491-add-isreleased-to-get-dataverse-response.md
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java
  src/test/java/edu/harvard/iq/dataverse/api/DataversesIT.java
Labels: Size: 10, pm.GREI-d-2.7.1, pm.GREI-d-2.7.2, SPA

#8995 Allow Dataset DOI in check permissions API request
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/api/AbstractApiBean.java
  src/main/java/edu/harvard/iq/dataverse/api/Admin.java
Labels: Type: Feature, Size: 3

#10182 docs: correct TRS JSON quotes
  doc/sphinx-guides/source/developers/big-data-support.rst
Labels: Size: 3

#10509 catch failures with tiff file thumbnail generation
  src/main/java/edu/harvard/iq/dataverse/DataFileServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/DatasetServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/ThumbnailServiceWrapper.java
  src/main/java/edu/harvard/iq/dataverse/api/DownloadInstanceWriter.java
  src/main/java/edu/harvard/iq/dataverse/dataaccess/DataAccess.java
  src/main/java/edu/harvard/iq/dataverse/dataaccess/ImageThumbConverter.java
  src/main/java/edu/harvard/iq/dataverse/dataset/DatasetUtil.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/UpdateDatasetThumbnailCommand.java
  src/main/java/propertyFiles/Bundle.properties
  src/test/java/edu/harvard/iq/dataverse/api/SearchIT.java
  src/test/java/edu/harvard/iq/dataverse/api/ThumbnailsIT.java
  src/test/java/edu/harvard/iq/dataverse/engine/command/impl/UpdateDatasetThumbnailCommandTest.java
  src/test/resources/images/bad.tiff
  src/test/resources/images/good.tiff
Labels: Type: Bug, Size: 30
