Repository IQSS/dataverse, pull requests merged in 2024-01, with the labels that each got.

#10191 return deaccessioned version of dataset in more cases
  doc/sphinx-guides/source/api/changelog.rst
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/GetLatestAccessibleDatasetVersionCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/GetLatestPublishedDatasetVersionCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/GetSpecificPublishedDatasetVersionCommand.java
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: Size: 10

#9927 support Postgres 16, bump Flyway
  doc/release-notes/9920-postgres16.md
  pom.xml
  scripts/installer/install.py
Labels: Size: 10

#10188 add "message sent" success message
  src/main/java/edu/harvard/iq/dataverse/SendFeedbackDialog.java
  src/main/java/propertyFiles/Bundle.properties
  src/main/webapp/contactFormFragment.xhtml
Labels: Size: 10

#10215 10202 extend get version files api to include total file count
  doc/release-notes/10202-extend-getVersionFiles-api-to-include-total-file-count.md
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/api/AbstractApiBean.java
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
Labels: User Role: API User, Size: 10, pm.GREI-d-2.7.1, pm.GREI-d-2.7.2, SPA

#10201 IQSS/10200 - Create dirs needed for Globus transfer to managed stores
  doc/sphinx-guides/source/developers/globus-api.rst
  src/main/java/edu/harvard/iq/dataverse/globus/GlobusServiceBean.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: HDC: 1, Size: 10

#9956 9926: list role assignments permissions
  doc/release-notes/9926-list-role-assignments-permissions.md
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/ListRoleAssignments.java
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
Labels: Feature: Permissions, User Role: API User, Size: 3

#10233 fix bad SQL query in guestbook #10232
  src/main/java/edu/harvard/iq/dataverse/GuestbookResponseServiceBean.java
Labels: Size: 3

#10205 OAI-PMH error handling: meaningful errors in XML for verb processing
  doc/release-notes/9275-harvest-invalid-query-params.md
  docker-compose-dev.yml
  src/main/java/edu/harvard/iq/dataverse/harvest/server/web/servlet/OAIServlet.java
  src/test/java/edu/harvard/iq/dataverse/api/HarvestingServerIT.java
Labels: Feature: Harvesting, Component: Containers, Size: 10

#10228 3322 Empty OAI sets should not be listed in ListSets
  src/main/java/edu/harvard/iq/dataverse/HarvestingSetsPage.java
  src/main/java/edu/harvard/iq/dataverse/harvest/server/OAISetServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/harvest/server/xoai/DataverseXoaiSetRepository.java
  src/main/java/propertyFiles/Bundle.properties
  src/test/java/edu/harvard/iq/dataverse/api/HarvestingServerIT.java
Labels: Size: 10

#9741 increase "universe" in variablemetadata table from varchar 255 to text
  doc/release-notes/9728-universe-variablemetadata.md
  src/main/java/edu/harvard/iq/dataverse/datavariable/VariableMetadata.java
  src/main/resources/db/migration/V5.13.0.3__9728-universe-variablemetadata.sql
Labels: Feature: Metadata, Size: 3

#9964 Always add validity field when indexing a dataset
  src/main/java/edu/harvard/iq/dataverse/search/IndexServiceBean.java
Labels: Feature: Metadata, Feature: My Data, Size: 3

#10225 Add displayOrder, typeClass and isRequired fields to DatasetFieldType payload
  doc/release-notes/10216-metadatablocks.md
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java
  src/test/java/edu/harvard/iq/dataverse/api/MetadataBlocksIT.java
Labels: Size: 3, pm.GREI-d-2.7.1, pm.GREI-d-2.7.2, SPA

#9941 #9940 - fixed various issues with generated urls of authors for signposting
  src/main/java/edu/harvard/iq/dataverse/util/SignpostingResources.java
Labels: Size: 3, Feature: Signposting

#10256 #10255 fix script name
  src/main/resources/db/migration/V6.1.0.1__9728-universe-variablemetadata.sql
Labels: Type: Bug, Size: 0.5

#10214 9686 move harvesting client
  doc/release-notes/9686-move-harvesting-client-id.md
  src/main/java/edu/harvard/iq/dataverse/Dataset.java
  src/main/java/edu/harvard/iq/dataverse/DatasetServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/DvObject.java
  src/main/java/edu/harvard/iq/dataverse/DvObjectServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/api/imports/ImportServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/harvest/client/HarvestingClientServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/metrics/MetricsServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/search/SearchIncludeFragment.java
  src/main/resources/db/migration/V6.1.0.2__9686-move-harvestingclient-id.sql
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
  src/test/java/edu/harvard/iq/dataverse/api/MetricsIT.java
Labels: Size: 33

#10247 Intellij IDEA webapp hotreload
  docker-compose-dev.yml
  scripts/intellij/cpwebapp.sh
  scripts/intellij/watchers.xml
Labels: Size: 3

#10264 IQSS/10251 fix for multifile downloads
  src/main/java/edu/harvard/iq/dataverse/FileDownloadServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/util/FileUtil.java
Labels: Size: 3

#10269 IQSS/10268 fix thumbnail selection logic
  src/main/java/edu/harvard/iq/dataverse/ThumbnailServiceWrapper.java
Labels: Size: 3

#10184 bump DuraCloud to 8.0.0
  pom.xml
Labels: Size: 0.5

#10183 bump htmlunit to 3.9.0
  pom.xml
Labels: Size: 0.5

#9963 assign role using email
  src/main/java/edu/harvard/iq/dataverse/authorization/users/AuthenticatedUser.java
  src/main/webapp/roles-assign.xhtml
Labels: Feature: Permissions, Size: 3

#10186 bump google.library.version to 26.30.0
  modules/dataverse-parent/pom.xml
  src/test/java/edu/harvard/iq/dataverse/api/SwordIT.java
Labels: Size: 0.5
