Repository IQSS/dataverse, pull requests merged in 2024-10, with the labels that each got.

#9665 improve the linked dataverse listing API
  doc/release-notes/9650-5-improve-list-linked-dataverses-API.md
  doc/sphinx-guides/source/admin/dataverses-datasets.rst
  doc/sphinx-guides/source/api/changelog.rst
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
  src/test/java/edu/harvard/iq/dataverse/api/MoveIT.java
Labels: Size: 3, FY25 Sprint 6, FY25 Sprint 7

#10901 Deaccessioned dataset file edit fix.
  doc/release-notes/10901deaccessioned file edit fix.md
  src/main/java/edu/harvard/iq/dataverse/Dataset.java
  src/main/java/edu/harvard/iq/dataverse/api/Files.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/UpdateDatasetVersionCommand.java
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
Labels: Type: Bug, Feature: Deaccession, Size: 30, FY25 Sprint 7

#10908 PR template: add hyphen to show issue title
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Size: 0.5

#10882 add isReleased field to isPartOf
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
Labels: Type: Feature, Size: 10, SPA, GREI Re-arch, SPA.Q3, FY25 Sprint 7, Original size: 10

#10075 Put modifiers in the correct order
  src/main/java/edu/harvard/iq/dataverse/DatasetFieldConstant.java
  src/main/java/edu/harvard/iq/dataverse/WidgetWrapper.java
  src/main/java/edu/harvard/iq/dataverse/authorization/providers/oauth2/AbstractOAuth2AuthenticationProvider.java
  src/main/java/edu/harvard/iq/dataverse/authorization/providers/oauth2/impl/OrcidOAuth2AP.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/DataverseRequest.java
  src/main/java/edu/harvard/iq/dataverse/util/ShapefileHandler.java
  src/main/java/edu/harvard/iq/dataverse/util/SystemConfig.java
  src/main/java/edu/harvard/iq/dataverse/validation/PasswordValidatorServiceBean.java
  src/test/java/edu/harvard/iq/dataverse/authorization/AuthenticationProviderTest.java
Labels: Type: Bug, Component: Code Infrastructure, Size: 0.5, FY25 Sprint 8

#10940 how to set up languages (English, French, etc.) in Docker
  doc/release-notes/10939-i18n-docker.md
  doc/sphinx-guides/source/container/running/demo.rst
  doc/sphinx-guides/source/installation/config.rst
  docker-compose-dev.yml
  docker/compose/demo/compose.yml
Labels: Component: Containers, Size: 3

#10948 Fixed typo tombstone in Bundle.properties
  src/main/java/propertyFiles/Bundle.properties
Labels: Type: Bug, Size: 0.5

#10921 #10920 fixing skomos typo
  doc/sphinx-guides/source/admin/metadatacustomization.rst
  src/main/java/edu/harvard/iq/dataverse/DatasetFieldServiceBean.java
Labels: Type: Bug, Size: 0.5

#10965 DatasetTypesIT- Fix for timing issue in test
  src/test/java/edu/harvard/iq/dataverse/api/DatasetTypesIT.java
Labels: Size: 0.5

#10301 Resolve conflicting version of MIME4J
  pom.xml
Labels: Type: Bug, GDCC: DANS, GDCC: QDR, Feature: Indexing, Size: 3, Consider For Next Release, FY25 Sprint 7, FY25 Sprint 8, FY25 Sprint 9

#10865 IQSS/10379 Fix Metrics API Bugs
  doc/release-notes/10379-MetricsBugsFixes.md
  src/main/java/edu/harvard/iq/dataverse/api/Metrics.java
  src/main/java/edu/harvard/iq/dataverse/metrics/MetricsServiceBean.java
Labels: Type: Bug, Size: 10, FY25 Sprint 6, FY25 Sprint 7, FY25 Sprint 8, FY25 Sprint 9

#10706 IQSS/10705: Refactor permission filter query in indexing
  src/main/java/edu/harvard/iq/dataverse/search/SearchServiceBean.java
Labels: Type: Bug, GDCC: QDR, Size: 3, Consider For Next Release, FY25 Sprint 7, FY25 Sprint 8, FY25 Sprint 9

#10836 10734 Refactoring and optimization of importing and reindexing of harvested content
  src/main/java/edu/harvard/iq/dataverse/api/imports/ImportServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/AbstractCreateDatasetCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/UpdateHarvestedDatasetCommand.java
  src/main/java/edu/harvard/iq/dataverse/search/IndexServiceBean.java
Labels: Type: Feature, Feature: Harvesting, Size: 30, FY25 Sprint 6, FY25 Sprint 7, FY25 Sprint 8, FY25 Sprint 9

#10886 Update the conditions to display image_url in Solr search results for file type
  doc/release-notes/10886-update-to-conditions-to-display-image_url.md
  src/main/java/edu/harvard/iq/dataverse/ThumbnailServiceWrapper.java
  src/test/java/edu/harvard/iq/dataverse/api/SearchIT.java
Labels: Type: Bug, Size: 10, SPA, GREI Re-arch, FY25 Sprint 7, Original size: 10, SPA.Q4, FY25 Sprint 8, FY25 Sprint 9

#10899 replace ZipInputStream with ZipFile
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/CreateNewDataFilesCommand.java
  src/main/java/edu/harvard/iq/dataverse/ingest/IngestServiceShapefileHelper.java
  src/main/java/edu/harvard/iq/dataverse/util/FileUtil.java
  src/main/java/edu/harvard/iq/dataverse/util/ShapefileHandler.java
  src/test/java/edu/harvard/iq/dataverse/engine/command/impl/CreateNewDataFilesTest.java
  src/test/java/edu/harvard/iq/dataverse/util/shapefile/ShapefileHandlerTest.java
  src/test/resources/own-cloud-downloads/greetings.zip
  src/test/resources/own-cloud-downloads/shapes.zip
Labels: Type: Bug, Size: 3, FY25 Sprint 7, FY25 Sprint 8, FY25 Sprint 9

#10958 Fixes updateAttributes endpoint
  src/main/java/edu/harvard/iq/dataverse/api/Dataverses.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/UpdateDataverseAttributeCommand.java
  src/test/java/edu/harvard/iq/dataverse/api/DataversesIT.java
Labels: Type: Bug, Size: 3, SPA, GREI Re-arch, Original size: 10, SPA.Q4, FY25 Sprint 8, FY25 Sprint 9

#10967 Update to #10705 fixing a blank filter query
  src/main/java/edu/harvard/iq/dataverse/search/SearchServiceBean.java
Labels: Size: 0.5

#10708 QDR: PID bug fixes
  doc/release-notes/10708 - MDC Citation and DOI parsing improvements.md
  src/main/java/edu/harvard/iq/dataverse/api/MakeDataCountApi.java
  src/main/java/edu/harvard/iq/dataverse/makedatacount/DatasetExternalCitationsServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/pidproviders/AbstractPidProvider.java
  src/main/java/edu/harvard/iq/dataverse/pidproviders/doi/AbstractDOIProvider.java
  src/main/java/edu/harvard/iq/dataverse/pidproviders/doi/datacite/DataCiteDOIProvider.java
  src/test/java/edu/harvard/iq/dataverse/pidproviders/PidUtilTest.java
Labels: Type: Bug, GDCC: QDR, Size: 3, Consider For Next Release, FY25 Sprint 7, FY25 Sprint 8, FY25 Sprint 9

#10974 fix get major version when deaccessioned
  doc/release-notes/10947-unpublished-files-appearing-in-search-results-for-anon-user.md
  src/main/java/edu/harvard/iq/dataverse/Dataset.java
  src/test/java/edu/harvard/iq/dataverse/DatasetTest.java
Labels: Type: Bug, Size: 10, FY25 Sprint 9

#10991 Update FeatureFlags apiNotes
  src/main/java/edu/harvard/iq/dataverse/settings/FeatureFlags.java
Labels: Size: 0.5

#10219 OdumInstitute is now UNCCH-RDMC
  .github/workflows/guides_build_sphinx.yml
  doc/sphinx-guides/source/developers/version-control.rst
Labels: Type: Bug, Size: 0.5, FY25 Sprint 8, FY25 Sprint 9
