Repository IQSS/dataverse, pull requests merged in 2024-03, with the labels that each got.

#10305 Add .qpj and .qmd Extensions to Shapefile Handling #8134
  doc/release-notes/8134-add-qpj-qmd-extensions.md
  doc/sphinx-guides/source/developers/geospatial.rst
  src/main/java/edu/harvard/iq/dataverse/util/ShapefileHandler.java
  src/test/java/edu/harvard/iq/dataverse/util/shapefile/ShapefileHandlerTest.java
Labels: Type: Bug, User Role: Depositor, Feature: Geospatial, Size: 10, NIH CAFE

#10260 10177 api metrics add user accounts number
  doc/release-notes/10117-api-metrics-add-user-accounts-number.md
  doc/sphinx-guides/source/api/metrics.rst
  src/main/java/edu/harvard/iq/dataverse/api/Metrics.java
  src/main/java/edu/harvard/iq/dataverse/metrics/MetricsServiceBean.java
  src/test/java/edu/harvard/iq/dataverse/api/MetricsIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: Feature: Metrics + Reports, Size: 3

#10342 assign roles without privilege escalation
  doc/release-notes/10342-assign-roles-without-privilege-escalation.md
  doc/sphinx-guides/source/user/dataset-management.rst
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/AssignRoleCommand.java
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
Labels: Size: 3

#10275 OIDC state algorithm update
  src/main/java/edu/harvard/iq/dataverse/util/StringUtil.java
Labels: GDCC: QDR, Size: 3

#10366 Fixing the null-unsafe bug in JsonPrinter #10365
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java
Labels: Size: 3

#10345 Globus Bug Fixes
  doc/sphinx-guides/source/developers/globus-api.rst
  doc/sphinx-guides/source/developers/s3-direct-upload-api.rst
  src/main/java/edu/harvard/iq/dataverse/DatasetPage.java
  src/main/java/edu/harvard/iq/dataverse/FileDownloadHelper.java
  src/main/java/edu/harvard/iq/dataverse/FilePage.java
  src/main/java/edu/harvard/iq/dataverse/SettingsWrapper.java
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/main/java/edu/harvard/iq/dataverse/dataaccess/AbstractRemoteOverlayAccessIO.java
  src/main/java/edu/harvard/iq/dataverse/dataaccess/GlobusOverlayAccessIO.java
  src/main/java/edu/harvard/iq/dataverse/dataaccess/StorageIO.java
  src/main/java/edu/harvard/iq/dataverse/externaltools/ExternalTool.java
  src/main/java/edu/harvard/iq/dataverse/externaltools/ExternalToolServiceBean.java
  src/test/java/edu/harvard/iq/dataverse/externaltools/ExternalToolServiceBeanTest.java
Labels: Size: 3

#10374 GlobalDataverseCommunityConsortium:IQSS/10369-support_legacy_PID_provider_settings
  src/main/java/edu/harvard/iq/dataverse/pidproviders/PidProviderFactoryBean.java
Labels: Size: 3

#10323 Add harvesting feature to handle missing controlled values
  doc/release-notes/9992-harvest-metadata-values-not-in-cvv-list.md
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/DatasetField.java
  src/main/java/edu/harvard/iq/dataverse/harvest/client/HarvestingClient.java
  src/main/java/edu/harvard/iq/dataverse/search/IndexServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonParser.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java
  src/main/resources/db/migration/V6.1.0.6.sql
  src/test/java/edu/harvard/iq/dataverse/api/HarvestingClientsIT.java
Labels: Type: Feature, Feature: Harvesting, User Role: Depositor, Size: 33, pm.GREI-d-2.4.1B

#10211 adding rate limiting for command engine
  doc/release-notes/9356-rate-limiting.md
  doc/sphinx-guides/source/_static/installation/files/examples/rate-limit-actions-setting.json
  doc/sphinx-guides/source/installation/config.rst
  pom.xml
  src/main/java/edu/harvard/iq/dataverse/DatasetPage.java
  src/main/java/edu/harvard/iq/dataverse/DataversePage.java
  src/main/java/edu/harvard/iq/dataverse/EjbDataverseEngine.java
  src/main/java/edu/harvard/iq/dataverse/UserServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/api/AbstractApiBean.java
  src/main/java/edu/harvard/iq/dataverse/authorization/users/AuthenticatedUser.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/exception/RateLimitCommandException.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/CheckRateLimitForCollectionPage.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/CheckRateLimitForDatasetPage.java
  src/main/java/edu/harvard/iq/dataverse/settings/SettingsServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/util/SystemConfig.java
  src/main/java/edu/harvard/iq/dataverse/util/cache/CacheFactoryBean.java
  src/main/java/edu/harvard/iq/dataverse/util/cache/RateLimitSetting.java
  src/main/java/edu/harvard/iq/dataverse/util/cache/RateLimitUtil.java
  src/main/java/propertyFiles/Bundle.properties
  src/main/resources/db/migration/V6.1.0.7.sql
  src/test/java/edu/harvard/iq/dataverse/util/cache/CacheFactoryBeanTest.java
  src/test/java/edu/harvard/iq/dataverse/util/cache/RateLimitUtilTest.java
Labels: Size: 10, D: FixRateLimitingBehaviors

#10377 Doc Update: Fix old DataCite 3.1 reference
  doc/sphinx-guides/source/user/appendix.rst
Labels: Size: 0.5

#10401 Fix files not uploading when there is a required selectone component
  src/main/webapp/metadataFragment.xhtml
Labels: Size: 3

#10382 Allow optional Croissant exporter to replace JSON-LD <head> content
  doc/release-notes/10382-optional-croissant-exporter.md
  docker-compose-dev.yml
  src/main/java/edu/harvard/iq/dataverse/DatasetPage.java
  src/main/webapp/dataset.xhtml
Labels: Feature: Metadata, Size: 10, NIH CAFE

#10410 clarify how to increase timeout in docker demo
  doc/sphinx-guides/source/container/running/demo.rst
  docker/compose/demo/compose.yml
Labels: Component: Containers, Size: 0.5

#10414 Downgrade configbaker to Alpine 3.18
  modules/container-configbaker/Dockerfile
Labels: Component: Containers, Size: 0.5

#10408 Fix PUBLICATION_STATUS facet order and visibility
  doc/release-notes/10338-expose-and-sort-publish-status-facet.md
  src/main/java/edu/harvard/iq/dataverse/search/SearchServiceBean.java
Labels: Size: 3

#10380 Update Flyway docs to shorten SQL script filenames to prevent conflicts
  doc/sphinx-guides/source/developers/sql-upgrade-scripts.rst
Labels: Size: 0.5

#9939 Enable mail MTA configuration using MicroProfile Config
  doc/release-notes/7424-mailsession.md
  doc/sphinx-guides/source/container/app-image.rst
  doc/sphinx-guides/source/installation/config.rst
  doc/sphinx-guides/source/installation/installation-main.rst
  docker-compose-dev.yml
  docker/compose/demo/compose.yml
  modules/container-configbaker/scripts/bootstrap/dev/init.sh
  modules/dataverse-parent/pom.xml
  pom.xml
  scripts/installer/as-setup.sh
  scripts/installer/install.py
  scripts/installer/installAppServer.py
  src/main/docker/scripts/init_2_configure.sh
  src/main/java/edu/harvard/iq/dataverse/MailServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/SendFeedbackDialog.java
  src/main/java/edu/harvard/iq/dataverse/SettingsWrapper.java
  src/main/java/edu/harvard/iq/dataverse/api/FeedbackApi.java
  src/main/java/edu/harvard/iq/dataverse/harvest/server/web/servlet/OAIServlet.java
  src/main/java/edu/harvard/iq/dataverse/settings/ConfigCheckService.java
  src/main/java/edu/harvard/iq/dataverse/settings/JvmSettings.java
  src/main/java/edu/harvard/iq/dataverse/settings/SettingsServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/util/MailSessionProducer.java
  src/main/java/edu/harvard/iq/dataverse/util/MailUtil.java
  src/main/java/edu/harvard/iq/dataverse/validation/EMailValidator.java
  src/main/resources/META-INF/javamail.default.address.map
  src/main/resources/META-INF/microprofile-config.properties
  src/test/java/edu/harvard/iq/dataverse/MailServiceBeanIT.java
  src/test/java/edu/harvard/iq/dataverse/MailServiceBeanTest.java
  src/test/java/edu/harvard/iq/dataverse/branding/BrandingUtilTest.java
  src/test/java/edu/harvard/iq/dataverse/util/MailSessionProducerIT.java
  src/test/java/edu/harvard/iq/dataverse/util/MailUtilTest.java
  src/test/java/edu/harvard/iq/dataverse/validation/EMailValidatorTest.java
  src/test/resources/mail/cert.pem
  src/test/resources/mail/key.pem
Labels: Feature: Email Dataset Contact, Component: Containers, Size: 10, Feature: Container Guide

#10373 log file with a different instance root directory
  .gitignore
  src/main/java/edu/harvard/iq/dataverse/DatasetServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/api/BatchServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/authorization/AuthFilter.java
  src/main/java/edu/harvard/iq/dataverse/globus/GlobusServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/harvest/client/HarvesterServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/harvest/server/OAISetServiceBean.java
Labels: Component: Containers, Size: 3

#10391 IQSS 10390: Multipid UI Fix
  src/main/java/edu/harvard/iq/dataverse/DataversePage.java
  src/main/java/edu/harvard/iq/dataverse/DvObjectContainer.java
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/main/java/propertyFiles/Bundle.properties
  src/test/java/edu/harvard/iq/dataverse/pidproviders/PidUtilTest.java
Labels: Size: 3

#10416 fixing bug with tabs in log line for MDC
  src/main/java/edu/harvard/iq/dataverse/makedatacount/MakeDataCountLoggingServiceBean.java
  src/test/java/edu/harvard/iq/dataverse/makedatacount/MakeDataCountLoggingServiceBeanTest.java
Labels: NIH OTA: 1.5.1, Size: 3, pm.GREI-d-1.5.1, pm.GREI-d-1.5.2

#10436 Rate Limiting docs: shorten heading, other tweaks
  doc/sphinx-guides/source/installation/config.rst
Labels: Size: 3

#10424 adding api for new mdc processing state db table
  doc/release-notes/10424-new-api-for-mdc.md
  doc/sphinx-guides/source/developers/make-data-count.rst
  src/main/java/edu/harvard/iq/dataverse/api/MakeDataCountApi.java
  src/main/java/edu/harvard/iq/dataverse/makedatacount/MakeDataCountProcessState.java
  src/main/java/edu/harvard/iq/dataverse/makedatacount/MakeDataCountProcessStateServiceBean.java
  src/test/java/edu/harvard/iq/dataverse/api/MakeDataCountApiIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: pm.GREI-d-1.5.1, pm.GREI-d-1.5.2, Size: 0.5

#10430 10254 fixing redirects for records harvested from "Generic OAI archives" (i.e., non-Dataverse OAI servers)
  doc/release-notes/10254-fix-harvested-redirects.md
  src/main/java/edu/harvard/iq/dataverse/Dataset.java
  src/main/java/edu/harvard/iq/dataverse/DatasetPage.java
Labels: Feature: Harvesting, Size: 3

#10444 fix bad curl url in doc
  doc/sphinx-guides/source/developers/make-data-count.rst
Labels: Size: 0.5

#10447 Geospatial tooltip updated
  doc/release-notes/10397-geospatial-tooltip-fix.md
  scripts/api/data/metadatablocks/geospatial.tsv
  src/main/java/propertyFiles/geospatial.properties
Labels: Size: 0.5
