Repository IQSS/dataverse, pull requests merged in 2024-05, with the labels that each got.

#10170 Fixed forgotten code to make localeStrValue of CVV depends on :MetadataLanguages
  src/main/webapp/metadataFragment.xhtml
Labels: Size: 3

#10016 RO-Crate metadata mime type detection
  doc/release-notes/10015-RO-Crate-metadata-file.md
  src/main/java/edu/harvard/iq/dataverse/util/FileUtil.java
  src/main/java/propertyFiles/MimeTypeDetectionByFileName.properties
  src/main/java/propertyFiles/MimeTypeDisplay.properties
  src/main/java/propertyFiles/MimeTypeFacets.properties
  src/test/java/edu/harvard/iq/dataverse/util/FileUtilTest.java
Labels: Size: 3, GREI 3

#10524 provide guidance to Java devs on wildcard imports
  doc/sphinx-guides/source/developers/coding-style.rst
Labels: Size: 0.5

#9735 #8655 Re-add value 'cell counting' to Life Science metadatablock's Measurement Type field vocabulary
  doc/release-notes/8655-re-add-cell-counting-biomedical-tsv.md
  scripts/api/data/metadatablocks/biomedical.tsv
Labels: Size: 3

#10426 Add MIT license file and guidance for more license files
  doc/release-notes/10425-add-MIT-License.md
  doc/sphinx-guides/source/installation/config.rst
  scripts/api/data/licenses/licenseApache-2.0.json
  scripts/api/data/licenses/licenseMIT.json
Labels: Type: Feature, Size: 3, GREI 6

#10321 Support sitemaps with more than 50,000 items
  doc/release-notes/8936-more-than-50000-entries-in-sitemap.md
  doc/sphinx-guides/source/installation/config.rst
  pom.xml
  src/main/java/edu/harvard/iq/dataverse/sitemap/SiteMapUtil.java
  src/main/webapp/WEB-INF/pretty-config.xml
  src/test/java/edu/harvard/iq/dataverse/sitemap/SiteMapUtilTest.java
Labels: Type: Feature, Size: 10

#9581 fix: NullPointerExceptions in /api/mydata/retrieve
  src/main/java/edu/harvard/iq/dataverse/mydata/DataRetrieverAPI.java
  src/main/java/edu/harvard/iq/dataverse/search/SolrSearchResult.java
  src/test/java/edu/harvard/iq/dataverse/api/DataRetrieverApiIT.java
  tests/integration-tests.txt
Labels: Size: 3

#10090 Add audio/vnd.wave to mime type files
  src/main/java/propertyFiles/MimeTypeDisplay.properties
  src/main/java/propertyFiles/MimeTypeFacets.properties
Labels: Size: 3

#10135 6630 lastlogintime not updated
  src/main/java/edu/harvard/iq/dataverse/Shib.java
  src/main/java/edu/harvard/iq/dataverse/authorization/AuthenticationServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/authorization/providers/oauth2/OAuth2LoginBackingBean.java
  src/test/java/edu/harvard/iq/dataverse/authorization/providers/oauth2/OAuth2LoginBackingBeanTest.java
Labels: Size: 3

#10560 Added a note to remind people to update the languages
  doc/release-notes/6.2-release-notes.md
Labels: Type: Bug, Size: 0.5

#10172 10116 incomplete matadata label setting
  doc/release-notes/10116-incomplete-metadata-label-setting.md
  doc/sphinx-guides/source/installation/config.rst
  src/main/java/edu/harvard/iq/dataverse/DatasetPage.java
  src/main/java/edu/harvard/iq/dataverse/DatasetVersion.java
  src/main/java/edu/harvard/iq/dataverse/FilePage.java
  src/main/java/edu/harvard/iq/dataverse/mydata/DataRetrieverAPI.java
  src/main/java/edu/harvard/iq/dataverse/mydata/MyDataFilterParams.java
  src/main/java/edu/harvard/iq/dataverse/search/IndexServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/search/SearchIncludeFragment.java
  src/main/java/edu/harvard/iq/dataverse/search/SolrSearchResult.java
  src/main/java/edu/harvard/iq/dataverse/settings/JvmSettings.java
  src/main/webapp/file.xhtml
Labels: Size: 3

#9750 #9739 - URLValidator now allows two slashes in the path component of the URL
  doc/release-notes/9739-url-validator.md
  src/main/java/edu/harvard/iq/dataverse/validation/URLValidator.java
  src/test/java/edu/harvard/iq/dataverse/validation/URLValidatorTest.java
Labels: Size: 3

#10404 CVOC : allow flexible params in retrievalUri (Ontoportal integration)
  doc/release-notes/9276-allow-flexible-params-in-retrievaluri-cvoc.md
  src/main/java/edu/harvard/iq/dataverse/DatasetFieldServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/DatasetPage.java
  src/main/java/edu/harvard/iq/dataverse/EjbDataverseEngine.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/CommandContext.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/AbstractCreateDatasetCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/AbstractDatasetCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/CreateDatasetVersionCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/UpdateDatasetVersionCommand.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JSONLDUtil.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonParser.java
  src/test/java/edu/harvard/iq/dataverse/engine/TestCommandContext.java
Labels: Size: 3

#9786 Remove hard-coded English strings from MyData API
  src/main/java/edu/harvard/iq/dataverse/mydata/DataRetrieverAPI.java
  src/main/java/edu/harvard/iq/dataverse/mydata/MyDataFilterParams.java
  src/main/java/edu/harvard/iq/dataverse/mydata/MyDataFinder.java
  src/main/java/propertyFiles/Bundle.properties
  src/test/java/edu/harvard/iq/dataverse/api/DataRetrieverApiIT.java
Labels: Type: Bug, Feature: Internationalization, Size: 3

#9413 Add JProfiler acknowledgement for free license
  doc/sphinx-guides/source/developers/tools.rst
Labels: Feature: Developer Guide, Size: 0.5

#10079 Read zip file in try-with-resources
  src/main/java/edu/harvard/iq/dataverse/api/DatasetFieldServiceApi.java
Labels: Component: Code Infrastructure, Size: 3

#10571 Test fix for confirmEmail test failure
  src/main/java/edu/harvard/iq/dataverse/search/SearchIncludeFragment.java
Labels: Size: 3

#9684 Faster combined query for retrieving datasets via API
  src/main/java/edu/harvard/iq/dataverse/DatasetServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/api/AbstractApiBean.java
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
Labels: Type: Feature, Component: Code Infrastructure, Feature: Performance & Stability, Size: 3

#5621 use dataset thumbnail if available
  doc/release-notes/5621_dataset image in header.md
  src/main/webapp/dataset.xhtml
Labels: Size: 3
