Repository IQSS/dataverse, pull requests merged in 2024-12, with the labels that each got.

#11016 API for auditing physical files and file metadata
  doc/release-notes/220-harvard-edu-audit-files.md
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/api/Admin.java
  src/main/java/edu/harvard/iq/dataverse/dataaccess/S3AccessIO.java
  src/test/java/edu/harvard/iq/dataverse/api/AdminIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: Type: Feature, Original size: 30, FY25 Sprint 10, FY25 Sprint 11

#11040 10977 Globus Upload optimization - batch file size lookups
  doc/release-notes/10977-globus-filesize-lookup.md
  doc/sphinx-guides/source/installation/config.rst
  src/main/java/edu/harvard/iq/dataverse/MailServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/dataaccess/GlobusOverlayAccessIO.java
  src/main/java/edu/harvard/iq/dataverse/datasetutility/AddReplaceFileHelper.java
  src/main/java/edu/harvard/iq/dataverse/datasetutility/OptionalFileParams.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/CreateNewDataFilesCommand.java
  src/main/java/edu/harvard/iq/dataverse/globus/GlobusServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/ingest/IngestServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/settings/SettingsServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/util/SystemConfig.java
  src/main/java/propertyFiles/Bundle.properties
Labels: GREI 5, FY25 Sprint 10, FY25 Sprint 11

#10696 Added whitespace trimming to uploaded custom metadata TSV files
  doc/release-notes/10688_whitespace_trimming.md
  src/main/java/edu/harvard/iq/dataverse/api/DatasetFieldServiceApi.java
  src/test/java/edu/harvard/iq/dataverse/api/DatasetFieldServiceApiTest.java
  src/test/resources/tsv/whitespace-test.tsv
Labels: Type: Feature, Size: 3, FY25 Sprint 10

#11052 11044 edit facet bug
  src/main/java/edu/harvard/iq/dataverse/DataverseFacetServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/AbstractWriteDataverseCommand.java
Labels: Size: 3, FY25 Sprint 11

#11063 comment out /dv/lang to prevent verbose logging
  doc/sphinx-guides/source/container/running/demo.rst
  docker-compose-dev.yml
  docker/compose/demo/compose.yml
Labels: Feature: Internationalization, Component: Containers, Size: 0.5, FY25 Sprint 11, FY25 Sprint 12

#11070 changes made in #9665 belong in API changelog for 6.5, not 6.4
  doc/sphinx-guides/source/admin/dataverses-datasets.rst
  doc/sphinx-guides/source/api/changelog.rst
Labels: Feature: API Guide, Size: 0.5, FY25 Sprint 12

#11080 #11076 Allow User with View Unpublished Dataset Perms to access Preview URL without becoming Preview URL User
  src/main/java/edu/harvard/iq/dataverse/privateurl/PrivateUrlPage.java
  src/main/webapp/dataset.xhtml
Labels: Size: 3, FY25 Sprint 12

#11034 Display overview fix (external controlled vocabulary)
  doc/release-notes/display_overview_fix.md
  src/main/webapp/metadataFragment.xhtml
Labels: Type: Bug, Size: 3, FY25 Sprint 10, FY25 Sprint 11, FY25 Sprint 12

#11067 6.5 release notes
  doc/release-notes/10117-guestbook-question-size-limit-raised.md
  doc/release-notes/10379-MetricsBugsFixes.md
  doc/release-notes/10661-guestbook-email-bug-fix.md
  doc/release-notes/10688_whitespace_trimming.md
  doc/release-notes/10697-improve-permission-indexing.md
  doc/release-notes/10708 - MDC Citation and DOI parsing improvements.md
  doc/release-notes/10742-newest-oldest-sort-order-backwards.md
  doc/release-notes/10772-fix-importDDI-otherId.md
  doc/release-notes/10793-optimisticlockexception handling.md
  doc/release-notes/10814-Differencing improvement.md
  doc/release-notes/10837-exclude-others-ns-harvesting-oai-dc.md
  doc/release-notes/10857-add-expiration-date-to-recreate-token-api.md
  doc/release-notes/10886-update-to-conditions-to-display-image_url.md
  doc/release-notes/10888-add-api-for-comparing-dataset-versions.md
  doc/release-notes/10889_bump_PG17_FlyWay10.md
  doc/release-notes/10901deaccessioned file edit fix.md
  doc/release-notes/10904-edit-dataverse-collection-endpoint.md
  doc/release-notes/10914-users-token-api-credentials.md
  doc/release-notes/10919-minor-DataCiteXML-bugfix.md
  doc/release-notes/10939-i18n-docker.md
  doc/release-notes/10947-unpublished-files-appearing-in-search-results-for-anon-user.md
  doc/release-notes/10969-order-subfields-version-difference.md
  doc/release-notes/10977-globus-filesize-lookup.md
  doc/release-notes/11012-get-dataverse-api-ext.md
  doc/release-notes/11018-update-dataverse-endpoint-update.md
  doc/release-notes/11049-oai-identifiers-as-pids.md
  doc/release-notes/220-harvard-edu-audit-files.md
  doc/release-notes/6.5-release-notes.md
  doc/release-notes/7239-mydata-results-by-username.md
  doc/release-notes/8184-rename-private-url.md
  doc/release-notes/8941-adding-fileCount-in-solr.md
  doc/release-notes/9408-fix-facets-labels-not-translated-in-result-block.md
  doc/release-notes/9650-5-improve-list-linked-dataverses-API.md
  doc/release-notes/display_overview_fix.md
  doc/release-notes/expose-export-formats.md
Labels: Size: 10, FY25 Sprint 12

#11091 bump to 6.5
  doc/sphinx-guides/source/conf.py
  doc/sphinx-guides/source/versions.rst
  modules/dataverse-parent/pom.xml
Labels: Size: 10, Release, FY25 Sprint 12

#9251 add check to look for updates to Github actions being used
  .github/dependabot.yml
Labels: Type: Feature, Size: 3, FY25 Sprint 11, FY25 Sprint 12

#7636 Exclusions to remove module/classpath warnings
  pom.xml
Labels: Type: Bug, Size: 10, FY25 Sprint 10, FY25 Sprint 11, FY25 Sprint 12

#10972 Handle unregistered users in BearerTokenAuthMechanism and implement user registration mechanism
  conf/keycloak/test-realm.json
  doc/release-notes/10959-oidc-api-auth-ext.md
  doc/sphinx-guides/source/api/auth.rst
  doc/sphinx-guides/source/installation/config.rst
  docker-compose-dev.yml
  src/main/java/edu/harvard/iq/dataverse/api/AbstractApiBean.java
  src/main/java/edu/harvard/iq/dataverse/api/Users.java
  src/main/java/edu/harvard/iq/dataverse/api/auth/ApiKeyAuthMechanism.java
  src/main/java/edu/harvard/iq/dataverse/api/auth/AuthUtil.java
  src/main/java/edu/harvard/iq/dataverse/api/auth/BearerTokenAuthMechanism.java
  src/main/java/edu/harvard/iq/dataverse/api/auth/CompoundAuthMechanism.java
  src/main/java/edu/harvard/iq/dataverse/api/auth/SignedUrlAuthMechanism.java
  src/main/java/edu/harvard/iq/dataverse/api/auth/WorkflowKeyAuthMechanism.java
  src/main/java/edu/harvard/iq/dataverse/api/auth/WrappedAuthErrorResponse.java
  src/main/java/edu/harvard/iq/dataverse/api/auth/WrappedForbiddenAuthErrorResponse.java
  src/main/java/edu/harvard/iq/dataverse/api/auth/WrappedUnauthorizedAuthErrorResponse.java
  src/main/java/edu/harvard/iq/dataverse/api/dto/UserDTO.java
  src/main/java/edu/harvard/iq/dataverse/authorization/AuthenticationServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/authorization/providers/oauth2/oidc/OIDCAuthProvider.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/exception/InvalidFieldsCommandException.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/exception/PermissionException.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/RegisterOIDCUserCommand.java
  src/main/java/edu/harvard/iq/dataverse/settings/FeatureFlags.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonParser.java
  src/main/java/propertyFiles/Bundle.properties
  src/test/java/edu/harvard/iq/dataverse/api/UsersIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
  src/test/java/edu/harvard/iq/dataverse/api/auth/ApiKeyAuthMechanismTest.java
  src/test/java/edu/harvard/iq/dataverse/api/auth/BearerTokenAuthMechanismTest.java
  src/test/java/edu/harvard/iq/dataverse/api/auth/SignedUrlAuthMechanismTest.java
  src/test/java/edu/harvard/iq/dataverse/api/auth/WorkflowKeyAuthMechanismTest.java
  src/test/java/edu/harvard/iq/dataverse/authorization/AuthenticationServiceBeanTest.java
  src/test/java/edu/harvard/iq/dataverse/authorization/providers/oauth2/oidc/OIDCAuthenticationProviderFactoryIT.java
  src/test/java/edu/harvard/iq/dataverse/engine/command/impl/RegisterOIDCUserCommandTest.java
Labels: User Role: API User, Size: 30, SPA, GREI Re-arch, Original size: 30, SPA.Q4.4, FY25 Sprint 10, FY25 Sprint 11, FY25 Sprint 12

#11082 include total_count_per_object_type in search response
  doc/release-notes/ 11065-extend-search-api-to-include-type-counts.md
  doc/sphinx-guides/source/api/search.rst
  src/main/java/edu/harvard/iq/dataverse/api/Search.java
  src/test/java/edu/harvard/iq/dataverse/api/SearchIT.java
Labels: Type: Feature, Size: 10, SPA, GREI Re-arch, SPA.Q4.1, FY25 Sprint 12

#11097 extended search API
  conf/solr/schema.xml
  doc/release-notes/11027-extend-datasets-files-from-search-api.md
  src/main/java/edu/harvard/iq/dataverse/search/IndexServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/search/SearchFields.java
  src/main/java/edu/harvard/iq/dataverse/search/SearchServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/search/SolrSearchResult.java
  src/main/java/edu/harvard/iq/dataverse/util/json/NullSafeJsonBuilder.java
  src/test/java/edu/harvard/iq/dataverse/api/SearchIT.java
Labels: Type: Feature, User Role: API User, Size: 30, SPA, GREI Re-arch, SPA.Q4.2, FY25 Sprint 12

#10764 Correction of JsonPrinter output for metadatablock api calls
  doc/release-notes/master_json_fix.md
  doc/sphinx-guides/source/api/changelog.rst
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java
  src/test/java/edu/harvard/iq/dataverse/api/DataversesIT.java
  src/test/java/edu/harvard/iq/dataverse/api/MetadataBlocksIT.java
Labels: Type: Bug, Size: 3, FY25 Sprint 8, FY25 Sprint 9, FY25 Sprint 10

#11051 fix search files to return latest published citation
  doc/release-notes/10735-search-dataset-name-and-dataset-citation-different.md
  src/main/java/edu/harvard/iq/dataverse/search/IndexServiceBean.java
  src/test/java/edu/harvard/iq/dataverse/api/SearchIT.java
Labels: Type: Bug, Size: 10, FY25 Sprint 11, FY25 Sprint 12

#11071 Adding terms of use in DDI
  src/main/java/edu/harvard/iq/dataverse/api/imports/ImportDDIServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/export/ddi/DdiExportUtil.java
  src/test/java/edu/harvard/iq/dataverse/export/ddi/DdiExportUtilTest.java
  src/test/java/edu/harvard/iq/dataverse/export/ddi/dataset-finch-terms-of-use.json
  src/test/java/edu/harvard/iq/dataverse/export/ddi/dataset-finch-terms-of-use.xml
  src/test/java/edu/harvard/iq/dataverse/export/ddi/dataset-finch1.xml
  src/test/java/edu/harvard/iq/dataverse/export/ddi/exportfull.xml
Labels: Type: Bug, FY25 Sprint 12

#11050 Update actions/checkout 2->3+
  .github/workflows/container_app_pr.yml
  .github/workflows/container_app_push.yml
  .github/workflows/guides_build_sphinx.yml
  .github/workflows/pr_comment_commands.yml
  .github/workflows/reviewdog_checkstyle.yml
  .github/workflows/shellcheck.yml
  .github/workflows/shellspec.yml
  .github/workflows/spi_release.yml
Labels: Size: 3, FY25 Sprint 12
