Repository IQSS/dataverse, pull requests merged in 2024-11, with the labels that each got.

#10924 Extends users/token GET endpoint to support any auth mechanism for retrieving the token
  doc/release-notes/10914-users-token-api-credentials.md
  src/main/java/edu/harvard/iq/dataverse/api/Users.java
  src/test/java/edu/harvard/iq/dataverse/api/UsersIT.java
Labels: Size: 0.5, SPA, GREI Re-arch, Original size: 0.5, SPA.Q4, FY25 Sprint 8, FY25 Sprint 9

#10987 Revert "Bump actions/download-artifact from 3 to 4.1.7 in /.github/workflows"
  .github/workflows/deploy_beta_testing.yml
  .github/workflows/maven_unit_test.yml
Labels: FY25 Sprint 9

#10990 A fix for the harvesting regression/tests introduced in 10836
  src/main/java/edu/harvard/iq/dataverse/api/imports/ImportServiceBean.java
Labels: Feature: Harvesting, Size: 3, FY25 Sprint 9

#10925 Adds new update dataverse general endpoint
  doc/release-notes/10904-edit-dataverse-collection-endpoint.md
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/api/Dataverses.java
  src/main/java/edu/harvard/iq/dataverse/api/dto/DataverseDTO.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/AbstractWriteDataverseCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/CreateDataverseCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/UpdateDataverseCommand.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonParser.java
  src/test/java/edu/harvard/iq/dataverse/api/DataversesIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
  src/test/java/edu/harvard/iq/dataverse/util/json/JsonParserTest.java
Labels: Size: 3, SPA, GREI Re-arch, Original size: 3, SPA.Q4.3, FY25 Sprint 8, FY25 Sprint 9

#10985 Fix bug related to returnDatasetFieldTypes in Dataverses.listMetadataBlocks endpoint
  src/main/java/edu/harvard/iq/dataverse/DatasetFieldServiceBean.java
  src/test/java/edu/harvard/iq/dataverse/api/DataversesIT.java
Labels: Size: 3, SPA, Original size: 3, SPA.Q4.10, FY25 Sprint 9

#10923 detected mime type of m4a uploaded in zip
  src/main/java/propertyFiles/MimeTypeDetectionByFileExtension.properties
Labels: Type: Bug, Size: 3, FY25 Sprint 8, FY25 Sprint 9

#10999 Fixes unit test assertion in JsonParserTest
  src/test/java/edu/harvard/iq/dataverse/util/json/JsonParserTest.java
Labels: Type: Bug, Size: 0.5

#10772 Harvesting : Fix DDI Import for otherId
  doc/release-notes/10772-fix-importDDI-otherId.md
  src/main/java/edu/harvard/iq/dataverse/api/imports/ImportDDIServiceBean.java
Labels: Type: Bug, Size: 3, FY25 Sprint 8, FY25 Sprint 9

#10926 Fix relationType display value bug
  src/main/java/edu/harvard/iq/dataverse/DatasetVersion.java
  src/test/java/edu/harvard/iq/dataverse/pidproviders/doi/datacite/XmlMetadataTemplateTest.java
Labels: Size: 3, FY25 Sprint 8, FY25 Sprint 9

#10969 Ordering subfields while displaying dataset version differences
  doc/release-notes/10969-order-subfields-version-difference.md
  src/main/java/edu/harvard/iq/dataverse/DatasetVersionDifference.java
Labels: Type: Bug, Size: 3, FY25 Sprint 9

#11000 fix backwards newest oldest sort order
  doc/release-notes/10742-newest-oldest-sort-order-backwards.md
  src/main/webapp/filesFragment.xhtml
Labels: Type: Bug, Size: 3, FY25 Sprint 9

#10912 bump to Postgres 17, Flyway 10.19, allows earlier versions of PostgreSQL
  .env
  doc/release-notes/10889_bump_PG17_FlyWay10.md
  docker/compose/demo/compose.yml
  modules/dataverse-parent/pom.xml
  pom.xml
Labels: Type: Feature, Size: 10, FY25 Sprint 8, FY25 Sprint 9

#9461 Add Shib attribute characterset conversion to getValueFromAssertion
  src/main/java/edu/harvard/iq/dataverse/Shib.java
Labels: Type: Feature, Feature: Account & User Info, Size: 3, FY25 Sprint 7, FY25 Sprint 8, FY25 Sprint 9

#11003 Fix lookups of Harvested datasets with lower-case versions of persistent identifiers in the database
  doc/release-notes/10708 - MDC Citation and DOI parsing improvements.md
  doc/sphinx-guides/source/installation/config.rst
  src/main/java/edu/harvard/iq/dataverse/DvObject.java
  src/main/java/edu/harvard/iq/dataverse/api/imports/ImportServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/pidproviders/handle/HandlePidProvider.java
  src/main/java/edu/harvard/iq/dataverse/pidproviders/perma/PermaLinkPidProvider.java
  src/main/resources/db/migration/V6.4.0.1.sql
  src/test/java/edu/harvard/iq/dataverse/pidproviders/PidUtilTest.java
Labels: Size: 3, FY25 Sprint 10

#11013 Extend getDataverse API json payload to include properties isMetadataBlockRoot and isFacetRoot
  doc/release-notes/11012-get-dataverse-api-ext.md
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java
  src/test/java/edu/harvard/iq/dataverse/api/DataversesIT.java
Labels: User Role: API User, Size: 0.5, SPA, GREI Re-arch, Original size: 0.5, SPA.Q4.3

#10932 update making releases page post 6.4
  doc/sphinx-guides/source/developers/making-releases.rst
Labels: Size: 0.5, FY25 Sprint 8, FY25 Sprint 9, FY25 Sprint 10

#11025 Add two additional containers to provide Previewers locally
  docker/compose/demo/compose.yml
Labels: Component: Containers, Size: 0.5

#10837 Exclude others namespace from harvesting "oai_dc" metadata prefix
  doc/release-notes/10837-exclude-others-ns-harvesting-oai-dc.md
  src/main/java/edu/harvard/iq/dataverse/api/imports/ImportGenericServiceBean.java
Labels: Type: Feature, Feature: Harvesting, GREI 3, FY25 Sprint 10

#10118 IQSS/10117-increase-guestbook-question-length
  doc/release-notes/10117-guestbook-question-size-limit-raised.md
  src/main/java/edu/harvard/iq/dataverse/CustomQuestion.java
  src/main/java/edu/harvard/iq/dataverse/GuestbookPage.java
  src/main/resources/db/migration/V6.4.0.2.sql
  src/main/webapp/resources/iqbs/messages.xhtml
Labels: Type: Feature, GDCC: QDR, Size: 3, FY25 Sprint 10

#11022 validate guestbook email field
  doc/release-notes/10661-guestbook-email-bug-fix.md
  src/main/java/edu/harvard/iq/dataverse/GuestbookResponse.java
Labels: Type: Bug, Size: 10, FY25 Sprint 10

#10997 github actions from v3 to v4
  .github/workflows/deploy_beta_testing.yml
  .github/workflows/maven_unit_test.yml
Labels: Size: 30, github_actions, FY25 Sprint 9, FY25 Sprint 10

#10199 document configuring SELinux for Shibboleth
  doc/sphinx-guides/source/developers/selinux.rst
  doc/sphinx-guides/source/installation/shibboleth.rst
Labels: Type: Feature, Size: 0.5, FY25 Sprint 10

#11033 add wait to async export call
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: Type: Bug, Size: 3, FY25 Sprint 10

#11035 docs: file detection using first few bytes disabled on S3 direct upload
  doc/sphinx-guides/source/api/native-api.rst
  doc/sphinx-guides/source/developers/big-data-support.rst
Labels: Size: 0.5

#10980 fixing filter for Results By Username
  doc/release-notes/7239-mydata-results-by-username.md
  src/main/webapp/mydata_fragment.xhtml
  src/main/webapp/resources/js/mydata.js
Labels: Feature: Search/Browse, Type: Bug, Feature: Superuser Dashboard, Feature: My Data, Size: 10, FY25 Sprint 9, FY25 Sprint 10, FY25 Sprint 11

#10678 Assert true or false, not equal to true or false
  src/test/java/edu/harvard/iq/dataverse/DatasetFieldTypeTest.java
  src/test/java/edu/harvard/iq/dataverse/DatasetFieldValueValidatorTest.java
  src/test/java/edu/harvard/iq/dataverse/DatasetVersionTest.java
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
  src/test/java/edu/harvard/iq/dataverse/api/SwordIT.java
  src/test/java/edu/harvard/iq/dataverse/authorization/users/AuthenticatedUserTest.java
  src/test/java/edu/harvard/iq/dataverse/dataaccess/FileAccessIOTest.java
  src/test/java/edu/harvard/iq/dataverse/dataaccess/StorageIOTest.java
  src/test/java/edu/harvard/iq/dataverse/dataaccess/SwiftAccessIOTest.java
  src/test/java/edu/harvard/iq/dataverse/datacapturemodule/DataCaptureModuleUtilTest.java
  src/test/java/edu/harvard/iq/dataverse/dataset/DatasetUtilTest.java
  src/test/java/edu/harvard/iq/dataverse/datavariable/VariableMetadataDDIParserTest.java
  src/test/java/edu/harvard/iq/dataverse/export/SchemaDotOrgExporterTest.java
  src/test/java/edu/harvard/iq/dataverse/ingest/IngestUtilTest.java
  src/test/java/edu/harvard/iq/dataverse/mydata/PagerTest.java
  src/test/java/edu/harvard/iq/dataverse/util/json/JsonPrinterTest.java
Labels: Type: Feature, Size: 0.5, FY25 Sprint 10, FY25 Sprint 11

#11019 Improvements on PR #10198
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/api/SavedSearches.java
  src/test/java/edu/harvard/iq/dataverse/api/SavedSearchIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: Type: Bug, Size: 3, FY25 Sprint 10, FY25 Sprint 11

#10945 Add API endpoint for comparing Dataset Versions
  doc/release-notes/10888-add-api-for-comparing-dataset-versions.md
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/DatasetVersion.java
  src/main/java/edu/harvard/iq/dataverse/DatasetVersionDifference.java
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/CuratePublishedDatasetVersionCommand.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonParser.java
  src/main/java/propertyFiles/Bundle.properties
  src/test/java/edu/harvard/iq/dataverse/DatasetVersionDifferenceTest.java
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: Type: Feature, Feature: API, Size: 3, SPA, GREI Re-arch, Original size: 30, FY25 Sprint 8, FY25 Sprint 9, FY25 Sprint 10, FY25 Sprint 11

#10794 IQSS/10793 Improve Handling of Parallel Edit/Publish errors
  doc/release-notes/10793-optimisticlockexception handling.md
  src/main/java/edu/harvard/iq/dataverse/DatasetPage.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/PublishDatasetCommand.java
  src/main/java/propertyFiles/Bundle.properties
  src/main/webapp/dataset.xhtml
Labels: Type: Feature, GDCC: DANS, Size: 3, Consider For Next Release

#10739 Expose export formats in native API
  doc/release-notes/expose-export-formats.md
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/api/Info.java
  src/test/java/edu/harvard/iq/dataverse/api/InfoIT.java
  src/test/resources/json/export-formats.json
Labels: Type: Feature, Size: 3, FY25 Sprint 10, FY25 Sprint 11

#10598 8941 adding file count in solr (v2)
  conf/solr/schema.xml
  doc/release-notes/8941-adding-fileCount-in-solr.md
  src/main/java/edu/harvard/iq/dataverse/api/Search.java
  src/main/java/edu/harvard/iq/dataverse/search/IndexServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/search/SearchFields.java
  src/main/java/edu/harvard/iq/dataverse/search/SearchServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/search/SolrSearchResult.java
  src/test/java/edu/harvard/iq/dataverse/search/IndexServiceBeanTest.java
Labels: Type: Feature, Size: 3, FY25 Sprint 10, FY25 Sprint 11

#11026 Updates the updateDataverse API endpoint to support cases where an "inherit from parent" configuration is desired
  doc/release-notes/11018-update-dataverse-endpoint-update.md
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/Dataverse.java
  src/main/java/edu/harvard/iq/dataverse/api/Dataverses.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/AbstractWriteDataverseCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/CreateDataverseCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/UpdateDataverseCommand.java
  src/test/java/edu/harvard/iq/dataverse/api/DataversesIT.java
Labels: User Role: API User, Size: 3, SPA, GREI Re-arch, Original size: 3, SPA.Q4.3, FY25 Sprint 10, FY25 Sprint 11

#11039 limit beta testing deployments to one concurrent action at a time
  .github/workflows/deploy_beta_testing.yml
Labels: FY25 Sprint 10, FY25 Sprint 11

#11049 10982 10909 Allow using OAI-PMH identifiers as persistent ids of harvested datasets
  doc/release-notes/11049-oai-identifiers-as-pids.md
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/DataCitation.java
  src/main/java/edu/harvard/iq/dataverse/api/imports/ImportGenericServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/api/imports/ImportServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/harvest/client/HarvestingClient.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonParser.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java
  src/main/resources/db/migration/V6.4.0.3.sql
  src/main/webapp/search-include-fragment.xhtml
  src/test/java/edu/harvard/iq/dataverse/api/imports/ImportGenericServiceBeanTest.java
  src/test/resources/json/importGenericWithOtherId.json
  src/test/resources/json/importGenericWithoutOtherId.json
Labels: Size: 10
