Repository IQSS/dataverse, pull requests merged in 2024-07, with the labels that each got.

#10590 Extra settings for limiting search facets 10570
  doc/release-notes/10570-extra-facet-settings.md
  doc/sphinx-guides/source/installation/config.rst
  src/main/java/edu/harvard/iq/dataverse/DatasetPage.java
  src/main/java/edu/harvard/iq/dataverse/search/SearchIncludeFragment.java
  src/main/java/edu/harvard/iq/dataverse/settings/SettingsServiceBean.java
  src/main/webapp/search-include-fragment.xhtml
Labels: Size: 3

#9718 remove duplicate properties keys
  src/main/java/propertyFiles/Bundle.properties
  src/main/java/propertyFiles/biomedical.properties
  src/main/java/propertyFiles/customGSD.properties
Labels: Component: Code Infrastructure, Size: 0.5

#10642 Fix metadata field type display condition in dataverses/{id}/metadatablocks API endpoint
  doc/release-notes/10637-fix-dataverse-metadatablocks-api.md
  src/main/java/edu/harvard/iq/dataverse/Dataverse.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java
  src/test/java/edu/harvard/iq/dataverse/api/DataversesIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: Size: 3, SPA

#10662 6.3 Release Notes
  doc/release-notes/10015-RO-Crate-metadata-file.md
  doc/release-notes/10022_upload_redirect_without_tagging.md
  doc/release-notes/10116-incomplete-metadata-label-setting.md
  doc/release-notes/10137-2-add-disable-reason-flag.md
  doc/release-notes/10236-openapi-definition-endpoint.md
  doc/release-notes/10242-add-feature-dv-api
  doc/release-notes/10288-add-term_uri-metadata-in-keyword-block.md
  doc/release-notes/10316_cvoc_http_headers.md
  doc/release-notes/10330-api-change-latest-version-status.md
  doc/release-notes/10339-workflow.md
  doc/release-notes/10389-metadatablocks-api-extension.md
  doc/release-notes/10415-fix-api-performance-issues-on-large-datasets.md
  doc/release-notes/10425-add-MIT-License.md
  doc/release-notes/10464-add-name-harvesting-client-facet.md
  doc/release-notes/10466-math-challenge-403-error-page.md
  doc/release-notes/10468-doc-datalad-integration.md
  doc/release-notes/10477-metadatablocks-api-extension-input-levels.md
  doc/release-notes/10491-add-isreleased-to-get-dataverse-response.md
  doc/release-notes/10494-payara-upgrade.md
  doc/release-notes/10503-cvoc-hidden-html-fields.md
  doc/release-notes/10531-contrib.md
  doc/release-notes/10547-solr-updates.md
  doc/release-notes/10554-avoid-solr-join-guest.md
  doc/release-notes/10561-3dviewer.md
  doc/release-notes/10565-banner-test-improvements.md
  doc/release-notes/10568-Fix File Reingest.md
  doc/release-notes/10570-extra-facet-settings.md
  doc/release-notes/10579-avoid-solr-deletes.md
  doc/release-notes/10611-harvested-origin-facet.md
  doc/release-notes/10637-fix-dataverse-metadatablocks-api.md
  doc/release-notes/5621_dataset image in header.md
  doc/release-notes/6.3-release-notes.md
  doc/release-notes/8243-improve-language-controlled-vocab.md
  doc/release-notes/8655-re-add-cell-counting-biomedical-tsv.md
  doc/release-notes/8936-more-than-50000-entries-in-sitemap.md
  doc/release-notes/8985-deprecate-rsync.md
  doc/release-notes/9276-allow-flexible-params-in-retrievaluri-cvoc.md
  doc/release-notes/9276-doc-cvoc-index-in.md
  doc/release-notes/9375-retention-period.md
  doc/release-notes/9729-release-notes.md
  doc/release-notes/9739-url-validator.md
  doc/release-notes/9887-new-superuser-status-endpoint.md
  doc/release-notes/solr-9.4.1.md
  doc/sphinx-guides/source/api/native-api.rst
Labels: Size: 10

#10613 adding fix to file name for download guestbook responses
  src/main/java/edu/harvard/iq/dataverse/GuestbookResponsesPage.java
  src/main/java/edu/harvard/iq/dataverse/ManageGuestbooksPage.java
  src/main/java/edu/harvard/iq/dataverse/util/FileUtil.java
  src/test/java/edu/harvard/iq/dataverse/util/FileUtilTest.java
Labels: Type: Bug, Feature: Guestbook, Size: 3

#9014 Compare classes, not classnames in tests
  src/test/java/edu/harvard/iq/dataverse/api/SwordIT.java
  src/test/java/edu/harvard/iq/dataverse/util/bagit/data/FileDataProviderFactoryTest.java
Labels: Component: Code Infrastructure, Size: 3

#10627 ignore shapefiles if they are under a hidden directory in the zip file
  doc/release-notes/8945-ignore-shapefiles-under-hidden-directories-in-zip.md
  src/main/java/edu/harvard/iq/dataverse/util/ShapefileHandler.java
  src/test/java/edu/harvard/iq/dataverse/util/shapefile/ShapefileHandlerTest.java
  src/test/resources/hiddenShapefiles.zip
Labels: Type: Bug, Size: 10

#10614 8796 fix no license display and indexing
  doc/release-notes/8796-fix-license-display-indexing.md
  src/main/java/edu/harvard/iq/dataverse/DatasetVersionServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/TermsOfUseAndAccess.java
  src/main/java/edu/harvard/iq/dataverse/dataset/DatasetUtil.java
  src/main/java/edu/harvard/iq/dataverse/search/IndexServiceBean.java
  src/main/java/propertyFiles/Bundle.properties
  src/main/webapp/dataset-license-terms.xhtml
  src/main/webapp/datasetLicenseInfoFragment.xhtml
  src/main/webapp/guestbook-terms-popup-fragment.xhtml
  src/test/java/edu/harvard/iq/dataverse/search/IndexServiceBeanTest.java
Labels: Size: 3

#9010 Overload DatasetField method to remove type check
  src/main/java/edu/harvard/iq/dataverse/DatasetField.java
  src/test/java/edu/harvard/iq/dataverse/DatasetFieldTest.java
Labels: Component: Code Infrastructure, Size: 3

#10676 improve "making releases" doc (post 6.3)
  doc/sphinx-guides/source/developers/making-releases.rst
Labels: Size: 0.5

#10634 adding sql script to convert custom license CC0 Waiver to CC0 1.0
  doc/release-notes/9081-CC0-waiver-turned-into-custom-license.md
  src/main/resources/db/migration/V6.3.0.1.sql
Labels: Type: Bug, Feature: Terms & Licensing, Size: 10

#10085 Return valid JSON from API blocking filters
  doc/release-notes/api-blocking-filter-json.md
  src/main/java/edu/harvard/iq/dataverse/api/ApiBlockingFilter.java
Labels: Component: Code Infrastructure, Size: 3, FY25 Sprint 1, FY25 Sprint 2

#10701 add aws-cli to configbaker
  modules/container-configbaker/Dockerfile
Labels: Component: Containers

#10672 Security optimizations for the container base image
  doc/release-notes/10508-base-image-fixes.md
  doc/sphinx-guides/source/container/base-image.rst
  modules/container-base/src/main/docker/Dockerfile
  modules/container-base/src/main/docker/scripts/entrypoint.sh
  modules/container-base/src/main/docker/scripts/init_1_change_passwords.sh
  modules/container-base/src/main/docker/scripts/init_1_generate_deploy_commands.sh
  modules/container-base/src/main/docker/scripts/init_1_generate_devmode_commands.sh
  modules/container-base/src/main/docker/scripts/startInForeground.sh
  src/main/docker/scripts/init_2_configure.sh
  src/main/docker/scripts/init_3_wait_dataverse_db_host.sh
Labels: Feature: Installation Guide, Component: Containers, Size: 3, Feature: Container Guide

#10533 make Croissant support official, update exporter docs
  doc/release-notes/10341-croissant.md
  doc/sphinx-guides/source/admin/discoverability.rst
  doc/sphinx-guides/source/api/native-api.rst
  doc/sphinx-guides/source/developers/making-library-releases.rst
  doc/sphinx-guides/source/developers/metadataexport.rst
  doc/sphinx-guides/source/installation/advanced.rst
  doc/sphinx-guides/source/installation/config.rst
  doc/sphinx-guides/source/user/dataset-management.rst
Labels: Size: 0.5, FY24 Sprint 23

#10720 #10719 fix manage templates display
  src/main/java/edu/harvard/iq/dataverse/DatasetVersionServiceBean.java
  src/main/webapp/dataset-license-terms.xhtml
  src/main/webapp/template.xhtml
Labels: Size: 10

#10071 Use JsonUtil.getJsonX more often
  src/main/java/edu/harvard/iq/dataverse/metrics/MetricsUtil.java
  src/test/java/edu/harvard/iq/dataverse/metrics/MetricsUtilTest.java
Labels: Component: Code Infrastructure, Size: 3
