Repository IQSS/dataverse, pull requests merged in 2024-09, with the labels that each got.

#10813 IQSS/10812 - Add details to error messages
  src/main/java/edu/harvard/iq/dataverse/api/errorhandlers/WebApplicationExceptionHandler.java
Labels: GDCC: DANS, GDCC: QDR, Size: 3

#10802 Fix addDataverse expected request body structure
  doc/release-notes/10800-add-dataverse-request-json-fix.md
  src/main/java/edu/harvard/iq/dataverse/api/Dataverses.java
  src/test/java/edu/harvard/iq/dataverse/api/DataversesIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: Size: 0.5, SPA, FY25 Sprint 4, FY25 Sprint 5

#10823 Fixes inconsistent "Upload Dataset Logo" behavior (10821)
  src/main/java/edu/harvard/iq/dataverse/DatasetServiceBean.java
Labels: Size: 3

#10433 Add thumbnail for featured dataverses
  doc/release-notes/10433-add-thumbnail-for-featured-dataverses.md
  doc/sphinx-guides/source/user/dataverse-management.rst
  src/main/java/edu/harvard/iq/dataverse/DataverseServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/DataverseTheme.java
  src/main/java/edu/harvard/iq/dataverse/FeaturedDataverseServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/ThemeWidgetFragment.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/UpdateDataverseThemeCommand.java
  src/main/java/propertyFiles/Bundle.properties
  src/main/resources/db/migration/V6.3.0.2.sql
  src/main/webapp/dataverse.xhtml
  src/main/webapp/themeAndWidgetsFragment.xhtml
Labels: Size: 10, FY25 Sprint 4, FY25 Sprint 5

#10124 JDD Metrics: Label KO #10123
  src/main/webapp/dataset.xhtml
Labels: Size: 3, FY25 Sprint 4

#10694 dataset types (software, workflow, etc.) - initial support
  conf/solr/schema.xml
  doc/release-notes/10517-datasetType.md
  doc/sphinx-guides/source/_static/api/dataset-create-software.json
  doc/sphinx-guides/source/_static/api/dataset-create-software.jsonld
  doc/sphinx-guides/source/api/native-api.rst
  doc/sphinx-guides/source/developers/dataset-semantic-metadata-api.rst
  doc/sphinx-guides/source/installation/config.rst
  doc/sphinx-guides/source/user/dataset-management.rst
  src/main/java/edu/harvard/iq/dataverse/Dataset.java
  src/main/java/edu/harvard/iq/dataverse/EjbDataverseEngine.java
  src/main/java/edu/harvard/iq/dataverse/api/AbstractApiBean.java
  src/main/java/edu/harvard/iq/dataverse/api/Admin.java
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/main/java/edu/harvard/iq/dataverse/api/Dataverses.java
  src/main/java/edu/harvard/iq/dataverse/api/imports/ImportGenericServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/api/imports/ImportServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/dataset/DatasetType.java
  src/main/java/edu/harvard/iq/dataverse/dataset/DatasetTypeServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/CommandContext.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/AbstractCreateDatasetCommand.java
  src/main/java/edu/harvard/iq/dataverse/pidproviders/doi/XmlMetadataTemplate.java
  src/main/java/edu/harvard/iq/dataverse/search/IndexServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/search/SearchFields.java
  src/main/java/edu/harvard/iq/dataverse/search/SearchServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/search/SolrSearchResult.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JSONLDUtil.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonLDTerm.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonParser.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java
  src/main/java/propertyFiles/Bundle.properties
  src/main/java/propertyFiles/staticSearchFields.properties
  src/main/resources/db/migration/V6.3.0.3.sql
  src/main/resources/edu/harvard/iq/dataverse/pidproviders/doi/datacite_metadata_template.xml
  src/test/java/edu/harvard/iq/dataverse/api/DatasetTypesIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
  src/test/java/edu/harvard/iq/dataverse/engine/TestCommandContext.java
  src/test/java/edu/harvard/iq/dataverse/export/SchemaDotOrgExporterTest.java
  src/test/java/edu/harvard/iq/dataverse/feedback/FeedbackUtilTest.java
  src/test/java/edu/harvard/iq/dataverse/search/IndexServiceBeanTest.java
  src/test/java/edu/harvard/iq/dataverse/util/json/JsonParserTest.java
  tests/integration-tests.txt
Labels: GREI 6, Size: 50, GREI Year 3, FY25 Sprint 2, FY25 Sprint 3, FY25 Sprint 4, FY25 Sprint 5

#10825 IQSS/10824 - Add logic to suppress query tool display for non-public files.
  src/main/java/edu/harvard/iq/dataverse/FilePage.java
Labels: Size: 3

#10811 Search API results payload extension
  conf/solr/schema.xml
  doc/release-notes/10810-search-api-payload-extensions.md
  doc/sphinx-guides/source/api/search.rst
  src/main/java/edu/harvard/iq/dataverse/ThumbnailServiceWrapper.java
  src/main/java/edu/harvard/iq/dataverse/search/IndexServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/search/SearchFields.java
  src/main/java/edu/harvard/iq/dataverse/search/SearchServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/search/SolrSearchResult.java
  src/test/java/edu/harvard/iq/dataverse/api/SearchIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: User Role: API User, Size: 3, SPA, GREI Re-arch

#10737 Remap oai_dc fields dc:type and dc:date
  doc/release-notes/8129-harvesting.md
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/export/dublincore/DublinCoreExportUtil.java
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: Feature: Harvesting, Size: 10, GREI 3, FY25 Sprint 3, FY25 Sprint 4, FY25 Sprint 5

#10535 10527 404static.xhtml has an old date in the footer (2023 is hard-coded) and update URLs
  src/main/webapp/404static.xhtml
Labels: Size: 0.5, Champion: pdurbin, FY25 Sprint 6

#10841 IQSS/10840 - DatasetTypesIT test fix
  src/test/java/edu/harvard/iq/dataverse/api/DatasetTypesIT.java
Labels: Size: 0.5

#10845 chore(ct): update base image wait4x to 2.14.2 for stdlib update #10844
  modules/container-base/src/main/docker/Dockerfile
Labels: Component: Containers, Size: 0.5

#10775 Update handling of permalink base-url setting
  doc/release-notes/permalink-base-urls.md
  doc/sphinx-guides/source/installation/config.rst
  src/main/java/edu/harvard/iq/dataverse/pidproviders/perma/PermaLinkPidProvider.java
  src/main/java/edu/harvard/iq/dataverse/pidproviders/perma/PermaLinkProviderFactory.java
  src/test/java/edu/harvard/iq/dataverse/pidproviders/PidUtilTest.java
Labels: Size: 3, FY25 Sprint 6

#10806 Crossref as a DOI provider (experimental)
  doc/release-notes/8581-add-crossref-pid-provider.md
  doc/sphinx-guides/source/installation/config.rst
  src/main/java/edu/harvard/iq/dataverse/pidproviders/doi/crossref/CrossRefDOIProvider.java
  src/main/java/edu/harvard/iq/dataverse/pidproviders/doi/crossref/CrossRefDOIProviderFactory.java
  src/main/java/edu/harvard/iq/dataverse/pidproviders/doi/crossref/CrossRefDOIRegisterService.java
  src/main/java/edu/harvard/iq/dataverse/pidproviders/doi/crossref/CrossRefRESTfullClient.java
  src/main/java/edu/harvard/iq/dataverse/settings/JvmSettings.java
  src/main/resources/edu/harvard/iq/dataverse/pidproviders/doi/crossref_metadata_template.xml
  src/test/java/edu/harvard/iq/dataverse/pidproviders/PidUtilTest.java
Labels: Type: Feature, Size: 10, FY25 Sprint 4, FY25 Sprint 5, FY25 Sprint 6

#10504 10287: Use support email in the system email message 'closing' text
  doc/release-notes/10287-use-support-address-in-system-email-text.md
  doc/sphinx-guides/source/installation/config.rst
  src/main/java/edu/harvard/iq/dataverse/MailServiceBean.java
Labels: Type: Feature, Feature: Notifications, Size: 3, Consider For Next Release, FY25 Sprint 6

#10710 IQSS/10709 - Improve index/status and /clear-orphan speed
  src/main/java/edu/harvard/iq/dataverse/DataFileServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/DatasetServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/DvObject.java
  src/main/java/edu/harvard/iq/dataverse/DvObjectServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/search/IndexBatchServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/search/IndexServiceBean.java
Labels: GDCC: DANS, GDCC: QDR, Size: 3, Consider For Next Release, FY25 Sprint 6

#10827 Releasing versioned (base) images
  .github/actions/setup-maven/action.yml
  .github/workflows/container_app_push.yml
  .github/workflows/container_base_push.yml
  .github/workflows/container_maintenance.yml
  .github/workflows/maven_unit_test.yml
  .github/workflows/scripts/maintenance-job.sh
  .github/workflows/scripts/utils.sh
  doc/release-notes/10478-version-base-image.md
  doc/sphinx-guides/source/container/base-image.rst
  doc/sphinx-guides/source/developers/making-releases.rst
  modules/container-base/README.md
  modules/container-base/pom.xml
  modules/container-base/src/backports/v6.1/001-pom.xml.patch
  modules/container-base/src/backports/v6.1/002-Dockerfile.patch
  modules/container-base/src/backports/v6.1/003-parent-pom.xml.patch
  modules/container-base/src/backports/v6.2/001-pom.xml.patch
  modules/container-base/src/backports/v6.2/002-Dockerfile.labels.patch
  modules/container-base/src/backports/v6.2/003-Dockerfile.security.patch
  modules/container-base/src/backports/v6.2/004-parent-pom.xml.patch
  modules/container-base/src/backports/v6.3/001-pom.xml.patch
  modules/container-base/src/backports/v6.3/002-Dockerfile.labels.patch
  modules/container-base/src/backports/v6.3/003-Dockerfile.security.patch
  modules/container-base/src/backports/v6.3/004-parent-pom.xml.patch
  modules/container-base/src/main/docker/Dockerfile
  modules/dataverse-parent/pom.xml
  pom.xml
Labels: Component: Containers, Size: 3

#10867 Temp file cleanup for PrimeFaces uploads 10667
  src/main/java/edu/harvard/iq/dataverse/EditDatafilesPage.java
Labels: Feature: File Upload & Handling, Size: 3

#10261 Document how to update a "develop branch to develop branch" pull request
  doc/sphinx-guides/source/developers/version-control.rst
Labels: Size: 0.5

#10632 DataciteXML changes Plus RelationType field
  conf/solr/schema.xml
  doc/release-notes/10632-DataCiteXMLandRelationType.md
  doc/sphinx-guides/source/admin/dataverses-datasets.rst
  doc/sphinx-guides/source/api/changelog.rst
  doc/sphinx-guides/source/installation/config.rst
  scripts/api/data/dataset-create-new-all-default-fields.json
  scripts/api/data/metadatablocks/citation.tsv
  src/main/java/edu/harvard/iq/dataverse/DataFile.java
  src/main/java/edu/harvard/iq/dataverse/DatasetFieldConstant.java
  src/main/java/edu/harvard/iq/dataverse/DatasetRelPublication.java
  src/main/java/edu/harvard/iq/dataverse/DatasetServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/DatasetVersion.java
  src/main/java/edu/harvard/iq/dataverse/DatasetVersionUI.java
  src/main/java/edu/harvard/iq/dataverse/ExternalIdentifier.java
  src/main/java/edu/harvard/iq/dataverse/GlobalId.java
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/AbstractCreateDatasetCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/FinalizeDatasetPublicationCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/UpdateDatasetTargetURLCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/UpdateDvObjectPIDMetadataCommand.java
  src/main/java/edu/harvard/iq/dataverse/export/DataCiteExporter.java
  src/main/java/edu/harvard/iq/dataverse/export/ddi/DdiExportUtil.java
  src/main/java/edu/harvard/iq/dataverse/export/dublincore/DublinCoreExportUtil.java
  src/main/java/edu/harvard/iq/dataverse/export/openaire/OpenAireExportUtil.java
  src/main/java/edu/harvard/iq/dataverse/pidproviders/PidProviderFactoryBean.java
  src/main/java/edu/harvard/iq/dataverse/pidproviders/doi/AbstractDOIProvider.java
  src/main/java/edu/harvard/iq/dataverse/pidproviders/doi/DoiMetadata.java
  src/main/java/edu/harvard/iq/dataverse/pidproviders/doi/XmlMetadataTemplate.java
  src/main/java/edu/harvard/iq/dataverse/pidproviders/doi/datacite/DOIDataCiteRegisterService.java
  src/main/java/edu/harvard/iq/dataverse/pidproviders/doi/datacite/DataCiteDOIProvider.java
  src/main/java/edu/harvard/iq/dataverse/pidproviders/doi/datacite/DataCiteRESTfullClient.java
  src/main/java/edu/harvard/iq/dataverse/util/xml/XmlValidator.java
  src/main/java/edu/harvard/iq/dataverse/util/xml/XmlWriterUtil.java
  src/main/java/propertyFiles/Bundle.properties
  src/main/java/propertyFiles/citation.properties
  src/main/resources/edu/harvard/iq/dataverse/pidproviders/doi/datacite_metadata_template.xml
  src/main/webapp/dataset.xhtml
  src/main/webapp/resources/css/structure.css
  src/test/java/edu/harvard/iq/dataverse/api/DataversesIT.java
  src/test/java/edu/harvard/iq/dataverse/api/MetadataBlocksIT.java
  src/test/java/edu/harvard/iq/dataverse/export/OpenAireExportUtilTest.java
  src/test/java/edu/harvard/iq/dataverse/export/dataset-all-defaults.txt
  src/test/java/edu/harvard/iq/dataverse/pidproviders/doi/datacite/XmlMetadataTemplateTest.java
Labels: GDCC: QDR, Size: 10, Consider For Next Release, FY25 Sprint 5, FY25 Sprint 6

#10864 add docs for disable-dataset-thumbnail-autoselect
  doc/sphinx-guides/source/installation/config.rst
Labels: Size: 0.5, FY25 Sprint 6

#10870 Fix NPE using CVOC
  doc/release-notes/10869-fix-npe-using-cvoc.md
  src/main/java/edu/harvard/iq/dataverse/search/IndexServiceBean.java
Labels: Size: 0.5

#10855 standardize image url
  doc/release-notes/10831-standardize-image-url-of-search-api.md
  doc/sphinx-guides/source/api/search.rst
  src/main/java/edu/harvard/iq/dataverse/DataverseServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/ThumbnailServiceWrapper.java
  src/main/java/edu/harvard/iq/dataverse/search/SearchServiceBean.java
  src/test/java/edu/harvard/iq/dataverse/api/SearchIT.java
Labels: Type: Feature, User Role: API User, Size: 3, SPA, GREI Re-arch, FY25 Sprint 6, SPA.Q3.1

#10829 reworked controlled vocab language keys
  scripts/api/data/metadatablocks/citation.tsv
  src/main/java/propertyFiles/citation.properties
  src/test/java/edu/harvard/iq/dataverse/MetadataBlockTest.java
Labels: Size: 3, FY25 Sprint 5

#10877 Update text to hyperlink in documentation
  doc/sphinx-guides/source/contributor/documentation.md
Labels: Size: 0.5

#10781 Improved handling of Globus uploads (experimental async framework)
  doc/release-notes/10623-globus-improvements.md
  doc/sphinx-guides/source/developers/big-data-support.rst
  doc/sphinx-guides/source/developers/globus-api.rst
  doc/sphinx-guides/source/installation/config.rst
  src/main/java/edu/harvard/iq/dataverse/DatasetServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/EditDatafilesPage.java
  src/main/java/edu/harvard/iq/dataverse/ExternalFileUploadInProgress.java
  src/main/java/edu/harvard/iq/dataverse/MailServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/UserNotification.java
  src/main/java/edu/harvard/iq/dataverse/api/ApiConstants.java
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/main/java/edu/harvard/iq/dataverse/authorization/providers/builtin/DataverseUserPage.java
  src/main/java/edu/harvard/iq/dataverse/datasetutility/AddReplaceFileHelper.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/UpdateDatasetVersionCommand.java
  src/main/java/edu/harvard/iq/dataverse/globus/GlobusServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/globus/GlobusTaskInProgress.java
  src/main/java/edu/harvard/iq/dataverse/globus/GlobusTaskState.java
  src/main/java/edu/harvard/iq/dataverse/globus/GlobusUtil.java
  src/main/java/edu/harvard/iq/dataverse/globus/TaskMonitoringServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/ingest/IngestServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/settings/FeatureFlags.java
  src/main/java/edu/harvard/iq/dataverse/settings/JvmSettings.java
  src/main/java/edu/harvard/iq/dataverse/timer/DataverseTimerServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/util/MailUtil.java
  src/main/java/edu/harvard/iq/dataverse/util/SystemConfig.java
  src/main/java/propertyFiles/Bundle.properties
  src/main/webapp/dataverseuser.xhtml
Labels: Size: 30, GREI 5, FY25 Sprint 4, FY25 Sprint 5, FY25 Sprint 6

#10712 IQSS/10711 Cvoc updates
  doc/release-notes/10711-CVoc Updates.md
  src/main/java/edu/harvard/iq/dataverse/DatasetFieldCompoundValue.java
  src/main/java/edu/harvard/iq/dataverse/DatasetFieldServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/SettingsWrapper.java
  src/main/webapp/metadataFragment.xhtml
  src/main/webapp/resources/css/structure.css
Labels: GDCC: DANS, GDCC: QDR, Feature: Controlled Vocabulary, Size: 3, Consider For Next Release, FY25 Sprint 6, FY25 Sprint 7

#10871 bump version to 6.4
  doc/sphinx-guides/source/conf.py
  doc/sphinx-guides/source/versions.rst
  modules/dataverse-parent/pom.xml
Labels: Size: 3, FY25 Sprint 6, FY25 Sprint 7

#10884 displayOnCreate set to true for depositor and dateOfDeposit in Citation metadata block
  doc/release-notes/10850-citation-tsv-displayoncreate-depositor-dateofdeposit.md
  scripts/api/data/metadatablocks/citation.tsv
  src/test/java/edu/harvard/iq/dataverse/api/MetadataBlocksIT.java
Labels: Size: 0.5, SPA, GREI Re-arch, SPA.Q3

#10866 6.4 release notes
  doc/release-notes/10169-JSON-schema-validation.md
  doc/release-notes/10287-use-support-address-in-system-email-text.md
  doc/release-notes/10341-croissant.md
  doc/release-notes/10433-add-thumbnail-for-featured-dataverses.md
  doc/release-notes/10478-version-base-image.md
  doc/release-notes/10508-base-image-fixes.md
  doc/release-notes/10517-datasetType.md
  doc/release-notes/10583-dataset-unlink-functionality-same-permission-as-link.md
  doc/release-notes/10606-dataverse-in-windows-wsl.md
  doc/release-notes/10623-globus-improvements.md
  doc/release-notes/10632-DataCiteXMLandRelationType.md
  doc/release-notes/10633-add-dataverse-api-extension.md
  doc/release-notes/10711-CVoc Updates.md
  doc/release-notes/10726-dataverse-facets-api-extension.md
  doc/release-notes/10733-add-publication-status-to-search-api-results.md
  doc/release-notes/10741-list-metadatablocks-display-on-create-fix.md
  doc/release-notes/10744-ro-crate-docs.md
  doc/release-notes/10749-dataverse-user-permissions-api-extension.md
  doc/release-notes/10758-rust-client.md
  doc/release-notes/10797-update-current-version-bug-fix.md
  doc/release-notes/10800-add-dataverse-request-json-fix.md
  doc/release-notes/10810-search-api-payload-extensions.md
  doc/release-notes/10819-publish-thumbnail-bug.md
  doc/release-notes/10831-standardize-image-url-of-search-api.md
  doc/release-notes/10850-citation-tsv-displayoncreate-depositor-dateofdeposit.md
  doc/release-notes/10869-fix-npe-using-cvoc.md
  doc/release-notes/6.4-release-notes.md
  doc/release-notes/7068-reserve-file-pids.md
  doc/release-notes/8129-harvesting.md
  doc/release-notes/8578-support-for-iso-639-3-languages.md
  doc/release-notes/8581-add-crossref-pid-provider.md
  doc/release-notes/8796-fix-license-display-indexing.md
  doc/release-notes/8945-ignore-shapefiles-under-hidden-directories-in-zip.md
  doc/release-notes/9081-CC0-waiver-turned-into-custom-license.md
  doc/release-notes/9317-delete-saved-search.md
  doc/release-notes/api-blocking-filter-json.md
  doc/release-notes/make-data-count-.md
  doc/release-notes/permalink-base-urls.md
Labels: Size: 3, FY25 Sprint 6, FY25 Sprint 7

#10776 Trailing comma in author name causes error
  doc/release-notes/10343-trailing-comma.md
  src/main/java/edu/harvard/iq/dataverse/util/PersonOrOrgUtil.java
  src/test/java/edu/harvard/iq/dataverse/util/PersonOrOrgUtilTest.java
Labels: Size: 0.5

#10894 docs: update release notes from #10343
  doc/release-notes/10343-trailing-comma.md
  doc/release-notes/6.4-release-notes.md
Labels: Size: 0.5

#10805 Importing unmanaged pids
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/api/Dataverses.java
  src/test/java/edu/harvard/iq/dataverse/api/DataversesIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: FY25 Sprint 7

#10897 #10879 remove access request from render logic
  src/main/webapp/dataset-license-terms.xhtml
Labels: Size: 3, FY25 Sprint 7
