Repository IQSS/dataverse, pull requests merged in 2025-05, with the labels that each got.

#11422 add API for getting application terms of use
  doc/release-notes/11415-app-tou.md
  doc/sphinx-guides/source/admin/metadatacustomization.rst
  doc/sphinx-guides/source/api/native-api.rst
  doc/sphinx-guides/source/installation/config.rst
  doc/sphinx-guides/source/user/dataset-management.rst
  src/main/java/edu/harvard/iq/dataverse/api/Info.java
  src/main/java/edu/harvard/iq/dataverse/util/SystemConfig.java
  src/test/java/edu/harvard/iq/dataverse/api/InfoIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: Type: Feature, Size: 10, GREI Re-arch, Original size: 10, FY25 Sprint 21, SPA.Q2.7, FY25 Sprint 22

#11460 #11458 remove file page breadcrumbs
  src/main/webapp/dataverse_header.xhtml
  src/main/webapp/file.xhtml
Labels: Type: Bug, Size: 3, FY25 Sprint 22

#11466 Prettier names for the zipped multi-file bundles
  doc/release-notes/9620-better-file-bundle-name.md
  doc/sphinx-guides/source/api/dataaccess.rst
  src/main/java/edu/harvard/iq/dataverse/api/Access.java
  src/test/java/edu/harvard/iq/dataverse/api/AccessIT.java
Labels: Type: Suggestion, Feature: File Upload & Handling, User Role: Guest, Size: 10, GREI 6, FY25 Sprint 21, FY25 Sprint 22

#11429 Allow images with unicode filenames to be uploaded for featured items
  scripts/issues/11429/add-featured-items.sh
  scripts/issues/11429/update-featured-item.sh
  scripts/issues/11429/update-featured-items.sh
  scripts/issues/11429/π.png
  src/main/java/edu/harvard/iq/dataverse/api/Dataverses.java
  src/main/java/edu/harvard/iq/dataverse/api/dto/NewDataverseFeaturedItemDTO.java
  src/main/java/edu/harvard/iq/dataverse/api/dto/UpdatedDataverseFeaturedItemDTO.java
  src/main/java/edu/harvard/iq/dataverse/util/FileUtil.java
  src/test/java/edu/harvard/iq/dataverse/api/DataverseFeaturedItemsIT.java
Labels: Type: Bug, Size: 10, SPA, GREI Re-arch, Original size: 10, FY25 Sprint 21, SPA.Q2, FY25 Sprint 22

#11478 Fix MailServiceBeanIT
  src/test/java/edu/harvard/iq/dataverse/MailServiceBeanIT.java
Labels: Component: Code Infrastructure, Feature: Performance & Stability, Size: 0.5

#11480 Fix copy label flow
  .github/workflows/copy_labels.yml
Labels: Component: Code Infrastructure, Consider For Next Release

#11398 metadata export for drafts via API
  doc/release-notes/11305-export-drafts.md
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/DatasetPage.java
  src/main/java/edu/harvard/iq/dataverse/DatasetVersion.java
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/main/java/edu/harvard/iq/dataverse/export/ExportService.java
  src/main/java/edu/harvard/iq/dataverse/export/ddi/DdiExportUtil.java
  src/main/java/edu/harvard/iq/dataverse/harvest/server/xoai/DataverseXoaiItemRepository.java
  src/test/java/edu/harvard/iq/dataverse/DatasetVersionTest.java
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: Type: Feature, Size: 3, Croissant, FY25 Sprint 20, FY25 Sprint 21, FY25 Sprint 22, FY25 Sprint 23

#11416 IQSS/10680-Bagit warning fix
  doc/release-notes/10680-Bagit-Change.md
  src/main/java/edu/harvard/iq/dataverse/util/bagit/BagGenerator.java
Labels: Size: 3, FY25 Sprint 21, FY25 Sprint 22, FY25 Sprint 23

#11464 Fix File Version Summary API
  doc/release-notes/11438-fix-file-version-summary.md
  src/main/java/edu/harvard/iq/dataverse/FileMetadataVersionsHelper.java
  src/test/java/edu/harvard/iq/dataverse/api/FilesIT.java
Labels: Type: Feature, SPA, GREI Re-arch, Size: 20, SPA.Q2.2, FY25 Sprint 22, Original size: 20, FY25 Sprint 23

#11476 avoid NPE when deciding between Croissant and Schema.org JSON-LD
  src/main/webapp/dataset.xhtml
Labels: Type: Bug, Size: 3, Croissant, FY25 Sprint 23

#11496 Reduce useless warnings about missing vocab values
  src/main/java/edu/harvard/iq/dataverse/ControlledVocabularyValue.java
Labels: Size: 3

#11482 feat: migrate FILES_HIDE_SCHEMA_DOT_ORG_DOWNLOAD_URLS to MPConfig
  doc/release-notes/11482-mpconfig-schema-dot-org-hide-download-urls.md
  doc/sphinx-guides/source/installation/config.rst
  src/main/java/edu/harvard/iq/dataverse/DatasetVersion.java
  src/main/java/edu/harvard/iq/dataverse/settings/JvmSettings.java
  src/main/java/edu/harvard/iq/dataverse/util/SystemConfig.java
  src/test/java/edu/harvard/iq/dataverse/export/SchemaDotOrgExporterTest.java
Labels: Component: Containers, Size: 3, FY25 Sprint 23

#11495 Fix DDI Exception
  src/main/java/edu/harvard/iq/dataverse/export/DDIExporter.java
Labels: Size: 0.5, FY25 Sprint 23

#11374 Solr Index Improvements
  conf/solr/solrconfig.xml
  doc/release-notes/11374-indexing-improvement.md
  doc/sphinx-guides/source/installation/config.rst
  src/main/java/edu/harvard/iq/dataverse/DataFile.java
  src/main/java/edu/harvard/iq/dataverse/Dataset.java
  src/main/java/edu/harvard/iq/dataverse/DatasetServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/FileMetadata.java
  src/main/java/edu/harvard/iq/dataverse/FileVersionDifference.java
  src/main/java/edu/harvard/iq/dataverse/RoleAssigneeServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/RoleAssignment.java
  src/main/java/edu/harvard/iq/dataverse/datavariable/VariableMetadataUtil.java
  src/main/java/edu/harvard/iq/dataverse/search/IndexBatchServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/search/IndexServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/search/SearchPermissionsServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/search/SolrIndexServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/settings/JvmSettings.java
  src/main/java/edu/harvard/iq/dataverse/settings/SettingsServiceBean.java
  src/main/resources/META-INF/persistence.xml
  src/test/java/edu/harvard/iq/dataverse/search/IndexServiceBeanTest.java
Labels: Size: 10, FY25 Sprint 20, FY25 Sprint 21, FY25 Sprint 22, FY25 Sprint 23, FY25 Sprint 24
