Repository IQSS/dataverse, pull requests merged in 2025-02, with the labels that each got.

#11164 11159 Add more information about anonymous access Preview URL; Limit Anon Access to Draft Versions
  doc/release-notes/11159-preview-url-update.md
  doc/sphinx-guides/source/user/dataset-management.rst
  src/main/java/edu/harvard/iq/dataverse/DatasetPage.java
  src/main/java/propertyFiles/Bundle.properties
  src/main/webapp/dataset.xhtml
Labels: Size: 3, FY25 Sprint 15, FY25 Sprint 16

#11167 add 3d objects metadata block
  conf/solr/schema.xml
  doc/release-notes/11120-add-3d-object-metadata-block.md
  doc/sphinx-guides/source/user/appendix.rst
  scripts/api/data/metadatablocks/3d_objects.tsv
  scripts/api/setup-datasetfields.sh
  scripts/api/update-datasetfields.sh
  src/main/java/propertyFiles/3dobjects.properties
  src/test/java/edu/harvard/iq/dataverse/api/DatasetFieldsIT.java
  src/test/java/edu/harvard/iq/dataverse/api/MetadataBlocksIT.java
Labels: Type: Feature, Feature: Metadata, Size: 10, FY25 Sprint 15, FY25 Sprint 16

#11138 Search API show_type_counts=true now includes all object types
  doc/release-notes/11127-update-search-api-to-show-dvobject-type-counts.md
  src/main/java/edu/harvard/iq/dataverse/api/Search.java
  src/test/java/edu/harvard/iq/dataverse/api/SearchIT.java
Labels: Size: 3, SPA, GREI Re-arch, Original size: 3, SPA.Q4.1, FY25 Sprint 14, SPA.Q1, FY25 Sprint 15, FY25 Sprint 16

#11192 Dataset Migration API documentation improvements
  doc/sphinx-guides/source/_static/api/dataset-migrate.jsonld
  doc/sphinx-guides/source/_static/api/transform-oai-ore-jsonld.xq
  doc/sphinx-guides/source/developers/dataset-migration-api.rst
Labels: Size: 3, FY25 Sprint 15, FY25 Sprint 16

#11170 Rezip shape files with upper case extension
  src/main/java/edu/harvard/iq/dataverse/util/ShapefileHandler.java
  src/test/java/edu/harvard/iq/dataverse/util/shapefile/ShapefileHandlerTest.java
Labels: Size: 3, FY25 Sprint 15, FY25 Sprint 16

#11205 clarify which PID settings are required
  doc/sphinx-guides/source/installation/config.rst
Labels: Size: 0.5, FY25 Sprint 16

#11054 IQSS/10108 Stata mimetype refinement for direct upload
  doc/release-notes/10108-stata-version-detected-in-direct-upload.md
  doc/sphinx-guides/source/api/native-api.rst
  doc/sphinx-guides/source/developers/big-data-support.rst
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/CreateNewDataFilesCommand.java
  src/main/java/edu/harvard/iq/dataverse/ingest/IngestableDataChecker.java
  src/main/java/edu/harvard/iq/dataverse/util/FileUtil.java
  src/test/java/edu/harvard/iq/dataverse/api/S3AccessIT.java
Labels: Size: 10, FY25 Sprint 14, FY25 Sprint 15, FY25 Sprint 16

#11209 Fix Flaky DatasetsIT test
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
Labels: Size: 0.5

#11106 IQSS/11053 - Metadata Style fixes
  doc/release-notes/11053-metadata-styling-fixes
  src/main/webapp/resources/css/structure.css
Labels: Size: 3, FY25 Sprint 14, FY25 Sprint 15, FY25 Sprint 16

#10320 Add cookie consent example
  doc/release-notes/10320-cookie-consent.md
  doc/sphinx-guides/source/installation/config.rst
  doc/sphinx-guides/source/installation/img/cookie-consent-example.png
Labels: Type: Feature, Size: 0.5, FY25 Sprint 11, FY25 Sprint 12, FY25 Sprint 14, FY25 Sprint 15, FY25 Sprint 16

#11190 fix: fix bug in OAI-ORE exporter related to nested compound fields
  doc/release-notes/10809-oai-ore-nested-compound.md
  src/main/java/edu/harvard/iq/dataverse/util/bagit/OREMap.java
Labels: Size: 3, FY25 Sprint 15, FY25 Sprint 16

#11136 fix: correctly set "multiValued" property in Solr schema for deeply nested fields
  doc/release-notes/11136-solr-nested.md
  src/main/java/edu/harvard/iq/dataverse/DatasetFieldType.java
Labels: Size: 3, FY25 Sprint 15, FY25 Sprint 16

#10979 IQSS 10975 - fix file replace
  doc/release-notes/10975-fix-file-replace-via-api
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/UpdateDatasetVersionCommand.java
  src/main/java/edu/harvard/iq/dataverse/pidproviders/doi/fake/FakeDOIProvider.java
Labels: Size: 3, FY25 Sprint 15, FY25 Sprint 16

#11045 expose links to all export formats via Signposting
  doc/release-notes/10542-signposting.md
  doc/sphinx-guides/source/admin/discoverability.rst
  doc/sphinx-guides/source/api/changelog.rst
  doc/sphinx-guides/source/api/native-api.rst
  doc/sphinx-guides/source/user/dataset-management.rst
  src/main/java/edu/harvard/iq/dataverse/export/SchemaDotOrgExporter.java
  src/main/java/edu/harvard/iq/dataverse/util/SignpostingResources.java
  src/test/java/edu/harvard/iq/dataverse/api/SignpostingIT.java
  src/test/resources/json/export-formats.json
Labels: FY25 Sprint 11, FY25 Sprint 12, FY25 Sprint 14, FY25 Sprint 15, FY25 Sprint 16

#10790 fix: issues in exporters and citations for PermaLink/non-DOI PIDs
  doc/release-notes/10790-fix pid handling in exporters and citations.md
  doc/sphinx-guides/source/installation/config.rst
  src/main/java/edu/harvard/iq/dataverse/DataCitation.java
  src/main/java/edu/harvard/iq/dataverse/DvObject.java
  src/main/java/edu/harvard/iq/dataverse/GlobalId.java
  src/main/java/edu/harvard/iq/dataverse/api/dto/DatasetDTO.java
  src/main/java/edu/harvard/iq/dataverse/export/ddi/DdiExportUtil.java
  src/main/java/edu/harvard/iq/dataverse/pidproviders/AbstractPidProvider.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java
  src/main/resources/db/migration/V6.5.0.4.sql
  src/test/java/edu/harvard/iq/dataverse/DataCitationTest.java
  src/test/java/edu/harvard/iq/dataverse/export/ddi/DdiExportUtilTest.java
  src/test/java/edu/harvard/iq/dataverse/export/ddi/dataset-create-new-all-ddi-fields.json
  src/test/java/edu/harvard/iq/dataverse/export/ddi/dataset-finch1.json
  src/test/java/edu/harvard/iq/dataverse/export/ddi/dataset-perma-w-separator.json
  src/test/java/edu/harvard/iq/dataverse/export/ddi/dataset-perma-w-separator.xml
  src/test/java/edu/harvard/iq/dataverse/export/ddi/dataset-perma.json
  src/test/java/edu/harvard/iq/dataverse/export/ddi/dataset-perma.xml
  src/test/java/edu/harvard/iq/dataverse/pidproviders/PidUtilTest.java
Labels: Type: Bug, Size: 10, FY25 Sprint 8, FY25 Sprint 9, FY25 Sprint 10, FY25 Sprint 11, FY25 Sprint 12, FY25 Sprint 14, FY25 Sprint 15, FY25 Sprint 16

#10906 Optimize permission lookups for a user
  doc/release-notes/6467-optimize-permission-lookups-for-a-user.md
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/PermissionServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/api/Users.java
  src/main/java/edu/harvard/iq/dataverse/api/datadeposit/SWORDv2ServiceDocumentServlet.java
  src/main/java/edu/harvard/iq/dataverse/api/datadeposit/ServiceDocumentManagerImpl.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/GetUserPermittedCollectionsCommand.java
  src/test/java/edu/harvard/iq/dataverse/api/IpGroupsIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UsersIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: Type: Bug, Feature: Permissions, Size: 10, FY25 Sprint 7, FY25 Sprint 8, FY25 Sprint 9, FY25 Sprint 10, FY25 Sprint 12, FY25 Sprint 14, FY25 Sprint 15, FY25 Sprint 16

#11250 IQSS/11248-Update oauth lib to fix json-smart error
  pom.xml
Labels: Size: 3, FY25 Sprint 16, FY25 Sprint 17

#11258 News on Support for External Vocabulary Services
  doc/release-notes/11256-news-on-support-for-external-vocabulary.md
Labels: Size: 0.5

#11225 Flaky XmlMetadataTemplateTest fix
  src/main/java/edu/harvard/iq/dataverse/pidproviders/doi/XmlMetadataTemplate.java
Labels: Size: 3, FY25 Sprint 17

#11266 index after file ingest
  src/main/java/edu/harvard/iq/dataverse/ingest/IngestMessageBean.java
  src/test/java/edu/harvard/iq/dataverse/api/SearchIT.java
Labels: Type: Bug, Size: 10, SPA, GREI Re-arch, SPA.Q1, FY25 Sprint 17

#11201 explain how to customize root collection in "running in Docker" tutorial
  doc/release-notes/10541-root-alias-name2.md
  doc/sphinx-guides/source/container/running/demo.rst
  modules/container-configbaker/scripts/bootstrap/demo/init.sh
Labels: Component: Containers, Size: 3, FY25 Sprint 16, FY25 Sprint 17

#11269 IQSS/11264 - Add pseudo-exponential backoff to dataset page refresh
  doc/release-notes/11264-slower refresh for long running locks.md
  src/main/webapp/dataset.xhtml
Labels: GDCC: QDR, Size: 3

#11180 Fix sorting of dataset drafts and minor versions when sorting by "newest first"
  doc/release-notes/11178-bug-fix-sort-by-newest-first.md
  src/main/java/edu/harvard/iq/dataverse/search/IndexServiceBean.java
  src/test/java/edu/harvard/iq/dataverse/api/DataRetrieverApiIT.java
Labels: Size: 3, FY25 Sprint 15, FY25 Sprint 16, FY25 Sprint 17

#11260 #11208 fix update fmd api
  src/main/java/edu/harvard/iq/dataverse/api/Files.java
  src/test/java/edu/harvard/iq/dataverse/api/FilesIT.java
Labels: Size: 3, FY25 Sprint 17

#11263 Copy labels from issue to pull request
  .github/workflows/copy_labels.yml
Labels: Component: Code Infrastructure, Size: 0.5, FY25 Sprint 17

#11230 Delete Files From Dataset
  doc/release-notes/11230-deleteFiles api call.md
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: GDCC: DANS, Size: 3, SPA, FY25 Sprint 16, FY25 Sprint 17

#11236 DOI Publishing Bug Fix
  doc/release-notes/11234-DOI Publishing Bug.md
  src/main/java/edu/harvard/iq/dataverse/pidproviders/doi/XmlMetadataTemplate.java
  src/test/java/edu/harvard/iq/dataverse/pidproviders/doi/datacite/XmlMetadataTemplateTest.java
Labels: Size: 3, FY25 Sprint 16, FY25 Sprint 17

#11229 IQSS/11228 Summary Fields fixes
  doc/release-notes/11228-summaryfields.md
  doc/sphinx-guides/source/installation/config.rst
  src/main/java/edu/harvard/iq/dataverse/dataset/DatasetUtil.java
  src/main/webapp/dataset.xhtml
Labels: Size: 0.5, FY25 Sprint 16, FY25 Sprint 17

#11286 clarify direct children only when using returnChildCount=true
  doc/release-notes/11255-get-dataverse-api-return-child-count.md
  doc/sphinx-guides/source/api/native-api.rst
Labels: Size: 0.5, FY25 Sprint 17

#11279 Fix the order of fields on the AdvancedSearch Page
  doc/release-notes/11272-fix-order-on-advancedsearchpage.md
  src/main/java/edu/harvard/iq/dataverse/DatasetFieldServiceBean.java
Labels: Size: 3, FY25 Sprint 17

#11241 update link to Data Explorer, incorporate Data Curation Tool
  doc/sphinx-guides/source/_static/admin/dataverse-external-tools.tsv
Labels: Size: 0.5

#11216 document need for vacuum full in custom format
  doc/sphinx-guides/source/admin/troubleshooting.rst
Labels: Size: 0.5

#10713 Solr 9.8.0 and other lib updates from QDR
  .env
  conf/solr/schema.xml
  conf/solr/solrconfig.xml
  doc/release-notes/10713-Solr9.8.0 and lib updates.md
  doc/release-notes/11095-fix-extcvoc-indexing.md
  doc/release-notes/11113-avoid-orphan-perm-docs.md
  doc/sphinx-guides/source/_static/installation/files/etc/init.d/solr
  doc/sphinx-guides/source/_static/installation/files/etc/systemd/solr.service
  doc/sphinx-guides/source/developers/classic-dev-env.rst
  doc/sphinx-guides/source/installation/prerequisites.rst
  docker/compose/demo/compose.yml
  modules/dataverse-parent/pom.xml
  pom.xml
Labels: Type: Feature, Size: 3, FY25 Sprint 16, FY25 Sprint 17

#11203 Request Access fixes
  doc/release-notes/11203-request-access-fixes.md
  src/main/java/propertyFiles/Bundle.properties
  src/main/webapp/guestbook-terms-popup-fragment.xhtml
Labels: Size: 10, FY25 Sprint 16, FY25 Sprint 17

#9302 add custom license for France to the Dataverse Doc
  doc/release-notes/9302-add-Etalab-License.md
  doc/sphinx-guides/source/installation/config.rst
  scripts/api/data/licenses/licenseEtalab-2.0.json
Labels: Type: Feature, Feature: Terms & Licensing, Size: 3, FY25 Sprint 18

#11189 File metrics fixes
  doc/release-notes/Metrics-FixFileAPIs.md
  src/main/java/edu/harvard/iq/dataverse/metrics/MetricsServiceBean.java
Labels: Size: 10, FY25 Sprint 15, FY25 Sprint 16, FY25 Sprint 17, FY25 Sprint 18

#11224 10476 display on create field option
  doc/release-notes/10476-display-on-create-field-option.md
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/DatasetFieldServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/DatasetPage.java
  src/main/java/edu/harvard/iq/dataverse/Dataverse.java
  src/main/java/edu/harvard/iq/dataverse/DataverseFieldTypeInputLevel.java
  src/main/java/edu/harvard/iq/dataverse/DataverseFieldTypeInputLevelServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/DataversePage.java
  src/main/java/edu/harvard/iq/dataverse/DataverseServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/MetadataBlockServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/TemplatePage.java
  src/main/java/edu/harvard/iq/dataverse/api/Dataverses.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java
  src/test/java/edu/harvard/iq/dataverse/api/DataversesIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: NIH CAFE, FY25 Sprint 16, FY25 Sprint 17, FY25 Sprint 18

#10626 added archival.tsv metadata block
  doc/release-notes/10626-archival-tsv.md
  doc/sphinx-guides/source/user/appendix.rst
  scripts/api/data/metadatablocks/archival.tsv
  src/main/java/propertyFiles/archival.properties
Labels: Type: Feature, Size: 3, FY25 Sprint 18

#11247 11188 API to get list of dataset versions with summary of differences
  doc/release-notes/11188-dataset-version-api.md
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/DatasetVersionDifference.java
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/main/webapp/dataset-versions.xhtml
  src/test/java/edu/harvard/iq/dataverse/DatasetVersionDifferenceTest.java
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: Size: 3, SPA, GREI Re-arch, SPA.Q1.2, FY25 Sprint 16, FY25 Sprint 17, FY25 Sprint 18

#11215 update docs to PostgreSQL 16
  doc/release-notes/11212-postgresql-16.md
  doc/sphinx-guides/source/developers/classic-dev-env.rst
  doc/sphinx-guides/source/installation/installation-main.rst
  doc/sphinx-guides/source/installation/prerequisites.rst
  scripts/installer/README_python.txt
Labels: Size: 3, FY25 Sprint 18

#11232 IQSS/10883-License Enhancements
  doc/release-notes/10883-license improvements.md
  doc/sphinx-guides/source/_static/api/add-license.json
  doc/sphinx-guides/source/api/native-api.rst
  scripts/api/data/licenses/licenseApache-2.0.json
  scripts/api/data/licenses/licenseCC-BY-4.0.json
  scripts/api/data/licenses/licenseCC-BY-NC-4.0.json
  scripts/api/data/licenses/licenseCC-BY-NC-ND-4.0.json
  scripts/api/data/licenses/licenseCC-BY-NC-SA-4.0.json
  scripts/api/data/licenses/licenseCC-BY-ND-4.0.json
  scripts/api/data/licenses/licenseCC-BY-SA-4.0.json
  scripts/api/data/licenses/licenseCC0-1.0.json
  scripts/api/data/licenses/licenseMIT.json
  src/main/java/edu/harvard/iq/dataverse/license/License.java
  src/main/java/edu/harvard/iq/dataverse/pidproviders/doi/XmlMetadataTemplate.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java
  src/main/resources/db/migration/V6.5.0.5.sql
  src/test/java/edu/harvard/iq/dataverse/api/LicensesIT.java
  src/test/resources/json/license.json
Labels: Size: 10, FY25 Sprint 18
