Repository IQSS/dataverse, pull requests merged in 2025-09, with the labels that each got.

#11779 IQSS/11776 indexing new files
  doc/release-notes/11776- index fix.md
  src/main/java/edu/harvard/iq/dataverse/FileMetadata.java
  src/main/java/edu/harvard/iq/dataverse/search/IndexServiceBean.java
  src/test/java/edu/harvard/iq/dataverse/api/SearchIT.java
Labels: Type: Bug, Size: 3

#11788 Update aws sdk version
  modules/dataverse-parent/pom.xml
Labels: Size: 0.5

#11792 TKLabel flag not documented in #11294
  doc/sphinx-guides/source/installation/config.rst
Labels: Size: 0.5

#11780 IQSS/11778 speedup custom file retrieval
  src/main/java/edu/harvard/iq/dataverse/CustomizationFilesServlet.java
  src/main/java/edu/harvard/iq/dataverse/util/FileUtil.java
Labels: Size: 3

#11769 Docs: add Open OnDemand/OnDemand Loop integration
  doc/release-notes/11768-ood.md
  doc/sphinx-guides/source/_static/admin/dataverse-external-tools.tsv
  doc/sphinx-guides/source/admin/integrations.rst
  doc/sphinx-guides/source/api/apps.rst
Labels: Size: 0.5, FY26 Sprint 5

#11607 Fix for flac, tab full-text indexing fails
  modules/dataverse-parent/pom.xml
  pom.xml
Labels: Size: 3

#11760 Add API to get tool launch url for SPA
  doc/release-notes/11760-tool url apis.md
  doc/sphinx-guides/source/api/changelog.rst
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/FilePage.java
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/main/java/edu/harvard/iq/dataverse/api/ExternalToolsApi.java
  src/main/java/edu/harvard/iq/dataverse/api/Files.java
  src/main/java/edu/harvard/iq/dataverse/api/TestApi.java
  src/main/java/edu/harvard/iq/dataverse/externaltools/ExternalTool.java
  src/test/java/edu/harvard/iq/dataverse/api/ExternalToolsIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
  src/test/java/edu/harvard/iq/dataverse/externaltools/ExternalToolTest.java
Labels: Size: 3, SPA, GREI Re-arch, FY26 Sprint 5, SPA.Q3.2025.10

#11681 11525 retrieve collections a user can create datasets in
  doc/release-notes/11525-retrieve-collections-a-user-can-create-datasets-in.md
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/PermissionServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/api/Users.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/GetUserPermittedCollectionsCommand.java
  src/main/java/edu/harvard/iq/dataverse/mydata/DataRetrieverAPI.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java
  src/main/java/propertyFiles/Bundle.properties
  src/test/java/edu/harvard/iq/dataverse/api/DataRetrieverApiIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UsersIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
  src/test/java/edu/harvard/iq/dataverse/engine/command/impl/GetUserPermittedCollectionsCommandTest.java
  src/test/java/edu/harvard/iq/dataverse/util/json/JsonPrinterTest.java
Labels: Type: Feature, User Role: API User, Size: 30, SPA, GREI Re-arch, Original size: 30, FY26 Sprint 2, FY26 Sprint 3, FY26 Sprint 4, FY26 Sprint 5

#11846 update base image version for post-6.8 release
  modules/dataverse-parent/pom.xml
Labels: Size: 3, FY26 Sprint 6, FY26 Sprint 7

#11849 docs: update dataverse-ansible links in guides
  doc/sphinx-guides/source/admin/monitoring.rst
  doc/sphinx-guides/source/api/external-tools.rst
  doc/sphinx-guides/source/developers/deployment.rst
  doc/sphinx-guides/source/developers/testing.rst
  doc/sphinx-guides/source/installation/prep.rst
Labels: Feature: Developer Guide, Size: 0.5

#11853 Typos in container documentation
  doc/sphinx-guides/source/container/app-image.rst
  modules/container-base/README.md
  modules/container-configbaker/README.md
  src/main/docker/README.md
Labels: Component: Containers, Feature: Container Guide, Size: 0.5

#11784 IQSS/11783 Curation Status fixes
  doc/release-notes/11783-Curation-Status-fixes.md
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/CuratePublishedDatasetVersionCommand.java
  src/main/webapp/dataset.xhtml
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
Labels: Size: 3, FY26 Sprint 5, FY26 Sprint 6, FY26 Sprint 7

#11748 11387 fix input level api
  doc/release-notes/11387-modify-input-level-api.md
  doc/sphinx-guides/source/api/changelog.rst
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/AbstractWriteDataverseCommand.java
  src/test/java/edu/harvard/iq/dataverse/api/DataversesIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
  src/test/java/edu/harvard/iq/dataverse/engine/command/impl/CreateDataverseCommandTest.java
Labels: Type: Bug, Size: 10, FY26 Sprint 4, FY26 Sprint 5, FY26 Sprint 6, FY26 Sprint 7
