Repository IQSS/dataverse, pull requests merged in 2025-06, with the labels that each got.

#11499 adding type and dvObject to dataverse featured items
  doc/release-notes/11414-add-dvobject-type-to-featured-items.md
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/Dataverse.java
  src/main/java/edu/harvard/iq/dataverse/DvObject.java
  src/main/java/edu/harvard/iq/dataverse/api/AbstractApiBean.java
  src/main/java/edu/harvard/iq/dataverse/api/DataverseFeaturedItems.java
  src/main/java/edu/harvard/iq/dataverse/api/Dataverses.java
  src/main/java/edu/harvard/iq/dataverse/api/dto/AbstractDataverseFeaturedItemDTO.java
  src/main/java/edu/harvard/iq/dataverse/api/dto/NewDataverseFeaturedItemDTO.java
  src/main/java/edu/harvard/iq/dataverse/api/dto/UpdatedDataverseFeaturedItemDTO.java
  src/main/java/edu/harvard/iq/dataverse/dataverse/featured/DataverseFeaturedItem.java
  src/main/java/edu/harvard/iq/dataverse/dataverse/featured/DataverseFeaturedItemServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/AbstractWriteDataverseFeaturedItemCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/CreateDataverseFeaturedItemCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/DeaccessionDatasetVersionCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/DeleteDataverseCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/RestrictFileCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/UpdateDataverseFeaturedItemCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/UpdateDataverseFeaturedItemsCommand.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java
  src/main/java/propertyFiles/Bundle.properties
  src/main/resources/db/migration/V6.5.0.13.sql
  src/test/java/edu/harvard/iq/dataverse/api/DataverseFeaturedItemsIT.java
  src/test/java/edu/harvard/iq/dataverse/api/DataversesIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
  src/test/java/edu/harvard/iq/dataverse/engine/command/impl/CreateDataverseFeaturedItemCommandTest.java
  src/test/java/edu/harvard/iq/dataverse/engine/command/impl/RestrictFileCommandTest.java
  src/test/java/edu/harvard/iq/dataverse/featured/DataverseFeaturedItemTest.java
Labels: Type: Feature, SPA, GREI Re-arch, Size: 50, Original size: 50, SPA.Q2.3, FY25 Sprint 23, FY25 Sprint 24

#11489 MDC: script updates for counter-processor-1.06+
  doc/release-notes/11489-CPUpdates.md
  doc/sphinx-guides/source/_static/util/counter_daily.sh
  doc/sphinx-guides/source/_static/util/counter_weekly.sh
  doc/sphinx-guides/source/admin/make-data-count.rst
Labels: Size: 3, GREI 4, FY25 Sprint 23, FY25 Sprint 24

#11407 Prevent needless optimistic lock exception for role assignment removal
  src/main/java/edu/harvard/iq/dataverse/RoleAssignment.java
Labels: Feature: Permissions, Size: 3, FY25 Sprint 20, FY25 Sprint 21, FY25 Sprint 22, FY25 Sprint 23, FY25 Sprint 24

#11487 Fix @AutoService classes not being loaded at runtime when using JDK23+ for compilation
  doc/sphinx-guides/source/developers/dev-environment.rst
  doc/sphinx-guides/source/installation/prerequisites.rst
  pom.xml
Labels: Type: Bug, Component: Code Infrastructure, Feature: Developer Guide, Size: 0.5

#11454 Filter Improvements
  doc/release-notes/Filter-efficiency.md
  doc/sphinx-guides/source/installation/config.rst
  modules/container-configbaker/scripts/bootstrap/demo/init.sh
  src/main/java/edu/harvard/iq/dataverse/api/Admin.java
  src/main/java/edu/harvard/iq/dataverse/api/ApiBlockingFilter.java
  src/main/java/edu/harvard/iq/dataverse/api/ApiConfiguration.java
  src/main/java/edu/harvard/iq/dataverse/api/ApiRouter.java
  src/main/java/edu/harvard/iq/dataverse/api/BuiltinUsers.java
  src/main/java/edu/harvard/iq/dataverse/api/filter/ApiBlockingFilter.java
  src/main/java/edu/harvard/iq/dataverse/api/util/JsonResponseBuilder.java
  src/main/java/edu/harvard/iq/dataverse/filter/CorsFilter.java
  src/main/java/edu/harvard/iq/dataverse/settings/JvmSettings.java
  src/main/java/edu/harvard/iq/dataverse/settings/SettingsServiceBean.java
  src/main/webapp/WEB-INF/web.xml
  src/test/java/edu/harvard/iq/dataverse/api/util/JsonResponseBuilderTest.java
Labels: Size: 10, FY25 Sprint 22, FY25 Sprint 23, FY25 Sprint 24

#11477 Change CI workflows to release tagged container images for Dataverse
  .github/CODEOWNERS
  .github/workflows/container_app_pr.yml
  .github/workflows/container_app_push.yml
  .github/workflows/container_base_push.yml
  .github/workflows/container_maintenance.yml
  .github/workflows/guides_build_sphinx.yml
  .github/workflows/maven_unit_test.yml
  .github/workflows/scripts/containers/maintain-application.sh
  .github/workflows/scripts/containers/maintain-base.sh
  .github/workflows/scripts/containers/maintain-configbaker.sh
  .github/workflows/scripts/containers/utils.sh
  doc/release-notes/10618-app-image-tags.md
  doc/sphinx-guides/requirements.txt
  doc/sphinx-guides/source/conf.py
  doc/sphinx-guides/source/container/app-image.rst
  doc/sphinx-guides/source/container/base-image.rst
  doc/sphinx-guides/source/container/configbaker-image.rst
  doc/sphinx-guides/source/container/running/demo.rst
  doc/sphinx-guides/source/container/running/production.rst
  doc/sphinx-guides/source/developers/making-releases.rst
  doc/sphinx-guides/source/versions.rst
  docker/compose/demo/compose.yml
  modules/container-base/README.md
  modules/container-configbaker/Dockerfile
  modules/container-configbaker/README.md
  modules/container-configbaker/backports/v6.4/001-parent-pom.xml.patch
  modules/container-configbaker/backports/v6.4/002-pom.xml.patch
  modules/container-configbaker/backports/v6.5/001-parent-pom.xml.patch
  modules/container-configbaker/backports/v6.5/002-pom.xml.patch
  modules/container-configbaker/backports/v6.6/001-parent-pom.xml.patch
  modules/container-configbaker/backports/v6.6/002-pom.xml.patch
  modules/dataverse-parent/pom.xml
  pom.xml
  renovate.json5
  src/backports/README.md
  src/backports/v6.4/001-parent-pom.xml.patch
  src/backports/v6.4/002-pom.xml.patch
  src/backports/v6.5/001-parent-pom.xml.patch
  src/backports/v6.5/002-pom.xml.patch
  src/backports/v6.6/001-parent-pom.xml.patch
  src/backports/v6.6/002-pom.xml.patch
  src/main/docker/Dockerfile
  src/main/docker/README.md
Labels: Component: Code Infrastructure, Feature: Developer Guide, Component: Containers, Feature: Container Guide, Release, FY25 Sprint 24, FY25 Sprint 25

#11301 blocked deposit page, hide host field when only one collection (e.g. root)
  doc/release-notes/11301-blocked-deposit-page.md
  src/main/java/edu/harvard/iq/dataverse/DatasetPage.java
  src/main/java/edu/harvard/iq/dataverse/DataverseConverter.java
  src/main/webapp/dataset.xhtml
Labels: Size: 3, FY25 Sprint 18, FY25 Sprint 19, FY25 Sprint 20, FY25 Sprint 21, FY25 Sprint 22, FY25 Sprint 23, FY25 Sprint 24, FY25 Sprint 25

#11494 Full-text Indexing Fixes
  src/main/java/edu/harvard/iq/dataverse/dataaccess/GlobusOverlayAccessIO.java
  src/main/java/edu/harvard/iq/dataverse/dataaccess/StorageIO.java
  src/main/java/edu/harvard/iq/dataverse/search/IndexServiceBean.java
Labels: Size: 3, FY25 Sprint 23, FY25 Sprint 24, FY25 Sprint 25

#11560 New API Endpoint for retrieving user selectable roles
  doc/release-notes/11434-api-selectable-roles.md
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/RoleAssigneeServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/api/Roles.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java
  src/main/java/propertyFiles/Bundle.properties
  src/test/java/edu/harvard/iq/dataverse/api/RolesIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: Size: 3, SPA, GREI Re-arch, Original size: 3, SPA.Q2.1, FY25 Sprint 25, FY25 Sprint 26

#11475 Add CITATION.cff
  CITATION.cff
Labels: Type: Feature, Size: 3, FY25 Sprint 23, FY25 Sprint 24, FY25 Sprint 25, FY25 Sprint 26

#11576 A fix for a recent bug in harvesting from some generic OAI archives
  src/main/java/edu/harvard/iq/dataverse/api/imports/ImportGenericServiceBean.java
Labels: Type: Bug, Feature: Harvesting, Size: 3, FY25 Sprint 25, FY25 Sprint 26

#11518 OJS 3 is now supported (and OPS)
  doc/release-notes/11518-ojs3.md
  doc/sphinx-guides/source/admin/integrations.rst
  doc/sphinx-guides/source/api/apps.rst
Labels: FY25 Sprint 24, FY25 Sprint 25, FY25 Sprint 26

#11520 Feature to limit file uploads to datasets
  doc/release-notes/11275-add-limit-to-number-of-dataset-files.md
  doc/sphinx-guides/source/api/native-api.rst
  doc/sphinx-guides/source/installation/config.rst
  scripts/search/tests/data/dataset-finch1-fileLimit.json
  src/main/java/edu/harvard/iq/dataverse/Dataset.java
  src/main/java/edu/harvard/iq/dataverse/DatasetPage.java
  src/main/java/edu/harvard/iq/dataverse/DatasetServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/DvObject.java
  src/main/java/edu/harvard/iq/dataverse/DvObjectContainer.java
  src/main/java/edu/harvard/iq/dataverse/EditDatafilesPage.java
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/main/java/edu/harvard/iq/dataverse/api/datadeposit/MediaResourceManagerImpl.java
  src/main/java/edu/harvard/iq/dataverse/api/dto/DatasetDTO.java
  src/main/java/edu/harvard/iq/dataverse/api/dto/DataverseDTO.java
  src/main/java/edu/harvard/iq/dataverse/datasetutility/AddReplaceFileHelper.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/CreateNewDataFilesCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/UpdateDataverseCommand.java
  src/main/java/edu/harvard/iq/dataverse/ingest/IngestServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/settings/JvmSettings.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonParser.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinterHelper.java
  src/main/java/edu/harvard/iq/dataverse/util/json/NullSafeJsonBuilder.java
  src/main/java/propertyFiles/Bundle.properties
  src/main/resources/db/migration/V6.6.0.1.sql
  src/main/webapp/editFilesFragment.xhtml
  src/test/java/edu/harvard/iq/dataverse/DataverseTest.java
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
  src/test/java/edu/harvard/iq/dataverse/api/DataversesIT.java
  src/test/java/edu/harvard/iq/dataverse/api/FilesIT.java
  src/test/java/edu/harvard/iq/dataverse/api/S3AccessIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
  src/test/java/edu/harvard/iq/dataverse/engine/command/impl/CreateNewDataFilesTest.java
  src/test/java/edu/harvard/iq/dataverse/util/json/JsonPrinterTest.java
Labels: Type: Feature, Size: 80, D: Dataset: large number of files, GREI 5, FY25 Sprint 23, FY25 Sprint 24, FY25 Sprint 25, FY25 Sprint 26

#11584 11542 get file count pg 2
  src/main/java/edu/harvard/iq/dataverse/api/Search.java
Labels: Type: Bug, Size: 3, SPA, GREI Re-arch, Original size: 3, FY25 Sprint 25, FY25 Sprint 26

#11589 Add datasetType to JSON serialization of DatasetVersion
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java
  src/test/java/edu/harvard/iq/dataverse/util/json/JsonPrinterTest.java
Labels: Size: 0.5, FY25 Sprint 26

#11595 Fix for #11268
  src/main/webapp/dataset.xhtml
Labels: Size: 3

#11294 TKLabels v2 implementation
  doc/release-notes/TKLabels.md
  doc/sphinx-guides/source/installation/config.rst
  doc/sphinx-guides/source/installation/img/LCDemo.png
  doc/sphinx-guides/source/installation/index.rst
  doc/sphinx-guides/source/installation/localcontexts.rst
  doc/sphinx-guides/source/user/appendix.rst
  src/main/java/edu/harvard/iq/dataverse/api/LocalContexts.java
  src/main/java/edu/harvard/iq/dataverse/settings/FeatureFlags.java
  src/main/java/edu/harvard/iq/dataverse/settings/JvmSettings.java
  src/test/java/edu/harvard/iq/dataverse/api/LocalContextsIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: Size: 10, GREI 5, FY25 Sprint 21, FY25 Sprint 22, FY25 Sprint 23, FY25 Sprint 24, FY25 Sprint 25, FY25 Sprint 26

#11596 #11546 fix compare separator logic
  src/main/java/edu/harvard/iq/dataverse/pidproviders/AbstractPidProvider.java
Labels: Type: Bug, Size: 3, FY25 Sprint 26
