Repository IQSS/dataverse, pull requests merged in 2025-03, with the labels that each got.

#11297 docs: update DataCite metadata reference from 4.0 to 4.5
  doc/sphinx-guides/source/user/appendix.rst
Labels: Size: 0.5, FY25 Sprint 18

#11304 Create V6.5.0.6.sql
  src/main/resources/db/migration/V6.5.0.6.sql
Labels: Type: Bug

#11246 IQSS/11242 ExternalIdentifier fix
  doc/release-notes/11242-fix-oricid-recognition.md
  doc/sphinx-guides/source/user/dataset-management.rst
  src/main/java/edu/harvard/iq/dataverse/DatasetAuthor.java
  src/main/java/edu/harvard/iq/dataverse/DatasetFieldValueValidator.java
  src/main/java/edu/harvard/iq/dataverse/ExternalIdentifier.java
  src/main/java/edu/harvard/iq/dataverse/pidproviders/doi/XmlMetadataTemplate.java
  src/test/java/edu/harvard/iq/dataverse/DatasetFieldValueValidatorTest.java
  src/test/java/edu/harvard/iq/dataverse/ExternalIdentifierTest.java
  src/test/java/edu/harvard/iq/dataverse/pidproviders/doi/datacite/XmlMetadataTemplateTest.java
Labels: Size: 3, GDCC:ORCID, FY25 Sprint 17, FY25 Sprint 18

#11217 10217 source name harvesting client
  doc/release-notes/11217-source-name-harvesting-client.md
  doc/sphinx-guides/source/_static/api/harvesting-client.json
  doc/sphinx-guides/source/api/native-api.rst
  doc/sphinx-guides/source/installation/config.rst
  docker-compose-dev.yml
  src/main/java/edu/harvard/iq/dataverse/HarvestingClientsPage.java
  src/main/java/edu/harvard/iq/dataverse/api/HarvestingClients.java
  src/main/java/edu/harvard/iq/dataverse/harvest/client/HarvestingClient.java
  src/main/java/edu/harvard/iq/dataverse/search/IndexServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonParser.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java
  src/main/java/propertyFiles/Bundle.properties
  src/main/resources/db/migration/V6.5.0.7.sql
  src/main/webapp/harvestclients.xhtml
  src/test/java/edu/harvard/iq/dataverse/api/HarvestingClientsIT.java
Labels: Feature: Harvesting, Size: 10, GREI 3, FY25 Sprint 18

#11011 10909 Support for OAI-PMH harvesting from DataCite
  doc/release-notes/10909-datacite-oai-harvesting.md
  doc/sphinx-guides/source/admin/harvestclients.rst
  doc/sphinx-guides/source/api/native-api.rst
  local_lib/io/gdcc/xoai-common/5.3.2-local/xoai-common-5.3.2-local.jar
  local_lib/io/gdcc/xoai-common/5.3.2-local/xoai-common-5.3.2-local.pom
  local_lib/io/gdcc/xoai-data-provider/5.3.2-local/xoai-data-provider-5.3.2-local.jar
  local_lib/io/gdcc/xoai-data-provider/5.3.2-local/xoai-data-provider-5.3.2-local.pom
  local_lib/io/gdcc/xoai-service-provider/5.3.2-local/xoai-service-provider-5.3.2-local.jar
  local_lib/io/gdcc/xoai-service-provider/5.3.2-local/xoai-service-provider-5.3.2-local.pom
  local_lib/io/gdcc/xoai-xmlio/5.3.2-local/xoai-xmlio-5.3.2-local.jar
  local_lib/io/gdcc/xoai-xmlio/5.3.2-local/xoai-xmlio-5.3.2-local.pom
  local_lib/io/gdcc/xoai/5.3.2-local/xoai-5.3.2-local.pom
  modules/dataverse-parent/pom.xml
  src/main/java/edu/harvard/iq/dataverse/api/dto/MetadataBlockDTO.java
  src/main/java/edu/harvard/iq/dataverse/api/imports/ImportGenericServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/api/imports/ImportServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/harvest/client/FastGetRecord.java
  src/main/java/edu/harvard/iq/dataverse/harvest/client/HarvesterServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/harvest/client/HarvestingClient.java
  src/main/java/edu/harvard/iq/dataverse/harvest/client/oai/OaiHandler.java
  src/main/java/edu/harvard/iq/dataverse/search/SearchServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonParser.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java
  src/main/resources/db/migration/V6.5.0.8.sql
  src/main/webapp/editFilesFragment.xhtml
  src/main/webapp/search-include-fragment.xhtml
  src/test/java/edu/harvard/iq/dataverse/api/HarvestingClientsIT.java
Labels: FY25 Sprint 17, FY25 Sprint 18

#11282 Native API - Get Dataset Download Count endpoint
  doc/release-notes/11244-get-dataset-download-count-api.md
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: Type: Feature, Size: 10, SPA, GREI Re-arch, SPA.Q1.4, FY25 Sprint 17, FY25 Sprint 18

#11163 CSL Citation support
  doc/release-notes/11163-CSL citation formats.md
  doc/sphinx-guides/source/api/native-api.rst
  doc/sphinx-guides/source/installation/config.rst
  doc/sphinx-guides/source/user/find-use-data.rst
  pom.xml
  src/main/java/edu/harvard/iq/dataverse/DataCitation.java
  src/main/java/edu/harvard/iq/dataverse/DatasetPage.java
  src/main/java/edu/harvard/iq/dataverse/DatasetVersion.java
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/main/java/edu/harvard/iq/dataverse/api/Pids.java
  src/main/java/edu/harvard/iq/dataverse/pidproviders/AbstractPidProvider.java
  src/main/java/edu/harvard/iq/dataverse/pidproviders/PidProvider.java
  src/main/java/edu/harvard/iq/dataverse/pidproviders/doi/datacite/DataCiteDOIProvider.java
  src/main/java/edu/harvard/iq/dataverse/settings/JvmSettings.java
  src/main/java/edu/harvard/iq/dataverse/util/CSLUtil.java
  src/main/java/propertyFiles/Bundle.properties
  src/main/webapp/dataset-citation.xhtml
  src/main/webapp/dataset.xhtml
  src/main/webapp/resources/css/structure.css
  src/main/webapp/resources/js/clipboard.min.js
Labels: GDCC: DANS, GDCC: QDR, Size: 10, FY25 Sprint 18

#11277 MDC Adding server to processing state table to allow the processing script to run on multiple servers
  doc/sphinx-guides/source/_static/admin/counter-processor-config.yaml
  doc/sphinx-guides/source/_static/util/counter_daily.sh
  doc/sphinx-guides/source/admin/make-data-count.rst
  doc/sphinx-guides/source/developers/make-data-count.rst
  doc/sphinx-guides/source/installation/prerequisites.rst
  src/main/java/edu/harvard/iq/dataverse/api/MakeDataCountApi.java
  src/main/java/edu/harvard/iq/dataverse/makedatacount/MakeDataCountProcessState.java
  src/main/java/edu/harvard/iq/dataverse/makedatacount/MakeDataCountProcessStateServiceBean.java
  src/main/resources/db/migration/V6.5.0.10.sql
  src/test/java/edu/harvard/iq/dataverse/api/MakeDataCountApiIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: Feature: Metrics + Reports, Size: 3, FY25 Sprint 17, FY25 Sprint 18

#11302 update etalab license to use the new JSON format
  doc/release-notes/9302-add-Etalab-License.md
  scripts/api/data/licenses/licenseEtalab-2.0.json
Labels: Size: 3

#11289 document behavior of Preview tab with regard to default license
  doc/sphinx-guides/source/user/dataset-management.rst
Labels: Size: 0.5, FY25 Sprint 17, FY25 Sprint 18

#11313 DANS/CSL - Fix create dataset bug
  src/main/webapp/dataset.xhtml
Labels: Size: 3

#11222 ORCID: Support authenticated ORCIDs in account profile
  doc/release-notes/11222-ORCID in profile.md
  doc/sphinx-guides/source/installation/index.rst
  doc/sphinx-guides/source/installation/oauth2.rst
  doc/sphinx-guides/source/installation/orcid.rst
  doc/sphinx-guides/source/user/account.rst
  src/main/java/edu/harvard/iq/dataverse/DatasetPage.java
  src/main/java/edu/harvard/iq/dataverse/authorization/AuthUtil.java
  src/main/java/edu/harvard/iq/dataverse/authorization/AuthenticatedUserDisplayInfo.java
  src/main/java/edu/harvard/iq/dataverse/authorization/AuthenticationProvider.java
  src/main/java/edu/harvard/iq/dataverse/authorization/AuthenticationProvidersRegistrationServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/authorization/AuthenticationServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/authorization/providers/AuthenticationProviderRow.java
  src/main/java/edu/harvard/iq/dataverse/authorization/providers/builtin/BuiltinAuthenticationProvider.java
  src/main/java/edu/harvard/iq/dataverse/authorization/providers/builtin/DataverseUserPage.java
  src/main/java/edu/harvard/iq/dataverse/authorization/providers/oauth2/OAuth2FirstLoginPage.java
  src/main/java/edu/harvard/iq/dataverse/authorization/providers/oauth2/OAuth2LoginBackingBean.java
  src/main/java/edu/harvard/iq/dataverse/authorization/providers/oauth2/impl/GitHubOAuth2AP.java
  src/main/java/edu/harvard/iq/dataverse/authorization/providers/oauth2/impl/GoogleOAuth2AP.java
  src/main/java/edu/harvard/iq/dataverse/authorization/providers/oauth2/impl/OrcidOAuth2AP.java
  src/main/java/edu/harvard/iq/dataverse/authorization/providers/oauth2/oidc/OIDCAuthProvider.java
  src/main/java/edu/harvard/iq/dataverse/authorization/providers/shib/ShibAuthenticationProvider.java
  src/main/java/edu/harvard/iq/dataverse/authorization/users/AuthenticatedUser.java
  src/main/java/propertyFiles/Bundle.properties
  src/main/resources/db/migration/V6.5.0.11.sql
  src/main/webapp/dataverseuser.xhtml
  src/main/webapp/loginpage.xhtml
  src/main/webapp/oauth2/firstLogin.xhtml
  src/main/webapp/oauth2/orcidConfirm.xhtml
  src/test/java/edu/harvard/iq/dataverse/api/AdminIT.java
  src/test/java/edu/harvard/iq/dataverse/authorization/AuthUtilTest.java
Labels: GDCC: QDR, Size: 10, GDCC:ORCID, FY25 Sprint 18

#11128 Upgrade to Payara 6 2025.2
  doc/release-notes/6.2025.2_update.md
  doc/sphinx-guides/source/developers/classic-dev-env.rst
  doc/sphinx-guides/source/developers/tips.rst
  doc/sphinx-guides/source/installation/prerequisites.rst
  doc/sphinx-guides/source/qa/test-automation.md
  modules/dataverse-parent/pom.xml
  src/main/java/edu/harvard/iq/dataverse/DatasetPage.java
  src/main/java/edu/harvard/iq/dataverse/DataverseSession.java
  src/main/webapp/ThemeAndWidgets.xhtml
  src/main/webapp/confirmemail.xhtml
  src/main/webapp/dashboard.xhtml
  src/main/webapp/dataset-widgets.xhtml
  src/main/webapp/dataset.xhtml
  src/main/webapp/dataverse.xhtml
  src/main/webapp/dataverse_homepage.xhtml
  src/main/webapp/dataverse_template.xhtml
  src/main/webapp/dataverseuser.xhtml
  src/main/webapp/editdatafiles.xhtml
  src/main/webapp/file.xhtml
  src/main/webapp/guestbook.xhtml
  src/main/webapp/mydata_page.xhtml
  src/main/webapp/passwordreset.xhtml
  src/main/webapp/previewurl.xhtml
  src/main/webapp/privateurl.xhtml
  src/main/webapp/role_permission_helper.xhtml
  src/main/webapp/search/advanced.xhtml
  src/main/webapp/superuser.xhtml
  src/main/webapp/template.xhtml
Labels: GDCC: QDR, Size: 10, FY25 Sprint 14, FY25 Sprint 15, FY25 Sprint 16, FY25 Sprint 17, FY25 Sprint 18

#11125 Globus support: download optimizations
  doc/release-notes/11057-globus-improvements.md
  doc/sphinx-guides/source/installation/config.rst
  src/main/java/edu/harvard/iq/dataverse/DatasetPage.java
  src/main/java/edu/harvard/iq/dataverse/FileDownloadHelper.java
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/main/java/edu/harvard/iq/dataverse/globus/ExpiredTokenException.java
  src/main/java/edu/harvard/iq/dataverse/globus/GlobusServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/globus/GlobusTaskInProgress.java
  src/main/java/edu/harvard/iq/dataverse/globus/GlobusTaskState.java
  src/main/java/edu/harvard/iq/dataverse/globus/GlobusUtil.java
  src/main/java/edu/harvard/iq/dataverse/globus/TaskMonitoringServiceBean.java
  src/main/webapp/filesFragment.xhtml
Labels: Size: 30, Feature: Globus, FY25 Sprint 17, FY25 Sprint 18

#11325 extend size of deaccessionlink column
  src/main/resources/db/migration/V6.5.0.9.sql
Labels: Type: Bug, GDCC: QDR, Size: 3, FY25 Sprint 18

#11326 DANS CSL - disable dialog in any edit mode
  src/main/java/edu/harvard/iq/dataverse/DatasetPage.java
  src/main/webapp/dataset.xhtml
Labels: Size: 3

#11329 Dashboard: fix npe from breadcrumbs
  src/main/webapp/dashboard-movedataset.xhtml
  src/main/webapp/dashboard-movedataverse.xhtml
  src/main/webapp/dashboard-users.xhtml
  src/main/webapp/harvestclients.xhtml
  src/main/webapp/harvestsets.xhtml
Labels: Size: 3, FY25 Sprint 18, FY25 Sprint 19

#11332 tweaks to harvest client docs
  doc/sphinx-guides/source/admin/harvestclients.rst
Labels: Size: 0.5, FY25 Sprint 18, FY25 Sprint 19

#11333 API Changelog: move version note to 6.6 where it belongs
  doc/sphinx-guides/source/api/changelog.rst
Labels: FY25 Sprint 19

#11334 API Guide: don't interleave "Dataset Version Notes" with "Dataset Types"
  doc/sphinx-guides/source/api/native-api.rst
Labels: FY25 Sprint 19

#11338 Clean up JSON CSL elements
  src/main/java/edu/harvard/iq/dataverse/DataCitation.java
Labels: Size: 3, FY25 Sprint 19

#11312 Metadata fields can be "display on create" per collection
  doc/release-notes/10476-display-on-create-field-option.md
  doc/sphinx-guides/source/_static/api/dataset-schema.json
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/DatasetFieldServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/DatasetFieldType.java
  src/main/java/edu/harvard/iq/dataverse/DatasetPage.java
  src/main/java/edu/harvard/iq/dataverse/Dataverse.java
  src/main/java/edu/harvard/iq/dataverse/DataverseFieldTypeInputLevel.java
  src/main/java/edu/harvard/iq/dataverse/DataverseFieldTypeInputLevelServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/DataversePage.java
  src/main/java/edu/harvard/iq/dataverse/DataverseServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/MetadataBlock.java
  src/main/java/edu/harvard/iq/dataverse/MetadataBlockServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/TemplatePage.java
  src/main/java/edu/harvard/iq/dataverse/api/DatasetFieldServiceApi.java
  src/main/java/edu/harvard/iq/dataverse/api/Dataverses.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/AbstractWriteDataverseCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/UpdateDataverseInputLevelsCommand.java
  src/main/java/edu/harvard/iq/dataverse/util/json/BriefJsonPrinter.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinterHelper.java
  src/main/webapp/metadataFragment.xhtml
  src/test/java/edu/harvard/iq/dataverse/api/DatasetTypesIT.java
  src/test/java/edu/harvard/iq/dataverse/api/DataversesIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
  src/test/java/edu/harvard/iq/dataverse/engine/command/impl/CreateDataverseCommandTest.java
  src/test/java/edu/harvard/iq/dataverse/util/json/JsonPrinterTest.java
Labels: Size: 3, NIH CAFE, FY25 Sprint 18, FY25 Sprint 19

#11343 DisplayOnCreate Fixes
  src/main/java/edu/harvard/iq/dataverse/DatasetFieldServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/DatasetFieldType.java
  src/main/java/edu/harvard/iq/dataverse/DatasetPage.java
  src/main/java/edu/harvard/iq/dataverse/Dataverse.java
  src/main/java/edu/harvard/iq/dataverse/DataverseFieldTypeInputLevel.java
  src/main/java/edu/harvard/iq/dataverse/DataversePage.java
  src/main/java/edu/harvard/iq/dataverse/DataverseServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/MetadataBlock.java
  src/main/java/edu/harvard/iq/dataverse/MetadataBlockServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/TemplatePage.java
  src/main/java/edu/harvard/iq/dataverse/api/Dataverses.java
  src/main/java/edu/harvard/iq/dataverse/util/json/BriefJsonPrinter.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java
  src/main/resources/db/migration/V6.5.0.12.sql
  src/main/webapp/metadataFragment.xhtml
  src/test/java/edu/harvard/iq/dataverse/api/DataversesIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
  src/test/java/edu/harvard/iq/dataverse/engine/command/impl/CreateDataverseCommandTest.java
Labels: Size: 10

#11290 Get Citation API docs: fix typo, link to version spec
  doc/sphinx-guides/source/api/native-api.rst
Labels: Feature: API Guide, Size: 0.5, FY25 Sprint 17, FY25 Sprint 18, FY25 Sprint 19

#9252 add CodeQL Github Action
  .github/workflows/codeql.yml
Labels: Type: Feature, Size: 10

#11181 add file previewers to dev env, more docs
  doc/release-notes/10506-previewers.md
  doc/sphinx-guides/source/container/running/demo.rst
  docker-compose-dev.yml
  docker/compose/demo/compose.yml
Labels: Component: Containers, Size: 3, FY25 Sprint 15, FY25 Sprint 16, FY25 Sprint 17, FY25 Sprint 18, FY25 Sprint 19

#11311 explain how to switch to (working) betatest NcML previewer
  doc/release-notes/11252-ncml.md
Labels: Type: Bug, Size: 3, NIH CAFE, FY25 Sprint 18, FY25 Sprint 19

#11273 Edit Metadata API endpoint - support empty values
  doc/release-notes/11243-editmetadata-api-extension.md
  doc/sphinx-guides/source/_static/api/dataset-edit-metadata-delete-fields-sample.json
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/DatasetFieldServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/EjbDataverseEngine.java
  src/main/java/edu/harvard/iq/dataverse/api/AbstractApiBean.java
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/main/java/edu/harvard/iq/dataverse/dataset/DatasetFieldsValidator.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/CommandContext.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/UpdateDatasetFieldsCommand.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonParser.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java
  src/main/java/propertyFiles/Bundle.properties
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
  src/test/java/edu/harvard/iq/dataverse/dataset/DatasetFieldsValidatorTest.java
  src/test/java/edu/harvard/iq/dataverse/engine/TestCommandContext.java
  src/test/java/edu/harvard/iq/dataverse/engine/command/impl/UpdateDatasetFieldsCommandTest.java
Labels: Size: 10, SPA, GREI Re-arch, Original size: 10, SPA.Q1, FY25 Sprint 18, FY25 Sprint 19

#11358 Metrics Fix
  src/main/java/edu/harvard/iq/dataverse/api/Metrics.java
  src/test/java/edu/harvard/iq/dataverse/api/MetricsIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: Size: 3, FY25 Sprint 19

#11362 Change to duplicate role assignment error message
  doc/release-notes/11191-assign-role-api-error-message.md
  src/main/java/propertyFiles/Bundle.properties
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
Labels: Type: Bug, Size: 3, FY25 Sprint 19

#11347 return all type totals regardless of types being returned
  doc/release-notes/11280-search-api-count-per-object.md
  src/main/java/edu/harvard/iq/dataverse/api/Search.java
  src/test/java/edu/harvard/iq/dataverse/api/SearchIT.java
Labels: Type: Bug, Size: 10, SPA, GREI Re-arch, Original size: 10, SPA.Q1, FY25 Sprint 18, FY25 Sprint 19

#11349 extending restrict api
  doc/release-notes/11299-file-restrict-api-extension.md
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/api/Files.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/RestrictFileCommand.java
  src/test/java/edu/harvard/iq/dataverse/api/FilesIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: Type: Feature, Size: 10, SPA, SPA: File Page, GREI Re-arch, Original size: 10, SPA.Q1.6, FY25 Sprint 19

#11354 11323 include deaccessioned versions in summary of compare dataset versions
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/DatasetVersionDifference.java
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: Size: 10, SPA, GREI Re-arch, Original size: 10, SPA.Q1.5, FY25 Sprint 19
