Repository IQSS/dataverse, pull requests merged in 2025-08, with the labels that each got.

#11715 Add VAST DataStore as a Reported Working S3-Compatible Storage
  doc/sphinx-guides/source/installation/config.rst
Labels: Feature: Installation Guide, Size: 0.5

#11702 fix file downloadSize/Count after revert
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
Labels: Type: Bug, Size: 3, SPA, GREI Re-arch, FY24 Sprint 23, Original size: 10, FY25 Sprint 24, FY26 Sprint 1, FY26 Sprint 3

#11713 avoid external resource for a unit test
  src/test/java/edu/harvard/iq/dataverse/dataaccess/RemoteOverlayAccessIOTest.java
Labels: Size: 3

#11723 Install `bc` in configbaker image so conf/solr/update-fields.sh will run
  conf/solr/update-fields.sh
  doc/release-notes/11722-configbaker-bc-missing.md
  modules/container-configbaker/Dockerfile
Labels: Type: Bug, Component: Containers, Size: 0.5, SPA

#11728 extend list dataverse collection links api
  doc/release-notes/11724-extend-list-dataverse-collection-links.md
  src/main/java/edu/harvard/iq/dataverse/api/Dataverses.java
  src/test/java/edu/harvard/iq/dataverse/api/LinkIT.java
Labels: Size: 3, SPA, GREI Re-arch, Original size: 3, SPA.Q3.2025.2, FY26 Sprint 3, FY26 Sprint 4

#11618 In ExportDataProvider, add directoryLabel (file path) to getDatasetFileDetails
  doc/release-notes/issue-10523.md
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java
  src/test/java/edu/harvard/iq/dataverse/export/InternalExportProviderTest.java
Labels: Size: 3, FY26 Sprint 1, FY26 Sprint 2, FY26 Sprint 3, FY26 Sprint 4

#11551 Added a control to publishing a Dataset and cleaning dataversesubjects table
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/FinalizeDatasetPublicationCommand.java
  src/main/resources/db/migration/V6.7.0.1.sql
Labels: Size: 3, FY25 Sprint 25, FY25 Sprint 26, FY26 Sprint 1, FY26 Sprint 2, FY26 Sprint 3, FY26 Sprint 4

#11433 error handling cvoc filters
  src/main/java/edu/harvard/iq/dataverse/DatasetFieldServiceBean.java
  src/test/java/edu/harvard/iq/dataverse/DatasetFieldServiceBeanFilterResponseTest.java
  src/test/resources/json/cvoc-dans-config/AATClassification.json
  src/test/resources/json/cvoc-dans-config/abrArtifact.json
  src/test/resources/json/cvoc-dans-config/abrComplex.json
  src/test/resources/json/cvoc-dans-config/abrPeriod.json
  src/test/resources/json/cvoc-dans-config/abrRapportType.json
  src/test/resources/json/cvoc-dans-config/abrVerwervingswijze.json
  src/test/resources/json/cvoc-dans-config/audience.json
  src/test/resources/json/cvoc-dans-config/cessdaClassification.json
  src/test/resources/json/cvoc-dans-config/collection.json
  src/test/resources/json/cvoc-dans-config/collectionMode.json
  src/test/resources/json/cvoc-dans-config/elsstClassification.json
  src/test/resources/json/cvoc-dans-config/researchInstrument.json
  src/test/resources/json/cvoc-dans-config/samplingProcedureCV.json
  src/test/resources/json/cvoc-dans-config/timeMethod.json
  src/test/resources/json/cvoc-dans-config/unitOfAnalysys.json
  src/test/resources/json/cvoc-dans-value/AATClassification.json
  src/test/resources/json/cvoc-dans-value/abrArtifact.json
  src/test/resources/json/cvoc-dans-value/abrComplex.json
  src/test/resources/json/cvoc-dans-value/abrPeriod.json
  src/test/resources/json/cvoc-dans-value/abrRapportType.json
  src/test/resources/json/cvoc-dans-value/abrVerwervingswijze.json
  src/test/resources/json/cvoc-dans-value/audience.json
  src/test/resources/json/cvoc-dans-value/cessdaClassification.json
  src/test/resources/json/cvoc-dans-value/collection.json
  src/test/resources/json/cvoc-dans-value/collectionMode.json
  src/test/resources/json/cvoc-dans-value/elsstClassification.json
  src/test/resources/json/cvoc-dans-value/researchInstrument.json
  src/test/resources/json/cvoc-dans-value/samplingProcedureCV.json
  src/test/resources/json/cvoc-dans-value/timeMethod.json
  src/test/resources/json/cvoc-dans-value/unitOfAnalysis.json
Labels: Size: 3, FY25 Sprint 21, FY25 Sprint 22, FY25 Sprint 23, FY25 Sprint 24, FY25 Sprint 25, FY25 Sprint 26, FY26 Sprint 1, FY26 Sprint 2, FY26 Sprint 3, FY26 Sprint 4
