Repository IQSS/dataverse, pull requests merged in 2025-07, with the labels that each got.

#11583 use WSL not cmd.exe for Windows dev, simplify guides
  doc/release-notes/10606-windows-dev.md
  doc/sphinx-guides/source/developers/dev-environment.rst
  doc/sphinx-guides/source/developers/windows.rst
Labels: Type: Bug, Component: Containers, Size: 10, FY25 Sprint 25, FY25 Sprint 26, FY26 Sprint 1

#11610 make limit update a superuser only function
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/CreateDataverseCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/UpdateDataverseCommand.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonParser.java
  src/main/java/propertyFiles/Bundle.properties
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
  src/test/java/edu/harvard/iq/dataverse/api/DataversesIT.java
  src/test/java/edu/harvard/iq/dataverse/api/FilesIT.java
  src/test/java/edu/harvard/iq/dataverse/api/S3AccessIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: Type: Feature, Size: 3, D: Dataset: large number of files, GREI 5, FY25 Sprint 23, FY25 Sprint 24

#11281 External Search Refactor
  doc/release-notes/11281-ExternalSearch.md
  doc/sphinx-guides/source/api/search.rst
  doc/sphinx-guides/source/developers/index.rst
  doc/sphinx-guides/source/developers/search-services.rst
  doc/sphinx-guides/source/installation/config.rst
  pom.xml
  src/assembly/external-search-get.xml
  src/assembly/external-search-post.xml
  src/assembly/trivial-search-examples.xml
  src/main/docker/assembly.xml
  src/main/java/edu/harvard/iq/dataverse/DatasetPage.java
  src/main/java/edu/harvard/iq/dataverse/DataversePage.java
  src/main/java/edu/harvard/iq/dataverse/EjbDataverseEngine.java
  src/main/java/edu/harvard/iq/dataverse/api/Index.java
  src/main/java/edu/harvard/iq/dataverse/api/Meta.java
  src/main/java/edu/harvard/iq/dataverse/api/Search.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/CommandContext.java
  src/main/java/edu/harvard/iq/dataverse/mydata/DataRetrieverAPI.java
  src/main/java/edu/harvard/iq/dataverse/mydata/MyDataPage.java
  src/main/java/edu/harvard/iq/dataverse/search/AbstractExternalSearchServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/search/ConfigurableSearchService.java
  src/main/java/edu/harvard/iq/dataverse/search/GetExternalSearchServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/search/GoldenOldiesSearchServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/search/OddlyEnoughSearchServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/search/PostExternalSearchServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/search/SearchFilesServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/search/SearchIncludeFragment.java
  src/main/java/edu/harvard/iq/dataverse/search/SearchService.java
  src/main/java/edu/harvard/iq/dataverse/search/SearchServiceFactory.java
  src/main/java/edu/harvard/iq/dataverse/search/SolrSearchServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/search/savedsearch/SavedSearchServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/settings/JvmSettings.java
  src/main/java/edu/harvard/iq/dataverse/settings/SettingsServiceBean.java
  src/main/resources/META-INF/ext-search-get/edu.harvard.iq.dataverse.search.SearchService
  src/main/resources/META-INF/ext-search-post/edu.harvard.iq.dataverse.search.SearchService
  src/main/resources/META-INF/trivial-search/edu.harvard.iq.dataverse.search.SearchService
  src/test/java/edu/harvard/iq/dataverse/engine/TestCommandContext.java
Labels: Size: 10, FY25 Sprint 24, FY25 Sprint 25, FY25 Sprint 26, FY26 Sprint 1

#11619 XML Parsing Updates
  doc/release-notes/xmlutil.md
  doc/sphinx-guides/source/api/changelog.rst
  src/main/java/edu/harvard/iq/dataverse/api/EditDDI.java
  src/main/java/edu/harvard/iq/dataverse/api/imports/ImportDDIServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/api/imports/ImportGenericServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/authorization/providers/oauth2/impl/OrcidOAuth2AP.java
  src/main/java/edu/harvard/iq/dataverse/export/ddi/DdiExportUtil.java
  src/main/java/edu/harvard/iq/dataverse/harvest/client/FastGetRecord.java
  src/main/java/edu/harvard/iq/dataverse/ingest/tabulardata/impl/plugins/xlsx/XLSXFileReader.java
  src/main/java/edu/harvard/iq/dataverse/metadataimport/ForeignMetadataImportServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/util/FileUtil.java
  src/main/java/edu/harvard/iq/dataverse/util/xml/XmlPrinter.java
  src/main/java/edu/harvard/iq/dataverse/util/xml/XmlUtil.java
  src/main/java/edu/harvard/iq/dataverse/util/xml/XmlValidator.java
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
  src/test/java/edu/harvard/iq/dataverse/api/EditDDIIT.java
  src/test/java/edu/harvard/iq/dataverse/datavariable/VariableMetadataDDIParserTest.java
  src/test/java/edu/harvard/iq/dataverse/export/OpenAireExporterTest.java
  src/test/java/edu/harvard/iq/dataverse/util/xml/XmlUtilTest.java
Labels: Size: 3, FY26 Sprint 1

#11620 Fix Cache test failure
  src/test/java/edu/harvard/iq/dataverse/util/cache/CacheFactoryBeanTest.java
Labels: Size: 0.5, FY26 Sprint 1

#11609 Admin Guide: add Rclone to list of integrations
  doc/release-notes/11608-rclone.md
  doc/sphinx-guides/source/admin/integrations.rst
Labels: Size: 0.5

#11655 switch base.image.version back to non-revision (post 6.7 release)
  modules/dataverse-parent/pom.xml
Labels: Size: 0.5

#11617 Include isAdvancedSearchFieldType property
  doc/release-notes/11614-include-isAdvancedSeachField-property.md
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java
  src/test/java/edu/harvard/iq/dataverse/api/MetadataBlocksIT.java
Labels: Type: Feature, Size: 0.5, SPA, GREI Re-arch, Original size: 0.5, FY26 Sprint 1, SPA.Q3.2025.1, FY26 Sprint 2

#11439 File Metadata Update - Empty values clear fields
  doc/release-notes/11243-editmetadata-api-extension.md
  doc/release-notes/11392-edit-file-metadata-empty-values.md
  doc/sphinx-guides/source/api/changelog.rst
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/api/AbstractApiBean.java
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/main/java/edu/harvard/iq/dataverse/api/Files.java
  src/main/java/edu/harvard/iq/dataverse/datasetutility/OptionalFileParams.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java
  src/main/java/propertyFiles/Bundle.properties
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
  src/test/java/edu/harvard/iq/dataverse/api/FilesIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
  src/test/java/edu/harvard/iq/dataverse/datasetutility/OptionalFileParamsTest.java
Labels: Type: Bug, Size: 10, GREI Re-arch, Original size: 10, FY25 Sprint 21, FY25 Sprint 22, FY25 Sprint 23, FY25 Sprint 24, FY25 Sprint 25, FY25 Sprint 26, FY26 Sprint 1, SPA.Q3.2025, FY26 Sprint 2

#11636 Bug: block guest from calling api
  doc/release-notes/11465-api-fetch-download-size-file-count.md
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/main/java/propertyFiles/Bundle.properties
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
  src/test/java/edu/harvard/iq/dataverse/api/FilesIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: Type: Bug, Size: 10, SPA, GREI Re-arch, FY24 Sprint 23, Original size: 10, FY25 Sprint 24, FY26 Sprint 1, SPA.Q3.2025, FY26 Sprint 2

#11569 fix: don't store duplicates in subtreePaths
  src/main/java/edu/harvard/iq/dataverse/search/IndexServiceBean.java
Labels: Size: 3, FY25 Sprint 25, FY25 Sprint 26, FY26 Sprint 1, FY26 Sprint 2

#11640 In guides, suggest trying an update to the geospatial metadata block
  doc/sphinx-guides/source/user/appendix.rst
Labels: Size: 0.5, FY26 Sprint 1, FY26 Sprint 2

#11565 Get Dataverse templates API endpoints
  doc/release-notes/11562-templates-api.md
  doc/sphinx-guides/source/_static/api/dataverse-template.json
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/EjbDataverseEngine.java
  src/main/java/edu/harvard/iq/dataverse/Template.java
  src/main/java/edu/harvard/iq/dataverse/api/Dataverses.java
  src/main/java/edu/harvard/iq/dataverse/api/dto/NewTemplateDTO.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/CommandContext.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/CreateTemplateCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/ListDataverseTemplatesCommand.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java
  src/main/java/propertyFiles/Bundle.properties
  src/test/java/edu/harvard/iq/dataverse/api/DataversesIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
  src/test/java/edu/harvard/iq/dataverse/engine/TestCommandContext.java
  src/test/java/edu/harvard/iq/dataverse/engine/command/impl/CreateTemplateCommandTest.java
  src/test/java/edu/harvard/iq/dataverse/engine/command/impl/ListDataverseTemplatesCommandTest.java
Labels: Size: 3, SPA, GREI Re-arch, Original size: 3, FY25 Sprint 26, FY26 Sprint 1, SPA.Q3.2025, FY26 Sprint 2

#11664 support read/unread status for notifications
  doc/release-notes/11650-unread.md
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/UserNotificationServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/api/Notifications.java
  src/main/java/edu/harvard/iq/dataverse/authorization/providers/builtin/DataverseUserPage.java
  src/test/java/edu/harvard/iq/dataverse/api/NotificationsIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: Type: Feature, Size: 10, SPA, Original size: 10, FY26 Sprint 2, SPA.Q3.2025.6

#11668 11634 api get available file categories
  doc/release-notes/11634-get-dataset-file-available-categories-api.md
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: Type: Feature, Size: 10, SPA, GREI Re-arch, Original size: 10, FY26 Sprint 2, SPA.Q3.2025.5

#11611 Dataset page: Use params for clarity and efficiency
  src/main/webapp/dataset.xhtml
  src/main/webapp/editFilesFragment.xhtml
  src/main/webapp/file-info-fragment.xhtml
  src/main/webapp/file-versions.xhtml
  src/main/webapp/filesFragment.xhtml
Labels: Size: 3, FY26 Sprint 1, FY26 Sprint 2

#11599 optimize check for existing role assignment
  src/main/java/edu/harvard/iq/dataverse/DataverseRoleServiceBean.java
Labels: Size: 3, FY25 Sprint 26, FY26 Sprint 1, FY26 Sprint 2
