Repository IQSS/dataverse, pull requests merged in 2025-01, with the labels that each got.

#10994 Published datasets should contain files
  doc/release-notes/10981-published-datasets-should-contain-files.md
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/Dataverse.java
  src/main/java/edu/harvard/iq/dataverse/api/Dataverses.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/PublishDatasetCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/UpdateDataverseAttributeCommand.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonParser.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java
  src/main/java/propertyFiles/Bundle.properties
  src/main/resources/db/migration/V6.5.0.1.sql
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
Labels: Size: 30, FY25 Sprint 9, FY25 Sprint 10, FY25 Sprint 11, FY25 Sprint 12, FY25 Sprint 14

#11115 in "requested access" email, add space after link to prevent it from breaking
  doc/release-notes/10384-link.md
  src/main/java/propertyFiles/Bundle.properties
Labels: Type: Bug, Feature: Notifications, Size: 0.5, FY25 Sprint 12, FY25 Sprint 14

#11111 document S3 RBAC preference on v5.14+
  doc/sphinx-guides/source/installation/config.rst
Labels: Size: 0.5, FY25 Sprint 14

#10887 feat: index numerical and date fields in Solr with appropriate types + more targeted search result highlighting
  conf/solr/schema.xml
  doc/release-notes/10887-solr-field-types.md
  src/main/java/edu/harvard/iq/dataverse/DatasetFieldType.java
  src/main/java/edu/harvard/iq/dataverse/search/IndexServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/search/SearchServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/search/SolrField.java
  src/test/java/edu/harvard/iq/dataverse/api/SearchIT.java
Labels: Type: Feature, Size: 3, GREI 3, FY25 Sprint 10, FY25 Sprint 11, FY25 Sprint 12, FY25 Sprint 14

#11017 Improvement and internationalization of harvest status
  doc/release-notes/9294-improvement-and-internationalization-of-harvest-status.md
  src/main/java/edu/harvard/iq/dataverse/harvest/client/ClientHarvestRun.java
  src/main/java/edu/harvard/iq/dataverse/harvest/client/HarvesterServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/harvest/client/HarvestingClient.java
  src/main/java/edu/harvard/iq/dataverse/harvest/client/HarvestingClientServiceBean.java
  src/main/java/propertyFiles/Bundle.properties
  src/test/java/edu/harvard/iq/dataverse/api/HarvestingClientsIT.java
Labels: Type: Bug, Size: 3, FY25 Sprint 10, FY25 Sprint 11, FY25 Sprint 12, FY25 Sprint 14

#10778 Extension of API `{id}/versions` and `{id}/versions/{versionId}` with an optional ``excludeMetadataBlocks`` parameter
  doc/release-notes/10171-exlude-metadatablocks.md
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: Type: Feature, Size: 3, FY25 Sprint 11, FY25 Sprint 12, FY25 Sprint 14

#11066 remove duplicate DatasetFieldTypes
  doc/release-notes/10472-review-modify-jsonprinter-for-datasetfieldtype.md
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java
  src/test/java/edu/harvard/iq/dataverse/api/DataversesIT.java
  src/test/java/edu/harvard/iq/dataverse/api/MetadataBlocksIT.java
  src/test/java/edu/harvard/iq/dataverse/util/json/JsonPrinterTest.java
Labels: Feature: Metadata, Feature: API, Type: Bug, Size: 10, FY25 Sprint 12, FY25 Sprint 14

#11114 IQSS/11113 fix file perm doc creation
  doc/release-notes/11113-avoid-orphan-perm-docs.md
  src/main/java/edu/harvard/iq/dataverse/DataFile.java
  src/main/java/edu/harvard/iq/dataverse/search/SolrIndexServiceBean.java
Labels: Size: 3

#11086 Prevent NPE in MyData when all dataverses are harvested dataverses
  doc/release-notes/11083-mydata-npe-with-harvested-dataverses.md
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/mydata/MyDataFinder.java
  src/test/java/edu/harvard/iq/dataverse/api/DataRetrieverApiIT.java
Labels: Type: Bug, Size: 3, FY25 Sprint 12, FY25 Sprint 14

#11144 Update Dataverse API removes metadatablocks if optional params are omitted
  doc/release-notes/11130-update-dataverse-api-remove-metadatablocks.md
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/api/Dataverses.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/AbstractWriteDataverseCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/CreateDataverseCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/UpdateDataverseCommand.java
  src/main/java/propertyFiles/Bundle.properties
  src/test/java/edu/harvard/iq/dataverse/api/DataversesIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: Type: Bug, Size: 30

#10612 API Update global role + fixed issue with GUI custom role edition
  doc/release-notes/8808-10575-update-global-role.md
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/DataverseRoleServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/api/Admin.java
  src/main/java/edu/harvard/iq/dataverse/api/dto/RoleDTO.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/CreateRoleCommand.java
  src/main/java/edu/harvard/iq/dataverse/search/SolrIndexServiceBean.java
Labels: Type: Feature, Size: 3, FY25 Sprint 6, FY25 Sprint 8, FY25 Sprint 10, FY25 Sprint 11, FY25 Sprint 12, FY25 Sprint 14

#11038 Harvesting : Add granularity to ListRecords when using from parameter
  doc/release-notes/11038-unconsidered-harvesting-granularity.md
  src/main/java/edu/harvard/iq/dataverse/harvest/client/oai/OaiHandler.java
Labels: Type: Bug, Size: 3, FY25 Sprint 11, FY25 Sprint 12, FY25 Sprint 14

#10521 IQSS/10516 fix perma legacy support
  doc/release-notes/10516_legacy_permalink_config_fix.md
  src/main/java/edu/harvard/iq/dataverse/pidproviders/PidProviderFactoryBean.java
  src/main/java/edu/harvard/iq/dataverse/pidproviders/PidUtil.java
  src/test/java/edu/harvard/iq/dataverse/pidproviders/PidUtilTest.java
Labels: Type: Bug, Size: 3, Consider For Next Release, FY25 Sprint 8, FY25 Sprint 9, FY25 Sprint 10, FY25 Sprint 12, FY25 Sprint 14

#11134 IQSS/11133-search-fix
  doc/release-notes/11133-search-fix.md
  src/main/java/edu/harvard/iq/dataverse/search/SearchServiceBean.java
Labels: Size: 3, FY25 Sprint 14

#11116 Correct /api/roles API to respond with 403 Forbidden (not 401 Unauthorized) when auth is good but no permission
  doc/release-notes/10340-forbidden.md
  doc/sphinx-guides/source/api/changelog.rst
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/api/AbstractApiBean.java
  src/test/java/edu/harvard/iq/dataverse/api/RolesIT.java
Labels: Size: 10, FY25 Sprint 12, FY25 Sprint 14, FY25 Sprint 15

#11061 sql script/flyway to fix file access requests
  doc/release-notes/10714-access-requests-missing-since-upgrade-v6-0.md
  src/main/resources/db/migration/V6.5.0.2.sql
Labels: Type: Bug, Size: 3, FY25 Sprint 11, FY25 Sprint 12, FY25 Sprint 14, FY25 Sprint 15

#11096 IQSS/11095- Account for multivalue needed by cvoc scripts
  doc/release-notes/11095-fix-extcvoc-indexing.md
  doc/sphinx-guides/source/admin/metadatacustomization.rst
  doc/sphinx-guides/source/installation/config.rst
  src/main/java/edu/harvard/iq/dataverse/api/Index.java
Labels: Size: 3, FY25 Sprint 12, FY25 Sprint 14, FY25 Sprint 15

#11118 add ROR as an Author Identifier Type
  doc/release-notes/11075-ror.md
  doc/sphinx-guides/source/admin/metadatacustomization.rst
  doc/sphinx-guides/source/user/dataset-management.rst
  scripts/api/data/metadatablocks/citation.tsv
  src/main/java/edu/harvard/iq/dataverse/ExternalIdentifier.java
  src/main/java/edu/harvard/iq/dataverse/pidproviders/doi/XmlMetadataTemplate.java
  src/main/java/propertyFiles/citation.properties
  src/test/java/edu/harvard/iq/dataverse/DatasetFieldValueValidatorTest.java
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
  src/test/java/edu/harvard/iq/dataverse/pidproviders/doi/datacite/XmlMetadataTemplateTest.java
Labels: Type: Feature, Feature: Metadata, Size: 3, GREI 2, FY25 Sprint 12, FY25 Sprint 14, FY25 Sprint 15

#11135 Format Solr schema.xml using update-fields.sh on Linux
  doc/sphinx-guides/source/admin/metadatacustomization.rst
  doc/sphinx-guides/source/container/configbaker-image.rst
  doc/sphinx-guides/source/developers/tips.rst
Labels: Size: 0.5, FY25 Sprint 14, FY25 Sprint 15

#9013 Harvest: map publisher tag to distributorName
  doc/release-notes/8739-publisher-during-harvesting.md
  doc/sphinx-guides/source/admin/harvestclients.rst
  src/main/resources/db/migration/V6.5.0.3.sql
  src/main/resources/db/migration/afterMigrate__1-7256-upsert-referenceData.sql
  src/test/java/edu/harvard/iq/dataverse/api/HarvestingClientsIT.java
Labels: Type: Feature, Feature: Harvesting, Size: 10, GREI 3, FY25 Sprint 11, FY25 Sprint 12, FY25 Sprint 14, FY25 Sprint 15

#11150 Allow collections to be moved in the superuser dashboard
  doc/release-notes/10304-add-move-dataverse-collection.md
  src/main/java/edu/harvard/iq/dataverse/Dataset.java
  src/main/java/edu/harvard/iq/dataverse/DatasetServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/Dataverse.java
  src/main/java/edu/harvard/iq/dataverse/DataverseServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/dashboard/DashboardMoveDatasetPage.java
  src/main/java/edu/harvard/iq/dataverse/dashboard/DashboardMoveDataversePage.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/MoveDatasetCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/MoveDataverseCommand.java
  src/main/java/propertyFiles/Bundle.properties
  src/main/webapp/dashboard-movedataset.xhtml
  src/main/webapp/dashboard-movedataverse.xhtml
  src/main/webapp/dashboard.xhtml
Labels: Size: 3, FY25 Sprint 15

#11092 clarify "making releases" process based on 6.5 release experience
  doc/sphinx-guides/source/developers/making-releases.rst
Labels: Size: 0.5, FY25 Sprint 14, FY25 Sprint 15

#11140 prevent DOCS_AND_FREQS_AND_POSITIONS Solr error
  doc/release-notes/10887-solr-field-types.md
Labels: Size: 3, FY25 Sprint 14, FY25 Sprint 15

#11168 Fix 500 errors when uploading single controlled vocab or compound field values to editMetadata API
  doc/sphinx-guides/source/_static/api/dataset-add-single-compound-field-metadata.json
  doc/sphinx-guides/source/_static/api/dataset-add-single-cvoc-field-metadata.json
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
Labels: Size: 3, FY25 Sprint 15

#11099 API Guide: update auth section on bearer tokens
  doc/sphinx-guides/source/api/auth.rst
Labels: Size: 0.5

#11124 Dataverse Featured Items support
  doc/release-notes/10943-featured-items.md
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/Dataverse.java
  src/main/java/edu/harvard/iq/dataverse/EjbDataverseEngine.java
  src/main/java/edu/harvard/iq/dataverse/api/AbstractApiBean.java
  src/main/java/edu/harvard/iq/dataverse/api/Access.java
  src/main/java/edu/harvard/iq/dataverse/api/DataverseFeaturedItems.java
  src/main/java/edu/harvard/iq/dataverse/api/Dataverses.java
  src/main/java/edu/harvard/iq/dataverse/api/dto/NewDataverseFeaturedItemDTO.java
  src/main/java/edu/harvard/iq/dataverse/api/dto/UpdatedDataverseFeaturedItemDTO.java
  src/main/java/edu/harvard/iq/dataverse/dataverse/featured/DataverseFeaturedItem.java
  src/main/java/edu/harvard/iq/dataverse/dataverse/featured/DataverseFeaturedItemServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/CommandContext.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/exception/InvalidCommandArgumentsException.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/AbstractWriteDataverseFeaturedItemCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/CreateDataverseFeaturedItemCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/DeleteDataverseCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/DeleteDataverseFeaturedItemCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/GetDataverseFeaturedItemCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/ListDataverseFeaturedItemsCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/UpdateDataverseFeaturedItemCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/UpdateDataverseFeaturedItemsCommand.java
  src/main/java/edu/harvard/iq/dataverse/settings/JvmSettings.java
  src/main/java/edu/harvard/iq/dataverse/util/FileUtil.java
  src/main/java/edu/harvard/iq/dataverse/util/MarkupChecker.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java
  src/main/java/propertyFiles/Bundle.properties
  src/main/resources/META-INF/microprofile-config.properties
  src/test/java/edu/harvard/iq/dataverse/api/DataverseFeaturedItemsIT.java
  src/test/java/edu/harvard/iq/dataverse/api/DataversesIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
  src/test/java/edu/harvard/iq/dataverse/engine/TestCommandContext.java
  src/test/java/edu/harvard/iq/dataverse/engine/command/impl/CreateDataverseFeaturedItemCommandTest.java
  src/test/java/edu/harvard/iq/dataverse/util/MarkupCheckerTest.java
  tests/integration-tests.txt
Labels: Size: 10, SPA, GREI Re-arch, Original size: 10, SPA.Q4, SPA.Q1, FY25 Sprint 15

#11162 add new feedback api
  doc/release-notes/11129-send-feedback-to-contacts.md
  doc/sphinx-guides/source/api/native-api.rst
  doc/sphinx-guides/source/installation/config.rst
  src/main/java/edu/harvard/iq/dataverse/api/SendFeedbackAPI.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/CheckRateLimitForDatasetFeedbackCommand.java
  src/main/java/edu/harvard/iq/dataverse/feedback/Feedback.java
  src/main/java/edu/harvard/iq/dataverse/settings/SettingsServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/util/SystemConfig.java
  src/main/java/edu/harvard/iq/dataverse/util/cache/CacheFactoryBean.java
  src/main/java/edu/harvard/iq/dataverse/util/cache/RateLimitUtil.java
  src/main/java/propertyFiles/Bundle.properties
  src/test/java/edu/harvard/iq/dataverse/api/SendFeedbackApiIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
  src/test/java/edu/harvard/iq/dataverse/util/cache/CacheFactoryBeanTest.java
  src/test/java/edu/harvard/iq/dataverse/util/cache/RateLimitUtilTest.java
  tests/integration-tests.txt
Labels: Type: Feature, Size: 30, GREI Re-arch, SPA.Q4.9, FY25 Sprint 14, SPA.Q1, FY25 Sprint 15, FY25 Sprint 16
