Repository IQSS/dataverse, pull requests merged in 2025-04, with the labels that each got.

#11359 allow for tag replacement
  doc/release-notes/11292-update-tabular-tags-with-replace.md
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/api/Files.java
  src/test/java/edu/harvard/iq/dataverse/api/FilesIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: Type: Bug, Size: 10, SPA, Original size: 10, FY25 Sprint 19, FY25 Sprint 20

#11375 remove unused show_my_data Search API parameter
  doc/release-notes/11287-show_my_data.md
  doc/sphinx-guides/source/api/changelog.rst
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/api/Search.java
Labels: Type: Feature, Size: 10, SPA, Original size: 10, FY25 Sprint 18, SPA.Q1.8, FY25 Sprint 19, FY25 Sprint 20

#11172 fix: don't duplicate nested compound fields in metadataBlocks returned by search API
  doc/release-notes/11172-fix-search-api-nested-metadata-fields.md
  src/main/java/edu/harvard/iq/dataverse/search/SolrSearchResult.java
Labels: Size: 10, FY25 Sprint 18, FY25 Sprint 19, FY25 Sprint 20

#11403 add replace to update category api
  doc/release-notes/11401-update-categories-with-replace.md
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/api/Files.java
  src/test/java/edu/harvard/iq/dataverse/api/FilesIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: Size: 3, SPA, SPA.Q1.6, FY25 Sprint 20, SPA.Q2

#11390 11376 add version note to diff summary
  src/main/java/edu/harvard/iq/dataverse/DatasetVersionDifference.java
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/main/java/propertyFiles/Bundle.properties
  src/main/webapp/dataset.xhtml
Labels: Type: Feature, Size: 10, SPA, GREI Re-arch, Original size: 10, SPA.Q1.6, FY25 Sprint 20, SPA.Q2

#11357 Payara 6.2025.3 Update
  doc/release-notes/11357-Payara-Update.md
  doc/sphinx-guides/source/developers/classic-dev-env.rst
  doc/sphinx-guides/source/installation/prerequisites.rst
  doc/sphinx-guides/source/qa/test-automation.md
  modules/dataverse-parent/pom.xml
Labels: Size: 10, FY25 Sprint 19, FY25 Sprint 20, FY25 Sprint 21

#10567 Reconcile the PID of a Dataset (If Multiple PID Providers Are Enabled)
  doc/release-notes/10567-feat-reconcilepid.md
  doc/sphinx-guides/source/admin/user-administration.rst
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/AlternativePersistentIdentifier.java
  src/main/java/edu/harvard/iq/dataverse/DvObject.java
  src/main/java/edu/harvard/iq/dataverse/DvObjectServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/MailServiceBean.java
  src/main/java/edu/harvard/iq/dataverse/UserNotification.java
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/main/java/edu/harvard/iq/dataverse/authorization/providers/builtin/DataverseUserPage.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/AbstractDatasetCommand.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/ReconcileDatasetPidCommand.java
  src/main/java/edu/harvard/iq/dataverse/pidproviders/PidProviderFactoryBean.java
  src/main/java/edu/harvard/iq/dataverse/util/MailUtil.java
  src/main/java/propertyFiles/Bundle.properties
  src/main/webapp/dataverseuser.xhtml
  src/test/java/edu/harvard/iq/dataverse/engine/command/impl/ReconcilePIDCommandTest.java
  src/test/java/edu/harvard/iq/dataverse/mocks/MocksFactory.java
Labels: Type: Feature, Size: 20, FY25 Sprint 20, FY25 Sprint 21

#11385 10520 dataset type licenses
  doc/release-notes/10520-datasetType-enable-licenses.md
  doc/sphinx-guides/source/api/native-api.rst
  scripts/api/data/dataset-create-new-with-type.json
  src/main/java/edu/harvard/iq/dataverse/DatasetPage.java
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/main/java/edu/harvard/iq/dataverse/dataset/DatasetType.java
  src/main/java/edu/harvard/iq/dataverse/engine/command/impl/UpdateDatasetTypeAvailableLicensesCommand.java
  src/main/java/edu/harvard/iq/dataverse/util/json/JsonParser.java
  src/main/webapp/dataset-license-terms.xhtml
  src/test/java/edu/harvard/iq/dataverse/api/DatasetTypesIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: Type: Feature, Size: 10, GREI 6, GREI Year 3, FY25 Sprint 19, FY25 Sprint 20, FY25 Sprint 21

#11408 Encoding of properties values in UTF-8
  src/main/java/propertyFiles/Bundle.properties
  src/main/java/propertyFiles/astrophysics.properties
  src/main/java/propertyFiles/geospatial.properties
Labels: Feature: Internationalization, Size: 20, FY25 Sprint 20, FY25 Sprint 21

#11424 Adding rate limiting statistics api
  doc/release-notes/11413-rate-limiting-statistics-api.md
  doc/sphinx-guides/source/admin/index.rst
  doc/sphinx-guides/source/admin/rate-limiting.rst
  src/main/java/edu/harvard/iq/dataverse/api/Admin.java
  src/main/java/edu/harvard/iq/dataverse/util/cache/CacheFactoryBean.java
  src/main/java/edu/harvard/iq/dataverse/util/cache/RateLimitUtil.java
  src/test/java/edu/harvard/iq/dataverse/api/SendFeedbackApiIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: Type: Feature, Size: 20, FY25 Sprint 21

#11437 UTF8TestFix
  src/main/java/edu/harvard/iq/dataverse/api/Dataverses.java
  src/test/java/edu/harvard/iq/dataverse/api/DataversesIT.java
Labels: Size: 3

#11412 Widget fix
  src/main/webapp/dataset-widgets.xhtml
  src/main/webapp/resources/js/widgets.js
  src/main/webapp/themeAndWidgetsFragment.xhtml
Labels: Size: 3

#11378 EditDDI API empty frequency bug
  src/main/java/edu/harvard/iq/dataverse/api/EditDDI.java
  src/main/java/edu/harvard/iq/dataverse/datavariable/VariableMetadataDDIParser.java
  src/test/java/edu/harvard/iq/dataverse/api/EditDDIIT.java
Labels: Size: 3, FY25 Sprint 20, FY25 Sprint 21

#11417 Memory Improvements in Export/Ingest
  doc/release-notes/11417-export-improvements.md
  src/main/java/edu/harvard/iq/dataverse/dataaccess/TabularSubsetGenerator.java
  src/main/java/edu/harvard/iq/dataverse/export/DDIExporter.java
  src/main/java/edu/harvard/iq/dataverse/export/ddi/DdiExportUtil.java
  src/main/java/edu/harvard/iq/dataverse/export/dublincore/DublinCoreExportUtil.java
  src/main/java/edu/harvard/iq/dataverse/export/openaire/OpenAireExportUtil.java
  src/main/java/edu/harvard/iq/dataverse/ingest/IngestServiceBean.java
Labels: Size: 3

#11388 add if workflows is IQSS running
  .github/workflows/deploy_beta_testing.yml
Labels: Size: 0.5, FY25 Sprint 20, FY25 Sprint 21, FY25 Sprint 22

#11444 IQSS/11394 version note bug fix
  doc/release-notes/11394-versionNoteBug.md
  src/main/java/edu/harvard/iq/dataverse/DatasetPage.java
Labels: Size: 3, FY25 Sprint 22

#11445 HDV-247: Guestbook at Request - add space to options
  src/main/java/edu/harvard/iq/dataverse/SettingsWrapper.java
Labels: Size: 3

#10942 Guides: improve navigation
  doc/release-notes/10941-remove-custom-guides-navbar.md
  doc/sphinx-guides/source/_static/docsdataverse_org.css
  doc/sphinx-guides/source/_static/navbar_from_dataverse_org.js
  doc/sphinx-guides/source/_templates/navbar.html
  doc/sphinx-guides/source/conf.py
  doc/sphinx_bootstrap_theme/bootstrap/globaltoc.html
  doc/sphinx_bootstrap_theme/bootstrap/layout.html
  doc/sphinx_bootstrap_theme/bootstrap/navbar.html
  doc/sphinx_bootstrap_theme/bootstrap/navbartoc.html
  doc/sphinx_bootstrap_theme/bootstrap/theme.conf
Labels: Size: 3, FY25 Sprint 19, FY25 Sprint 20, FY25 Sprint 21, FY25 Sprint 22

#11271 DANS - Multifile edit
  doc/release-notes/11271-edit-files-metadata-api-call
  doc/sphinx-guides/source/api/native-api.rst
  src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
  src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
  src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
Labels: GDCC: DANS, Size: 3, FY25 Sprint 21, FY25 Sprint 22
